In [1]:

# PASO 1: Abrimos librerias necesarias
import json
import pandas as pd

In [2]:
import json

archivos = [
    "Files/api_artistas_hip_hop.json", 
    "Files/datos_latin_apilastfm.json", 
    "Files/datos_pop_apilastfm.json", 
    "Files/datos_rap_apilastfm.json",
    "Files/datos_rock_apilastfm.json"
]

lista_unificada = []

for nombre in archivos:
    with open(nombre, "r", encoding="utf-8") as f:
        datos = json.load(f)
        
        for artista in datos:
            # --- AQUÍ ESTÁ EL TRUCO ---
            # Si existe "biografía" (con tilde), la movemos a "biografia" (sin tilde)
            if "biografía" in artista:
                artista["biografia"] = artista.pop("biografía")
            
            lista_unificada.append(artista)

In [3]:
len(lista_unificada)

6057

In [4]:
from collections import Counter
nombres = [str(a.get("artista")).strip().lower() for a in lista_unificada]
duplicados = [item for item, count in Counter(nombres).items() if count > 1]
print(f"Artistas que Python detecta como duplicados: {duplicados}")

Artistas que Python detecta como duplicados: ['xxxtentacion', 'the alchemist', 'natos y waor', 'arcángel', 'bad bunny', 'losniñosdelcaminito', 'khea', 'duki', 'cazzu', 'becky g', 'prince royce', 'dj luian', 'mambo kingz', 'anuel aa', 'c. tangana', 'kanye west', 'kidd keo', 'delaossa', 'j.moods', 'trueno', 'blake', 'j-hope', 'soolking', 'matasvandals', 'da silva', 'rels b', 'diplo', 'fernandocosta', 'chicho beats', 'denom', 'nadal015', 'kaze', 'el perla', 'drake', 'fazzini', 'franky style', 'moha la squale', 'miranda', 'wos', 'javi bambini cattivi', 'alemán', 'revol', 'j balvin', 'de la ghetto', 'dirty porko', 'drefquila', 'lil pump', 'swae lee', 'maluma', 'trippie redd', 'eladio carrion', 'big soto', 'ysy a', 'hard gz', 'eminem', 'mac miller', 'lil gz', 'calero ldn', 'trap capos', 'noriel', 'bryant myers', 'walls', 'el jincho', 'sfdk', 'cardi b', 'lil baby', 'gunna', 'costa', 'ninho', 'residente', 'nicky jam', 'a boogie wit da hoodie', 'post malone', 'nanpa básico', 'toteking', 'bizarrap', '3robi', 'mula b', 'daddy yankee', 'farruko', 'miky woodz', 'maes', 'booba', 'akapellah', 'fntxy', 'jamby el favo', 'ecko', 'seven kayne', 'omar varela', "rim'k", 'metro boomin', 'offset', 'ñengo flow', 'joey bada$$', 'kids see ghosts', 'cosculluela', 'migos', 'yung sarria', 'crudo means raw', 'aaron may', 'dinos', 'nav', 'rejjie snow', 'aminé', 'pablo chill-e', 'redimi2', 'playboi carti', 'young thug', 'cejaz negraz', 'gera mx', 'khaled', 'marcianos crew', 'dani ribba', 'neo pistea', 'millonario', 'lacrim', 'saint jhn', 'capo plaza', 'sfera ebbasta', 'royce da 5\'9"', 'g-eazy', 'westside gunn', 'conway the machine', 'lary over', 'aerophon', 'quavo', 'awon', 'phoniks', 'kendrick lamar', 'j. cole', 'bas', 'sidhu moose wala', "heuss l'enfoiré", 'a$ap rocky', 'nipsey hussle', 'la gra$a', 'granuja', 'zof ziro', 'doble porción', 'métricas frías', 'mañas ru-fino', 'pnl', 'cartel de santa', 'ca7riel & paco amoroso', 'niska', 'anitta', 'rochy rd', 'sch', 'dharius', 'luck ra', 'kali uchis', 'tyler, the creator', 'la santa grifa', '6lack', 'alcolirykoz', 'logic', 'wiz khalifa', 'al2 el aldeano', 'fratelli-b', 'scoot da kidd', 'bfd', 'd-weez', 'k kutta', 'solareye', 'quan duke', 'jairzinho', 'c.w. da youngblood', 's beater', 'sean gonzalez', "john'nay lasha", 'csaba', 'hyu', 'benjahvites', 'zorimawi', 'conjuro epiléptico', 'the jacka', 'hancoq', 'preme dibiasi', 'baby brown', 'nyanda', 'shabzi madallion', 'badhabitz', 'bko', 'hoodini', 'lil los', 'ampichino', 'chey dolla', 'q052', 'the architect', 'mill bill', 'rich the factor', 'swelto', 'factor', '12mé', 'dj spinna', 'oriole', 'tal hefter', 'blezz', 'nati hassid', 'шеff', 'ryda', 'vaze haze', 'eazy racks', 'camb', 'g-rdz', 'thug lucciano', 'cinnay', 'козачок', 'gena', 'j-wats', 'ace cino', 'cmdwn', 'fiji', 'castro', 'pe2ny', 'chip charlez', 'micall parknsun', 'lay lay', 'ofiri', 'snow', 'tao quit', 'lady j', 'phidizz', 'paper tiger', 'arce', 'ele a el dominio', 'lil tecca', 'al safir', 'jul', 'paulo londra', 'mauri', 'zaidbreak', 'rick ross', 'nicki nicole', 'grind', 'los hijos de la luna', 'lágrimas de sangre', 'hoke', 'atari hanzo', 'santa fe klan', 'neto peña', 'yoss bones', 'amenazzy', 'myke towers', 'juice wrld', 'ill pekeño', 'nf', 'a$ap ferg', 'charles ans', 'alka produce', 'frijo', 'mustard', 'john c', 'bhavi', 'el chojin', 'ynw melly', 'ed sheeran', '50 cent', 'dillom', 'meek mill', 'santoz', 'fuego', 'midel', 'dreamville', 'dababy', 'loyle carner', 'moonkey', 'polimá westcoast', 'farid bang', 'french montana', 'russ millions', 'tion wayne', 'aitch', 'oboy', 'koba lad', 'ty dolla $ign', 'mgk', 'bardero$', 'naps', 'el arkeologo', 'doble porcion', 'ashafar', 'plk', 'zetazeta', 'tyga', 'nicki minaj', 'robot95', 'baby gang', 'djadja & dinaz', 'apache', 'hamza', 'aya nakamura', 'lefty sm', 'dowba montana', 'jid', 'smino', 'zxmyr', 'mc davo', 'denzel curry', 'deejohend', 'dtf', 'ap dhillon', 'lazza', 'sleepy hallow', 'sheff g', 'pashanim', 'marracash', 'rich vagos', 'jay romero', 'omg oumy gueye', 'old grape god', 'love guru', 'bergmál', 'sarafa', 'elemental', 'guy mar', 'bruce banna', 'icaki', 'vinci', 'gonzo g', 'kenny k-shot', 'atk', 'brianna perry', 'optic bloom', 'cliff notez', 'duckman', 'atchi', 'st!llness', 'vagan', 'brighty', 'zuti', 'spectacular diagnostics', 'najee janey', 'craig mack', 'hamed slash', 'richie ledreagle', 'jacin trill', 'leafs', 'nicko', 'munch lauren', 'mula kkhan', 'dubb saq', 'ice one', 'mad stage', 'lil skritt', 'ramson badbonez', 'lil p', 'miks', 'ruggedman', 'reklews', 'bang on!', 'stewie g', 'subliminal', 'bad balance', 'ironik', 'fat jack', 'mase', 'ben jones', 'blauwe uil', 'blackface', 'm7', 'zaman', 'nathy peluso', 'wise', 'beny jr', 'dualy', 'lunay', 'jhayco', 'darell', 'brray', 'ayax y prok', 'serko', 'taiu', 'tatool', 'recycled j', 'kase.o', 'agust d', 'yung beef', 'pipo beatz', 'el alfa', 'ozuna', 'secreto "el famoso biberon"', 'yesan 雪山', 'cyril kamer', 'moha the b', 'mayo 214', 'luck', 'kid cudi', 'fulston', 'jack harlow', 'lil nas x', 'ergo pro', 'future', 'stormy', 'internet money', 'boef', 'club hats', 'luar la l', 'homer el mero mero', 'buhodermia 夜', 'kofs', 'freddie gibbs', 'lucho ssj', 'népal', 'ovi', 'natanael cano', 'gambi', 'jauria santa', 'timal', 'alvaro diaz', 'freeze corleone', 'gambeta', 'los nandez', 'mister you', 'gurinder gill', 'gminxr', 'luis7lunes', 'afterclass', 'fousheé', 'josylvio', 'iziou', 'lil uzi vert', 'lil yachty', 'king von', 'lil durk', 'tory lanez', 'benny the butcher', 'zola', 'guè', 'almanegra', 'shiva', 'rucorap', 'austin fox 狐', 'louie ray', 'wes', 'tori fixx', 'мойша эскобар', 'atila', 'nazar', 'lil malice', 'mad dogg', 'dope boys bapele', 'eedris abdulkareem', 'craic boi mental', 'ricca razor sharp', 'd knowledge', 'mmp family', 'an ty', 'lizzo', 'bad royale', 'bigg nugg', 'b.glenn', 'uknwn', 'yung cat', 'groovy jo', 'vigos', 'altervers', 'hudson mohawke', 'king macarella', 'pyoot', 'free radicals', 'theophilus london', 'kirko bangz', 'slimm', '2t', 'young ellens', 'shrekdimc', 'tzukush', 'goldenb', 'connis', 'dintleonthetrack', 'pce bj', 'yung verbal', 'nigma', 'morad', 'tiago pzk', 'rvfv', 'cano', 'ptazeta', 'dollar selmouni', 'jc reyes', 'hijos de la ruina', 'the weeknd', 'rei', 'sosad', 'quevedo', 'ezvit 810', 'israel b', 'cruz cafuné', 'omar courtz', 'baby keem', 'central cee', 'elgrandetoto', 'chucky73', 'foyone', 'antony z', 'polo g', 'bm', 'dei v', 'yovngchimi', 'ankhal', "oblivion's mighty trash", 'hwasa', 'lit killah', 'werenoi', 'young miko', 'villano antillano', 'asan', '21 savage', 'changbin', 'gazo', 'snoop dogg', 'coqe', 'alex zurdo', 'funky', 'a1 x j1', 'feid', 'sponsor dios', 'bobo', 'simba la rue', 'gims', 'chief keef', 'la loquera', 'lil mosey', 'kore', 'tiakola', 'bigxthaplug', 'orelsan', 'cincere', 'kmoneybeats', 'pirmin', 'dj mzenga man', 'chase manhattan', 'mr phormula', 'flo rida', 'bluemason', 'chilli mari', 'les', 'bigmcenroe', 'shaba stele', 'maki', 'the gumshoe strut', 'cream', 'c-lance', 'jonathan cloud', 'agirbest', 'y2', 'lievin', 'oliver tree', 'masked wolf', 'bndr', 'lupe fiasco', 'ali gatie', 'detroit rap news', 'sker mcgurt', 'tems', 'milo j', 'louis amoeba', 'lionware', 'akon', 'tego calderón', 'rubin', 'emilia', 'don toliver', 'tokischa', 'los g4', 'rokero', 'de la rose', 'lil tjay', 'lloyd banks', 'takeoff', 'luciano', 'bia', 'tornillo', 'kodak black', 'fondo blanco', 'peso pluma', 'blessd', 'summer walker', 'doble one flow letal', 'samara', 'pusha t', 'big sean', 'yahfs', 'jayval green', 'guy sebastian', 'kyle', 'loopermanbeats', 'russy', 'zach zoya', 'carvie p', 'jay simmons', 'rob lucci', 'sten joddi', '8 zipp', 'mike d', 'conscious route', 'trina', 'shirt off fe', '$kyhook', '3am', '6ix9ine', 'abhir', 'abra', 'abraham mateo', 'aitana', 'alberdi', 'alejo', 'alex gargolas', 'alex goot', 'alex rose', 'almighty', 'alvaro soler', 'alzate', 'ana mena', 'andy rivera', 'anne-marie', 'antonio banderas', 'antonio josé', 'anuel', 'atomic otro way', 'aventura', 'b-case', 'bejo', 'baby rasta', 'bad gyal', 'bad milk', 'bandaga', 'bassy', 'beatriz luengo', 'bebe', 'belinda', 'beret', 'beéle', 'billie eilish', 'billy chester', 'biwan la pauta', 'bluefire', 'bomba estéreo', 'boricua boys', 'boy wonder cf', 'boza', 'bruno romano', 'brytiago', 'bujan', 'buscabulla', 'busy signal', 'c de cama', 'c.r.o', 'cj', 'cnco', 'cadenza', 'caleb calloway', 'cam steady', 'came beats', 'camilo', 'camin', 'carlitos rossy', 'carly', 'carín león', 'casper magico', 'cauty', 'ceky viciny', 'celebration guns', 'chael produciendo', 'chanell', 'chema rivas', 'chencho corleone', 'chiki el de la vaina', 'chimbala', 'chris brown', 'chris jedi', 'chris lebron', 'chris viz', 'christian daniel', 'christian nodal', 'cojo crazy', 'coqeéin montana', 'corina smith', 'cotorra music grup', 'cris mj', 'cumbiafrica', "d' la crem", 'dellafuente', 'dicc', 'dj conds', 'dj nelson', 'dj pablito', 'dj pana', 'dj premier', 'dj snake', 'dalex', 'dalmata', 'danny ocean', 'darkiel', 'darío gómez', 'david marley', 'daviles de novelda', 'dayme y el high', 'dayvi', 'demi lovato', 'descemer bueno', 'dinamarca', 'doc psych', 'doja cat', 'don miguelo', 'don omar', 'don patricio', 'drago200', 'dua lipa', 'dubbel dutch', 'duncan dhu', 'dylan fuentes', 'dímelo flow', 'el ima', 'elena rose', 'earthadox', 'eddie dee', 'eddie santiago', 'eix', 'el bobe', 'el charrito negro', 'el chaval de la bachata', 'el cherry scom', 'el chuky de lewa', 'el completo rd', 'el conejo', 'el daddy', 'el guincho', 'el kanka', 'el taiger', 'el yman', 'ele a', 'elilluminari', 'elisabeth roma', 'eloy', 'enrique iglesias', 'evaluna montaner', 'fabbio', 'fakeguido', 'famous', 'fat dolsk', 'felino brown', 'fito la r', 'flow la movie', 'flowzeta', 'floyd', 'foking', 'foreign teck', 'fred de palma', 'freshy kanal', 'fresto music', 'funk.shu', 'garabatto', 'gaby music', 'galvan real', 'gangster bunny', 'gigolo y la exce', 'gloosito', 'gote', 'grupo niche', 'guaynaa', 'guitarricadelafuente', 'hugel', 'harry nach', 'haze', 'hydro', 'icon', 'invadable harmony', 'ir sais', 'irrita el indio', 'j-xtreme', 'jc el diamante', 'jada facer', 'jarabe de palo', 'javiielo', 'jay menez', 'jay wheeler', 'jedis', 'jenny "la sexy voz"', 'jerry di', 'jessi uribe', 'jey blessing', 'jhon alex castaño', 'jhonny rivera', 'joaquín sabina', 'joel santos', 'joey montana', 'john doe the first', 'john pollõn', 'jon z', 'jone quest', 'joniel', 'joost', 'jorge drexler', 'jossef', 'jowell', 'jowell & randy', 'joycee', 'juacko', 'juan magán', 'juanka', 'juhn', 'julianno sosa', 'julieta venegas', 'juseph', 'justin quiles', 'karol g', 'kevin roldan', 'kevvo', 'kream', 'kabasaki', 'kafu banton', 'kaio viana', 'karetta el gucci', 'kasher quon', 'kaydy cain', 'keen levy', 'kelly ruíz', 'kenai', 'kendo kaponi', 'kevin kaarl', 'kevin krust', 'kikimoteleba', 'kiko rodriguez', 'killatonez', 'kion studio', 'kiubbah malon', 'kurt hugo schneider', 'l-gante', 'lagos', 'latin mafia', 'lzyxlr', 'la decada prodigiosa', 'la factoria', 'la fortaleza real', 'la húngara', 'la insuperable', 'la nueva escuela', 'la pantera', 'la secta', 'la suprema corte', 'la zowi', 'la mano de oro', 'lalo ebratt', 'leby', 'leebrian', 'leiva', 'lele pons', 'lenny santos', 'lenny tavárez', 'lenuel', 'leo rizzi', 'leoni torres', 'leslie grace', 'lil cake', 'liderj', 'linton', 'lirico en la casa', 'lola indigo', 'los 40', 'los fantastikos', 'los legendarios', 'los lobos', 'los del control', 'los ángeles azules', 'lucho rk', 'luis alberto posada', 'luis figueroa', 'luis fonsi', 'lyanno', 'lérica', 'mc bin laden', 'mc cj', 'mygal', 'maffio', 'maikel delacalle', 'major lazer', 'maka', 'mala rodríguez', 'mama dousha', 'manuel medrano', 'manuel turizo', 'marc anthony', 'marc seguí', 'marciano cantero', 'maria becerra', 'mariah angeliq', 'mat4yo', 'mathew', 'mau y ricky', 'mdmoney', 'melody', 'micro tdh', 'migrantes', 'mike morato', 'moncho chavea', 'mora', 'morat', 'mozart la para', 'mr eazi', 'mr. naisgai', 'musicologo the libro', 'natti natasha', 'noreh', 'nacho', 'naim', 'natalia lafourcade', 'nego do borel', 'neutro shorty', 'nico valdi', 'nio garcia', 'niño de elche', 'nolep', 'nyno vargas', 'obie wanshot', 'oken', 'omar montes', 'omega', 'original elias', 'oscar el ruso', 'ovy on the drums', 'pmp', 'pablo mas', 'pailita', 'paloma mami', 'paul marmota', 'paul sonoria', 'pedro calderon', 'pedro capó', 'pepe y vizio', 'phontana', 'pipe bueno', 'piso 21', 'pj sin suela', 'plan b', 'playa cuberris', 'pol granch', 'princesa alba', 'pure negga', 'pyllo cortes', 'robi', 'rosalía', 'rafa pabön', 'raffa fl', 'ralphie choo', 'randy nota loca', 'rasel', 'raul clyde', 'rauw alejandro', 'reik', 'rema', 'rich music ltd', 'rios', 'rita payés', 'robgz', 'robert hesser', 'roberto ferrante', 'rocco hunt', 'romeo santos', 'rusherking', 'rvssian', 'ryan castro', 'saiko', 'sharif rafael', 'sammy baby', 'scarlett miller', 'scotty dk', 'sean paul', 'sebastian yatra', 'sech', 'selena gomez', 'sen senra', 'shadow blow', 'shaggy', 'shakira', 'shelow shaq', 'sia', 'sick luke', 'skillz beatz', 'skrillex', 'sky rompiendo', 'snova', 'soben', 'soge culebra', 'soto asa', 'spice', 'spiff tv', 'standly', 'stars music chile', 'stefflon don', 'steve lean', 'sticky m.a.', 'super yei', 'tainy', 'tapia el sikario', 'taxi', 'teejayx6', 'tempo', 'the marías', 'the tyets', 'thiago muller', 'tito nieves', 'tony dize', 'totoy el frio', 'travis scott', 'unorthodocks', 'uzii gaang', 'verónica romero', 'victor cardenas', 'viti ruiz', 'waste', 'wesh music', 'will smith', 'willy william', 'wisin', 'wisin & yandel', 'wiso rivera', 'xules', 'yami safdie', 'yan block', 'yandar & yostin', 'yandel', 'yannc', 'yaviah', 'yeison jimenez', 'yiyo sarante', 'yotuel', 'young vene', 'zion', 'zion & lennox', 'ajan', 'integrityoficial', 'l0rna', 'lil eli young bapestah', 'o2 tbb', 'paopao', 'rusowsky', 'shattered', 'çantamarta', 'íñigo quintero', 'ñejo', 'alicia renee', 'ava max', 'black eyed peas', 'bruno mars', 'c grizzy', 'gbaskill-d', 'j.broady', 'kehlani', 'lisa', 'marina', 'megan thee stallion', 'psy', 'rm', 'sza', 'saweetie', 'y2k', 'younglove823', 'bbno$', 'darksunn', 'амир']

In [5]:
len(duplicados)

1062

#paso muy importante para poder evitar duplicados y poner artista como PK

In [6]:
datos_artista_para_sql_api = []
# Usamos un set para nombres normalizados
artistas_vistos = set()

for artista in lista_unificada:
    nombre_original = artista.get("artista")
    
    if nombre_original is None:
        continue

    # --- NORMALIZACIÓN RADICAL ---
    # Quitamos espacios, saltos de línea y pasamos a minúsculas
    nombre_limpio = str(nombre_original).strip().lower()
    
    # Si ya vimos este nombre (aunque tuviera espacios o mayúsculas distintas), lo saltamos
    if nombre_limpio in artistas_vistos:
        continue
    
    # Marcamos como visto
    artistas_vistos.add(nombre_limpio)
    
    # --- PROCESAMIENTO ---
    fila = artista.copy()
    
    # Limpiamos también el nombre que irá a SQL para que no haya espacios
    fila["artista"] = nombre_original.strip()
    
    if isinstance(fila.get("similares"), list):
        fila["similares"] = ", ".join(fila["similares"])
    
    if fila.get("similares") is None:
        fila["similares"] = ""
        
    datos_artista_para_sql_api.append(fila)

print(f"Total original: {len(lista_unificada)}")
print(f"Total tras limpieza radical: {len(datos_artista_para_sql_api)}")

Total original: 6057
Total tras limpieza radical: 3268

In [6]:
len(artistas_vistos)

3268

In [ ]:
# Ahora guardamos todo limpio
with open("Files/json_general_limpio.json", "w", encoding="utf-8") as f:
    json.dump(lista_unificada, f, indent=4, ensure_ascii=False)

print("¡Fusionado y normalizado! Ahora solo tienes una clave 'biografia'.")

In [4]:
df_lista_unificada = pd.DataFrame(lista_unificada)

In [5]:
df_lista_unificada

,artista,audiencia,reproducciones,similares,biografia
0,XXXTENTACION,2774772,335541691,Kid Trunks,"Jahseh Dwayne Onfroy (January 23, 1998 – June ..."
1,The Alchemist,1347530,47088057,Roc Marciano,"Alan Daniel Maman (born October 25, 1977), bet..."
2,Action Bronson,807075,25853544,Action Bronson & The Alchemist,"Ariyan Arslani (born December 2, 1983), better..."
3,Natos y Waor,52124,2763301,FERNANDOCOSTA,Dúo de rap madrileño. Cuentan con 8 trabajos a...
4,Arcángel,433430,14000648,De La Ghetto,"Austin Santos, conocido como Arcangel, nació e..."
...,...,...,...,...,...
6052,Совче,106,341,"[SH Kera, Весъ, Plastic Robots, TRUEten, Брату...",
6053,Стриж,8461,167517,"[Дымовая Завеса, Птаха, 5 Плюх, TAHDEM Foundat...",
6054,ТРИДЦАТЬ ДЕВЯТЫЙ,1439,15141,"[JEEMBO & TVETH, SUPERIOR.CAT.PROTEUS, Pkhat, ...",
6055,ЦИНК УРОДОВ,10025,183850,"[тяжёлая атлетика, H8.HOOD, Metox, Алкоголь По...",
6056,Эскимос Crew,2212,33582,"[Бразилец, Твёрдый Мики, тяжёлая атлетика, ОСО...",

In [ ]:

with open("Files/json_general_limpio.json.json", "w", encoding='utf-8') as f: 
    json.dump(lista_unificada, f, indent=4, ensure_ascii=False)

In [ ]:
#pip install SQLAlchemy

In [7]:
import mysql.connector
from mysql.connector import errorcode
import pandas as pd
import json
from sqlalchemy import create_engine

In [ ]:
usuario = "root"
password = "UsuarioAdalab"
host = "127.0.0.1"
base_de_datos = "pandemusic" # Asegúrate de haber creado el Schema en Workbench

In [9]:
#creamos el engine a ver que tal
engine = create_engine(f"mysql+mysqlconnector://{usuario}:{password}@{host}/{base_de_datos}")
try:
    df_lista_unificada.to_sql('tabla_artistas', con=engine, if_exists="replace", index=False)
    print("✅ ¡Conexión exitosa! Los artistas se han guardado en la tabla 'artistas'.")
except Exception as e:
    print(f"❌ Ups, algo falló: {e}")

❌ Ups, algo falló: Execution failed on sql 'INSERT INTO tabla_artistas (artista, audiencia, reproducciones, similares, biografia) VALUES (:artista, :audiencia, :reproducciones, :similares, :biografia)': (mysql.connector.errors.InterfaceError) Failed executing the operation; Python type list cannot be converted
[SQL: INSERT INTO tabla_artistas (artista, audiencia, reproducciones, similares, biografia) VALUES (%(artista)s, %(audiencia)s, %(reproducciones)s, %(similares)s, %(biografia)s)]
[parameters: [{'artista': 'XXXTENTACION', 'audiencia': '2774772', 'reproducciones': '335541691', 'similares': 'Kid Trunks', 'biografia': 'Jahseh Dwayne Onfroy (January 23, 1998 – June 18, 2018), better known by his stage name XXXTentacion, was an American rapper from Lauderhill, Florida ... (273 characters truncated) ... nd unmastered. His vocal style ranged from singing, rapping, and screaming. <a href="https://www.last.fm/music/XXXTENTACION">Read more on Last.fm</a>'}, {'artista': 'The Alchemist', 'audiencia': '1347530', 'reproducciones': '47088057', 'similares': 'Roc Marciano', 'biografia': 'Alan Daniel Maman (born October 25, 1977), better known as The Alchemist, is a hip-hop producer and MC. The Alchemist has been an active producer sin ... (303 characters truncated) ... unds of hip-hop, and he began writing his own lyrics as a creative outlet. <a href="https://www.last.fm/music/The+Alchemist">Read more on Last.fm</a>'}, {'artista': 'Action Bronson', 'audiencia': '807075', 'reproducciones': '25853544', 'similares': 'Action Bronson & The Alchemist', 'biografia': 'Ariyan Arslani (born December 2, 1983), better known by the stage name Action Bronson, is an American rapper, writer, chef, and television presenter. ... (325 characters truncated) ...  and formerly Big Body Bes are regulars on both of his television series. <a href="https://www.last.fm/music/Action+Bronson">Read more on Last.fm</a>'}, {'artista': 'Natos y Waor', 'audiencia': '52124', 'reproducciones': '2763301', 'similares': 'FERNANDOCOSTA', 'biografia': 'Dúo de rap madrileño. Cuentan con 8 trabajos a sus espaldas: ¨POR LA JETA¨ (2011), "CATARSIS" (2012), "HIJOS DE LA RUINA" (2012, ft Recycled J), "CAJ ... (268 characters truncated) ... paña el día de su lanzamiento en la historia de las plataformas digitales). <a href="https://www.last.fm/music/Natos+y+Waor">Read more on Last.fm</a>'}, {'artista': 'Arcángel', 'audiencia': '433430', 'reproducciones': '14000648', 'similares': 'De La Ghetto', 'biografia': 'Austin Santos, conocido como Arcangel, nació en Nueva York el 23 de diciembre de 1985. Honrando su ascendencia puertorriqueño-dominicana, se trasladó ... (252 characters truncated) ... “Flow La Discoteka 2” y se hizo popular en las radios urbanas. <a href="https://www.last.fm/music/+noredirect/Arc%C3%A1ngel">Read more on Last.fm</a>'}, {'artista': 'Bad Bunny', 'audiencia': '2466426', 'reproducciones': '380858783', 'similares': 'Rauw Alejandro', 'biografia': 'Benito Antonio Martínez Ocasio (born March 10, 1994), known professionally as Bad Bunny, is a Puerto Rican rapper and singer. He is recognized as a l ... (317 characters truncated) ... bum "Un Verano Sin Ti" holds the record as the most-streamed album on Spotify. <a href="https://www.last.fm/music/Bad+Bunny">Read more on Last.fm</a>'}, {'artista': 'LosNiñosDelCaminito', 'audiencia': '3719', 'reproducciones': '151203', 'similares': 'aka Safir', 'biografia': ' <a href="https://www.last.fm/music/LosNi%C3%B1osDelCaminito">Read more on Last.fm</a>'}, {'artista': 'Khea', 'audiencia': '230668', 'reproducciones': '10478724', 'similares': 'Duki', 'biografia': 'Ivo Alfredo Thomas Serue, known musically as Khea, is an Argentinian Latin trap singer born in Mar de Plata, Buenos Aires, Argentina. He is a member of the Argentinian trap scene along with artist such as :   Cazzu and  Duki.  <a href="https://www.last.fm/music/Khea">Read more on Last.fm</a>'}  ... displaying 10 of 6057 total bound parameter sets ...  {'artista': 'ЦИНК УРОДОВ', 'audiencia': '10025', 'reproducciones': '183850', 'similares': ['тяжёлая атлетика', 'H8.HOOD', 'Metox', 'Алкоголь После Спорта', 'Полумягкие'], 'biografia': ''}, {'artista': 'Эскимос Crew', 'audiencia': '2212', 'reproducciones': '33582', 'similares': ['Бразилец', 'Твёрдый Мики', 'тяжёлая атлетика', 'ОСОБОВ', 'Brick Bazuka'], 'biografia': ''}]]
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [13]:
datos_para_sql_api = []

for artista in lista_unificada:
    # Creamos una copia para no romper el original
    fila = artista.copy()
    
    # --- EL TRUCO ESTÁ AQUÍ ---
    # Si 'similares' es una lista, la convertimos a un string separado por comas
    if isinstance(fila.get("similares"), list):
        fila["similares"] = ", ".join(fila["similares"])
    
    # Si es None o no existe, le ponemos un texto vacío para que SQL no sufra
    if fila.get("similares") is None:
        fila["similares"] = ""
        
    datos_para_sql_api.append(fila)

# Ahora ya puedes lanzar tu SQL con 'datos_para_sql'
# engine.execute(sql, datos_para_sql) o el método que estés usando

In [14]:
df_datos_para_sql_api = pd.DataFrame(datos_para_sql_api)

In [15]:
df_datos_para_sql_api

,artista,audiencia,reproducciones,similares,biografia
0,XXXTENTACION,2774772,335541691,Kid Trunks,"Jahseh Dwayne Onfroy (January 23, 1998 – June ..."
1,The Alchemist,1347530,47088057,Roc Marciano,"Alan Daniel Maman (born October 25, 1977), bet..."
2,Action Bronson,807075,25853544,Action Bronson & The Alchemist,"Ariyan Arslani (born December 2, 1983), better..."
3,Natos y Waor,52124,2763301,FERNANDOCOSTA,Dúo de rap madrileño. Cuentan con 8 trabajos a...
4,Arcángel,433430,14000648,De La Ghetto,"Austin Santos, conocido como Arcangel, nació e..."
...,...,...,...,...,...
6052,Совче,106,341,"SH Kera, Весъ, Plastic Robots, TRUEten, Братубрат",
6053,Стриж,8461,167517,"Дымовая Завеса, Птаха, 5 Плюх, TAHDEM Foundati...",
6054,ТРИДЦАТЬ ДЕВЯТЫЙ,1439,15141,"JEEMBO & TVETH, SUPERIOR.CAT.PROTEUS, Pkhat, Ж...",
6055,ЦИНК УРОДОВ,10025,183850,"тяжёлая атлетика, H8.HOOD, Metox, Алкоголь Пос...",
6056,Эскимос Crew,2212,33582,"Бразилец, Твёрдый Мики, тяжёлая атлетика, ОСОБ...",

In [16]:
#creamos el engine a ver que tal
engine = create_engine(f"mysql+mysqlconnector://{usuario}:{password}@{host}/{base_de_datos}")
try:
    df_datos_para_sql_api.to_sql('tabla_artistas', con=engine, if_exists="replace", index=False)
    print("✅ ¡Conexión exitosa! Los artistas se han guardado en la tabla 'artistas'.")
except Exception as e:
    print(f"❌ Ups, algo falló: {e}")

✅ ¡Conexión exitosa! Los artistas se han guardado en la tabla 'artistas'.