In [46]:
# Cuenta API creada --> Aquí están los detalles de su nueva cuenta API:

# - Nombre de la aplicación: adalab_ama
# - Clave API: e313d3e1e9201b89cf4199ad1591d3d7
# - Secreto compartido: 4ec48b1a423188aee9fa7807557a25a6
# - Registrado en: adalab_ama

In [1]:
import os # Importamos 'os' para saber la ruta en donde Python está mirando ahora mismo
import requests # Importamos 'requests' para las peticiones a la web
import pandas as pd # Importamos 'pandas' para visuaizar los datos en tablas
import json # Importamos 'json' para leer ese fromato de lectuta de archivos
import time # Importamos 'time' para realizar pruebas

In [2]:
donde_estoy = os.getcwd() # Nos dice la ruta exacta donde Python está mirando ahora mismo
print(f"Ahora mismo Python está trabajando en: {donde_estoy}")

Ahora mismo Python está trabajando en: /Users/ama/Documents/ESTUDIOS/ADALAB/Módulo 2/Proyecto

In [4]:
with open("json_canciones_hip_hop.json", "r", encoding = "utf-8") as f: # Cargar el archivo JSON
    lista_hip_hop = json.load(f)
print("JSON cargado correctamente")

JSON cargado correctamente

In [5]:
lista_hip_hop # Para ver la estructura general

[{'id': '2ZRo7axmMPeSVUvDbGkJah',
  'artist_name': 'XXXTENTACION',
  'track_name': 'Hope',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7osqbFRT43itJzwduP3sST',
  'artist_name': 'The Alchemist',
  'track_name': 'The Hopeless Romantic (feat. Action Bronson)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7osqbFRT43itJzwduP3sST',
  'artist_name': 'Action Bronson',
  'track_name': 'The Hopeless Romantic (feat. Action Bronson)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0wa6vnWunlgJ23vMCVDM3p',
  'artist_name': 'Natos y Waor',
  'track_name': 'Bicho raro',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1penZqPCE4BosvlbEBcdvp',
  'artist_name': 'Arcángel',
  'track_name': 'Original',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1penZqPCE4BosvlbEBcdvp',
  'artist_name': 'Bad Bunny',
  'track_name': 'Original',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1jsq7wSRqp2jw62kSne7v9',
  'artist_name': 'LosNiñosDelCaminito',
  'track_name': 'Ítaka',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2ECIwi1a7mfokdDkkJ08Ne',
  'artist_name': 'KHEA',
  'track_name': 'Loca - Remix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2ECIwi1a7mfokdDkkJ08Ne',
  'artist_name': 'Bad Bunny',
  'track_name': 'Loca - Remix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2ECIwi1a7mfokdDkkJ08Ne',
  'artist_name': 'Duki',
  'track_name': 'Loca - Remix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2ECIwi1a7mfokdDkkJ08Ne',
  'artist_name': 'Cazzu',
  'track_name': 'Loca - Remix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2xLMifQCjDGFmkHkpNLD9h',
  'artist_name': 'Travis Scott',
  'track_name': 'SICKO MODE',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3E4ZzO4ySupnYypDPXcc3D',
  'artist_name': 'Duki',
  'track_name': 'Rockstar',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dNwJbsT0sg1le5kVugGJb',
  'artist_name': 'Becky G',
  'track_name': 'Bubalu',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dNwJbsT0sg1le5kVugGJb',
  'artist_name': 'Prince Royce',
  'track_name': 'Bubalu',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dNwJbsT0sg1le5kVugGJb',
  'artist_name': 'DJ Luian',
  'track_name': 'Bubalu',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dNwJbsT0sg1le5kVugGJb',
  'artist_name': 'Mambo Kingz',
  'track_name': 'Bubalu',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dNwJbsT0sg1le5kVugGJb',
  'artist_name': 'Anuel AA',
  'track_name': 'Bubalu',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4U0Cx2oGeiUQQCmCByQDxE',
  'artist_name': 'C. Tangana',
  'track_name': 'Llorando en la Limo (feat. Alizzz)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4U0Cx2oGeiUQQCmCByQDxE',
  'artist_name': 'Alizzz',
  'track_name': 'Llorando en la Limo (feat. Alizzz)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3s7MCdXyWmwjdcWh7GWXas',
  'artist_name': 'Kanye West',
  'track_name': 'Violent Crimes',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0CZUctybGtQ8kX8bGXDn8w',
  'artist_name': 'Kidd Keo',
  'track_name': 'Dracukeo',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7AK2UgOQLWpfHZiUlS3u2y',
  'artist_name': 'Delaossa',
  'track_name': 'Sola',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7AK2UgOQLWpfHZiUlS3u2y',
  'artist_name': 'Carrion GodBle$$',
  'track_name': 'Sola',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7AK2UgOQLWpfHZiUlS3u2y',
  'artist_name': 'Perea',
  'track_name': 'Sola',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7AK2UgOQLWpfHZiUlS3u2y',
  'artist_name': 'J.Moods',
  'track_name': 'Sola',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1EljzqiV1RDtXj1QUbx3db',
  'artist_name': 'Trueno',
  'track_name': 'Rain',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1btXIMqhheMHFTSYRfYd7j',
  'artist_name': 'Blake',
  'track_name': 'Lengua de Serpiente',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '270k38FpoKhnvZLv50NlTr',
  'artist_name': 'j-hope',
  'track_name': '항상 (HANGSANG)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '270k38FpoKhnvZLv50NlTr',
  'artist_name': 'Supreme Boi',
  'track_name': '항상 (HANGSANG)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1SpBVFwvj7WsfxOxcQz6Z8',
  'artist_name': 'Soolking',
  'track_name': 'Milano',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3o0dhbe6LWvyUXjr2IyQiv',
  'artist_name': 'Natos y Waor',
  'track_name': 'Piratas',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4m7Mtcd5EuzKdu2sdqcQ8g',
  'artist_name': 'Matasvandals',
  'track_name': 'Tres Calos',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4m7Mtcd5EuzKdu2sdqcQ8g',
  'artist_name': 'Da Silva',
  'track_name': 'Tres Calos',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5u3FdkhdizFMMagxjbS53C',
  'artist_name': 'Rels B',
  'track_name': 'Love It',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5jGUJXnELDaDTgiRjD9lsg',
  'artist_name': 'Bad Bunny',
  'track_name': '200 Mph',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5jGUJXnELDaDTgiRjD9lsg',
  'artist_name': 'Diplo',
  'track_name': '200 Mph',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6kdyQUoFRC8DdfCxnFYd03',
  'artist_name': 'FERNANDOCOSTA',
  'track_name': 'Narcolepsia (feat. Chicho Beats)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6kdyQUoFRC8DdfCxnFYd03',
  'artist_name': 'Chicho Beats',
  'track_name': 'Narcolepsia (feat. Chicho Beats)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '17NW5LLmN6PXrUdknZ6iT1',
  'artist_name': 'Kidd Keo',
  'track_name': 'Miss U',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6JwxU6BVnUsXiGOK9IuC3F',
  'artist_name': 'Blake',
  'track_name': 'Rema',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0wBzg9W5KJiK3IMjVOaoOf',
  'artist_name': 'Natos y Waor',
  'track_name': 'Generación perdida',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2jk6oBuLiCZJTDWhlJEzIw',
  'artist_name': 'j-hope',
  'track_name': 'Airplane',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2hLyWkdMjWsudBEvJ5bokV',
  'artist_name': 'Denom',
  'track_name': 'Solo pienso en ti',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2hLyWkdMjWsudBEvJ5bokV',
  'artist_name': 'Vengui',
  'track_name': 'Solo pienso en ti',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '47Y6vv6KLQIia9mMMxulO3',
  'artist_name': 'Nadal015',
  'track_name': 'Streetshark',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7LQDeayxCl0fFqhIVFc67U',
  'artist_name': 'Kaze',
  'track_name': 'Modo Turbio',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7LQDeayxCl0fFqhIVFc67U',
  'artist_name': 'Dj Figu',
  'track_name': 'Modo Turbio',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1DsOJEDpZj9uBTqYD2Dzhb',
  'artist_name': 'El Perla',
  'track_name': 'Que Tiren',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2G7V7zsVDxg1yRsu7Ew9RJ',
  'artist_name': 'Drake',
  'track_name': 'In My Feelings',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2gzrOxaYdGnYcJ5R4MErFV',
  'artist_name': 'Fazzini',
  'track_name': 'Crazy',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2gzrOxaYdGnYcJ5R4MErFV',
  'artist_name': 'Franky Style',
  'track_name': 'Crazy',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0TlLq3lA83rQOYtrqBqSct',
  'artist_name': 'Drake',
  'track_name': 'Nonstop',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '55PyQALchJn43CGeN6XHAN',
  'artist_name': 'Moha La Squale',
  'track_name': 'Luna',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5Dp8iBqAjkmh3kRX9bNPM7',
  'artist_name': 'Kidd Keo',
  'track_name': 'Igot',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5ytZtH3YKQEqKax966QseE',
  'artist_name': 'Miranda',
  'track_name': 'Diferente',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5FyTyoz2x0cgeu7IPPVTK6',
  'artist_name': 'WOS',
  'track_name': 'ANDRÓMEDA',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1ctmEy4ajH5dIGDWIBMMYH',
  'artist_name': 'Matasvandals',
  'track_name': 'Hardalla',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1ctmEy4ajH5dIGDWIBMMYH',
  'artist_name': 'Carlytos Vela',
  'track_name': 'Hardalla',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1ctmEy4ajH5dIGDWIBMMYH',
  'artist_name': 'JAVI BAMBINI CATTIVI',
  'track_name': 'Hardalla',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5Givva6Je0aVBdlQsoiVbJ',
  'artist_name': 'FERNANDOCOSTA',
  'track_name': 'Dinamo (feat. Chicho Beats)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5Givva6Je0aVBdlQsoiVbJ',
  'artist_name': 'Chicho Beats',
  'track_name': 'Dinamo (feat. Chicho Beats)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3eSCPt6StovDAIps2XhZ2Z',
  'artist_name': 'j-hope',
  'track_name': 'Base Line',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '45TB9eVUb6KjwOwa8UNL1e',
  'artist_name': 'Rels B',
  'track_name': 'Euromillón',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1g2pomnU3K9f0f5wW4k0N0',
  'artist_name': 'Kidd Keo',
  'track_name': 'Touchdown',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1g2pomnU3K9f0f5wW4k0N0',
  'artist_name': 'Alemán',
  'track_name': 'Touchdown',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7lAK3oHbfEnvUQWosrMMpR',
  'artist_name': 'Travis Scott',
  'track_name': 'YOSEMITE',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '27a1mYSG5tYg7dmEjWBcmL',
  'artist_name': 'Travis Scott',
  'track_name': "CAN'T SAY",
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '11kDth1aKUEUMq9r1pqyds',
  'artist_name': 'Travis Scott',
  'track_name': '5% TINT',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7wBJfHzpfI3032CSD7CE2m',
  'artist_name': 'Travis Scott',
  'track_name': 'STARGAZING',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5ucAspGDdhcaGgTn5gUVdl',
  'artist_name': 'Blake',
  'track_name': 'En el Clavo',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dGns2SXShGkQhJmaNPnT8',
  'artist_name': 'Fazzini',
  'track_name': 'Marihuana',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7dGns2SXShGkQhJmaNPnT8',
  'artist_name': 'Franky Style',
  'track_name': 'Marihuana',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '08wJw4VdkKImX4t1vL6MsO',
  'artist_name': 'Revol',
  'track_name': 'Dime',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '08wJw4VdkKImX4t1vL6MsO',
  'artist_name': 'J Balvin',
  'track_name': 'Dime',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '08wJw4VdkKImX4t1vL6MsO',
  'artist_name': 'Bad Bunny',
  'track_name': 'Dime',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '08wJw4VdkKImX4t1vL6MsO',
  'artist_name': 'Arcángel',
  'track_name': 'Dime',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '08wJw4VdkKImX4t1vL6MsO',
  'artist_name': 'De La Ghetto',
  'track_name': 'Dime',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '11LvBvbQyFNE8AUYXDmr53',
  'artist_name': 'Dirty Porko',
  'track_name': 'Hazme Five',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '03PZ9C7f90TLbDk3dYjBd2',
  'artist_name': 'Duki',
  'track_name': 'Sin Culpa (feat.DrefQuila)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '03PZ9C7f90TLbDk3dYjBd2',
  'artist_name': 'DrefQuila',
  'track_name': 'Sin Culpa (feat.DrefQuila)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2LskIZrCeLxRvCiGP8gxlh',
  'artist_name': 'XXXTENTACION',
  'track_name': 'Arms Around You (feat. Maluma & Swae Lee)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2LskIZrCeLxRvCiGP8gxlh',
  'artist_name': 'Lil Pump',
  'track_name': 'Arms Around You (feat. Maluma & Swae Lee)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2LskIZrCeLxRvCiGP8gxlh',
  'artist_name': 'Swae Lee',
  'track_name': 'Arms Around You (feat. Maluma & Swae Lee)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2LskIZrCeLxRvCiGP8gxlh',
  'artist_name': 'Maluma',
  'track_name': 'Arms Around You (feat. Maluma & Swae Lee)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0c0YHn3DIQLl1opsQDd9kO',
  'artist_name': 'Diplo',
  'track_name': 'Wish (feat. Trippie Redd) - Trippie Mix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0c0YHn3DIQLl1opsQDd9kO',
  'artist_name': 'Trippie Redd',
  'track_name': 'Wish (feat. Trippie Redd) - Trippie Mix',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '69rcDQoTgcU1qI396vTcxC',
  'artist_name': 'Eladio Carrion',
  'track_name': 'Mula',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '69rcDQoTgcU1qI396vTcxC',
  'artist_name': 'Big Soto',
  'track_name': 'Mula',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6HSnLmg25CFVozSlimAzF4',
  'artist_name': 'Rels B',
  'track_name': 'Es Mejor',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7FYAPL3LQsIjlhxJl5XIcz',
  'artist_name': 'Natos y Waor',
  'track_name': 'Underground Kings',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5ri9yKB3I7bWzzJclz72Vg',
  'artist_name': 'Kidd Keo',
  'track_name': 'One',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2ksvWFIlW7QgXuvk2MA1FT',
  'artist_name': 'YSY A',
  'track_name': 'Pastel Con Nutella',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6aTqtTc3XV1PVw3DTcfF5o',
  'artist_name': 'Hard GZ',
  'track_name': 'Shameless',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3LmzaazAk8DNwkwg6KqZId',
  'artist_name': 'FERNANDOCOSTA',
  'track_name': 'Danger',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3LmzaazAk8DNwkwg6KqZId',
  'artist_name': 'Denom',
  'track_name': 'Danger',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3LmzaazAk8DNwkwg6KqZId',
  'artist_name': 'Blasfem',
  'track_name': 'Danger',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3kpYJjvM8Ja6btr5hEJLWc',
  'artist_name': 'Eminem',
  'track_name': 'Venom - Music From The Motion Picture',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7yzJgwUE1yUW4ilkeH8myG',
  'artist_name': 'Subze',
  'track_name': 'Guerrero',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7yzJgwUE1yUW4ilkeH8myG',
  'artist_name': 'Edoby',
  'track_name': 'Guerrero',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1L5znesec7eOVNAqnrUn3r',
  'artist_name': 'Natos y Waor',
  'track_name': 'Alfa y omega',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1L5znesec7eOVNAqnrUn3r',
  'artist_name': 'Denom',
  'track_name': 'Alfa y omega',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '39NDBdU5Xkm5pCFGa5kZtI',
  'artist_name': 'Mac Miller',
  'track_name': 'Ladders',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6U4wdeB0dIWNe9qgY5nS37',
  'artist_name': 'Hard GZ',
  'track_name': 'Weah',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6U4wdeB0dIWNe9qgY5nS37',
  'artist_name': 'Lil GZ',
  'track_name': 'Weah',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '40m1dUUK3xgDBS8CVPzWGR',
  'artist_name': 'Calero LDN',
  'track_name': 'Corazón Pagano',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0Ks2NJH2PCxyWAFPlI4p9B',
  'artist_name': 'Trap Capos',
  'track_name': 'Porque Te Mientes (feat. Gadiel & Bryant Myers)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0Ks2NJH2PCxyWAFPlI4p9B',
  'artist_name': 'Noriel',
  'track_name': 'Porque Te Mientes (feat. Gadiel & Bryant Myers)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0Ks2NJH2PCxyWAFPlI4p9B',
  'artist_name': 'Gadiel',
  'track_name': 'Porque Te Mientes (feat. Gadiel & Bryant Myers)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0Ks2NJH2PCxyWAFPlI4p9B',
  'artist_name': 'Bryant Myers',
  'track_name': 'Porque Te Mientes (feat. Gadiel & Bryant Myers)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0bs3znECtSp5I5ZjMpj6Mh',
  'artist_name': 'Walls',
  'track_name': 'Por Partes',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6rE7ytpSheKE4ui9AXnkti',
  'artist_name': 'El Jincho',
  'track_name': 'Ojos Rojos',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0yE6ut9o4LCErTckysVNXU',
  'artist_name': 'SFDK',
  'track_name': 'Me Queo en Mi Casa',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6KBYefIoo7KydImq1uUQlL',
  'artist_name': 'Cardi B',
  'track_name': 'Bodak Yellow',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '60SdxE8apGAxMiRrpbmLY0',
  'artist_name': 'Eminem',
  'track_name': 'Lucky You (feat. Joyner Lucas)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '60SdxE8apGAxMiRrpbmLY0',
  'artist_name': 'Joyner Lucas',
  'track_name': 'Lucky You (feat. Joyner Lucas)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6wWaVoUOzLQJHd3bWAUpdZ',
  'artist_name': 'Lil Baby',
  'track_name': 'Never Recover (Lil Baby & Gunna, Drake)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6wWaVoUOzLQJHd3bWAUpdZ',
  'artist_name': 'Gunna',
  'track_name': 'Never Recover (Lil Baby & Gunna, Drake)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '6wWaVoUOzLQJHd3bWAUpdZ',
  'artist_name': 'Drake',
  'track_name': 'Never Recover (Lil Baby & Gunna, Drake)',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7nimqvRz6Xh2vDz2oGv0Sy',
  'artist_name': 'Underdann',
  'track_name': 'La Salamandra',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7nimqvRz6Xh2vDz2oGv0Sy',
  'artist_name': 'Trueno',
  'track_name': 'La Salamandra',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0Ea9DDc9ypH8XjYNB1uD2n',
  'artist_name': 'Rels B',
  'track_name': 'King Flakk',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1ZVOp3LZg5Xgd1NzYWacma',
  'artist_name': 'El Jincho',
  'track_name': 'Pensando en Ti',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '65G8Kk1Fto5dVx9PAVZiem',
  'artist_name': 'Costa',
  'track_name': 'Halloween',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '1lfwT0UCbiRUT1E6ZegkeL',
  'artist_name': 'Costa',
  'track_name': 'Lunático',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '32IOZbDl7IB6BppbnEBOVd',
  'artist_name': 'Natos y Waor',
  'track_name': 'Autodestrucción',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '7BtAkqRFQjvOYOq5k5mlCb',
  'artist_name': 'Ninho',
  'track_name': 'Fendi',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5UB4pyeyR7d4LLJfVN4Kis',
  'artist_name': 'Residente',
  'track_name': 'Rap Bruto',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5UB4pyeyR7d4LLJfVN4Kis',
  'artist_name': 'Nach',
  'track_name': 'Rap Bruto',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '21WvAGxPUNJARcZoSqswd7',
  'artist_name': 'Nicky Jam',
  'track_name': 'Satisfacción',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '21WvAGxPUNJARcZoSqswd7',
  'artist_name': 'Bad Bunny',
  'track_name': 'Satisfacción',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '21WvAGxPUNJARcZoSqswd7',
  'artist_name': 'Arcángel',
  'track_name': 'Satisfacción',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3Ol2xnObFdKV9pmRD2t9x8',
  'artist_name': 'A Boogie Wit da Hoodie',
  'track_name': 'Look Back at It',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '32lItqlMi4LBhb4k0BaSaC',
  'artist_name': 'Post Malone',
  'track_name': 'Candy Paint',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '3U21A07gAloCc4P7J8rxcn',
  'artist_name': 'Kanye West',
  'track_name': 'All Mine',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '2as7AQfl3uoUbNazMXDKFC',
  'artist_name': 'YSY A',
  'track_name': 'Hidro',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '26JLezveasjmj1YypgUGsf',
  'artist_name': 'Nanpa Básico',
  'track_name': 'Flaca',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4NE2cVf0KZTQhZaueJ9pEa',
  'artist_name': 'ToteKing',
  'track_name': 'Bartleby & Co.',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '4dQX1TnaicU7KD6kgotVBw',
  'artist_name': 'Eladio Carrion',
  'track_name': 'Miles',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'Delaossa',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'Raggio',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'Chicolisto',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'Saske',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'J.Moods',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5nyZ6PuO78VKtz1L5cHeCJ',
  'artist_name': 'Dheformer Galinier',
  'track_name': 'Turín 97',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '5Psnhdkyanjpgc2P8A5TSM',
  'artist_name': 'Drake',
  'track_name': 'Emotionless',
  'genre': 'hip-hop',
  'year': 2018},
 {'id': '0LIrw4bN6n32HmxptRya7I',
  'artist_name': 'Bizarrap',

In [6]:
# FUNCIÓN 1: Extraer los Artistas del JSON de Hip-Hop

def artistas_hip_hop (lista_hip_hop):
    lista_artistas = []

    print(f"Iniciando comparación de datos para {len(lista_hip_hop)} artistas")

    for elemento in lista_hip_hop:
        informacion = {"artista" : elemento["artist_name"]} # Para extraer una información específica: Nombre del artista, 
        lista_artistas.append(informacion)
    
    print("----")
    print("Se ha filtrado con éxito")
    
    return lista_artistas

In [7]:
lista_artistas_hip_hop = artistas_hip_hop(lista_hip_hop)

Iniciando comparación de datos para 3642 artistas
----
Se ha filtrado con éxito

In [8]:
lista_artistas_hip_hop

[{'artista': 'XXXTENTACION'},
 {'artista': 'The Alchemist'},
 {'artista': 'Action Bronson'},
 {'artista': 'Natos y Waor'},
 {'artista': 'Arcángel'},
 {'artista': 'Bad Bunny'},
 {'artista': 'LosNiñosDelCaminito'},
 {'artista': 'KHEA'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Duki'},
 {'artista': 'Cazzu'},
 {'artista': 'Travis Scott'},
 {'artista': 'Duki'},
 {'artista': 'Becky G'},
 {'artista': 'Prince Royce'},
 {'artista': 'DJ Luian'},
 {'artista': 'Mambo Kingz'},
 {'artista': 'Anuel AA'},
 {'artista': 'C. Tangana'},
 {'artista': 'Alizzz'},
 {'artista': 'Kanye West'},
 {'artista': 'Kidd Keo'},
 {'artista': 'Delaossa'},
 {'artista': 'Carrion GodBle$$'},
 {'artista': 'Perea'},
 {'artista': 'J.Moods'},
 {'artista': 'Trueno'},
 {'artista': 'Blake'},
 {'artista': 'j-hope'},
 {'artista': 'Supreme Boi'},
 {'artista': 'Soolking'},
 {'artista': 'Natos y Waor'},
 {'artista': 'Matasvandals'},
 {'artista': 'Da Silva'},
 {'artista': 'Rels B'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Diplo'},
 {'artista': 'FERNANDOCOSTA'},
 {'artista': 'Chicho Beats'},
 {'artista': 'Kidd Keo'},
 {'artista': 'Blake'},
 {'artista': 'Natos y Waor'},
 {'artista': 'j-hope'},
 {'artista': 'Denom'},
 {'artista': 'Vengui'},
 {'artista': 'Nadal015'},
 {'artista': 'Kaze'},
 {'artista': 'Dj Figu'},
 {'artista': 'El Perla'},
 {'artista': 'Drake'},
 {'artista': 'Fazzini'},
 {'artista': 'Franky Style'},
 {'artista': 'Drake'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Kidd Keo'},
 {'artista': 'Miranda'},
 {'artista': 'WOS'},
 {'artista': 'Matasvandals'},
 {'artista': 'Carlytos Vela'},
 {'artista': 'JAVI BAMBINI CATTIVI'},
 {'artista': 'FERNANDOCOSTA'},
 {'artista': 'Chicho Beats'},
 {'artista': 'j-hope'},
 {'artista': 'Rels B'},
 {'artista': 'Kidd Keo'},
 {'artista': 'Alemán'},
 {'artista': 'Travis Scott'},
 {'artista': 'Travis Scott'},
 {'artista': 'Travis Scott'},
 {'artista': 'Travis Scott'},
 {'artista': 'Blake'},
 {'artista': 'Fazzini'},
 {'artista': 'Franky Style'},
 {'artista': 'Revol'},
 {'artista': 'J Balvin'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Arcángel'},
 {'artista': 'De La Ghetto'},
 {'artista': 'Dirty Porko'},
 {'artista': 'Duki'},
 {'artista': 'DrefQuila'},
 {'artista': 'XXXTENTACION'},
 {'artista': 'Lil Pump'},
 {'artista': 'Swae Lee'},
 {'artista': 'Maluma'},
 {'artista': 'Diplo'},
 {'artista': 'Trippie Redd'},
 {'artista': 'Eladio Carrion'},
 {'artista': 'Big Soto'},
 {'artista': 'Rels B'},
 {'artista': 'Natos y Waor'},
 {'artista': 'Kidd Keo'},
 {'artista': 'YSY A'},
 {'artista': 'Hard GZ'},
 {'artista': 'FERNANDOCOSTA'},
 {'artista': 'Denom'},
 {'artista': 'Blasfem'},
 {'artista': 'Eminem'},
 {'artista': 'Subze'},
 {'artista': 'Edoby'},
 {'artista': 'Natos y Waor'},
 {'artista': 'Denom'},
 {'artista': 'Mac Miller'},
 {'artista': 'Hard GZ'},
 {'artista': 'Lil GZ'},
 {'artista': 'Calero LDN'},
 {'artista': 'Trap Capos'},
 {'artista': 'Noriel'},
 {'artista': 'Gadiel'},
 {'artista': 'Bryant Myers'},
 {'artista': 'Walls'},
 {'artista': 'El Jincho'},
 {'artista': 'SFDK'},
 {'artista': 'Cardi B'},
 {'artista': 'Eminem'},
 {'artista': 'Joyner Lucas'},
 {'artista': 'Lil Baby'},
 {'artista': 'Gunna'},
 {'artista': 'Drake'},
 {'artista': 'Underdann'},
 {'artista': 'Trueno'},
 {'artista': 'Rels B'},
 {'artista': 'El Jincho'},
 {'artista': 'Costa'},
 {'artista': 'Costa'},
 {'artista': 'Natos y Waor'},
 {'artista': 'Ninho'},
 {'artista': 'Residente'},
 {'artista': 'Nach'},
 {'artista': 'Nicky Jam'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Arcángel'},
 {'artista': 'A Boogie Wit da Hoodie'},
 {'artista': 'Post Malone'},
 {'artista': 'Kanye West'},
 {'artista': 'YSY A'},
 {'artista': 'Nanpa Básico'},
 {'artista': 'ToteKing'},
 {'artista': 'Eladio Carrion'},
 {'artista': 'Delaossa'},
 {'artista': 'Raggio'},
 {'artista': 'Chicolisto'},
 {'artista': 'Saske'},
 {'artista': 'J.Moods'},
 {'artista': 'Dheformer Galinier'},
 {'artista': 'Drake'},
 {'artista': 'Bizarrap'},
 {'artista': 'Bartofso'},
 {'artista': '3robi'},
 {'artista': 'Mula B'},
 {'artista': 'Nanpa Básico'},
 {'artista': 'Benny Benni'},
 {'artista': 'Daddy Yankee'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Pusho'},
 {'artista': 'Farruko'},
 {'artista': 'Noriel'},
 {'artista': 'Miky Woodz'},
 {'artista': 'Soolking'},
 {'artista': 'Maes'},
 {'artista': 'Booba'},
 {'artista': 'Maes'},
 {'artista': 'Alemán'},
 {'artista': 'Charlie Hijos Bastardos'},
 {'artista': 'YSY A'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Akapellah'},
 {'artista': 'Travis Scott'},
 {'artista': 'Alemán'},
 {'artista': 'C. Tangana'},
 {'artista': 'Fntxy'},
 {'artista': 'Drake'},
 {'artista': 'Felo Blonck'},
 {'artista': 'Jamby El Favo'},
 {'artista': 'ECKO'},
 {'artista': 'KHEA'},
 {'artista': 'Seven Kayne'},
 {'artista': 'Iacho'},
 {'artista': 'Omar Varela'},
 {'artista': "Rim'K"},
 {'artista': 'Ninho'},
 {'artista': 'Mula B'},
 {'artista': '3robi'},
 {'artista': 'Metro Boomin'},
 {'artista': 'Offset'},
 {'artista': 'Drake'},
 {'artista': 'Ñengo Flow'},
 {'artista': 'Travis Scott'},
 {'artista': 'Kanye West'},
 {'artista': 'XXXTENTACION'},
 {'artista': 'Joey Bada$$'},
 {'artista': 'C.R.O'},
 {'artista': 'Duki'},
 {'artista': 'C.R.O'},
 {'artista': 'KHEA'},
 {'artista': 'Teo LB'},
 {'artista': 'Nanpa Básico'},
 {'artista': 'Drake'},
 {'artista': 'Moha La Squale'},
 {'artista': 'KIDS SEE GHOSTS'},
 {'artista': 'Louis Prima'},
 {'artista': 'Cosculluela'},
 {'artista': 'Migos'},
 {'artista': 'Post Malone'},
 {'artista': 'Kanye West'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Miky Woodz'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Rels B'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Eladio Carrion'},
 {'artista': 'Cazzu'},
 {'artista': 'KHEA'},
 {'artista': 'ECKO'},
 {'artista': 'Alemán'},
 {'artista': 'Yung Sarria'},
 {'artista': 'Fntxy'},
 {'artista': 'DrefQuila'},
 {'artista': 'Kanye West'},
 {'artista': 'PARTYNEXTDOOR'},
 {'artista': 'Crudo Means Raw'},
 {'artista': 'Aaron May'},
 {'artista': 'Dinos'},
 {'artista': 'NAV'},
 {'artista': 'Travis Scott'},
 {'artista': 'Rejjie Snow'},
 {'artista': 'Aminé'},
 {'artista': 'Dana Williams'},
 {'artista': 'Pablo Chill-E'},
 {'artista': 'Duki'},
 {'artista': 'Redimi2'},
 {'artista': 'Natan El Profeta'},
 {'artista': 'Rubinsky Rbk'},
 {'artista': 'El Philippe'},
 {'artista': 'Eminem'},
 {'artista': 'Playboi Carti'},
 {'artista': 'Young Thug'},
 {'artista': 'Cejaz Negraz'},
 {'artista': 'Gera MX'},
 {'artista': 'Soolking'},
 {'artista': 'Khaled'},
 {'artista': 'Drake'},
 {'artista': 'YSY A'},
 {'artista': 'Marcianos Crew'},
 {'artista': 'Dani Ribba'},
 {'artista': 'YSY A'},
 {'artista': 'Neo Pistea'},
 {'artista': 'Millonario'},
 {'artista': 'Lacrim'},
 {'artista': 'Gera MX'},
 {'artista': 'Dany Calvario'},
 {'artista': 'SAINt JHN'},
 {'artista': 'Drake'},
 {'artista': 'Capo Plaza'},
 {'artista': 'C.R.O'},
 {'artista': 'C.R.O'},
 {'artista': 'Sfera Ebbasta'},
 {'artista': 'Lexicon'},
 {'artista': 'Summer Cem'},
 {'artista': 'Eminem'},
 {'artista': 'Royce Da 5\'9"'},
 {'artista': 'Gera MX'},
 {'artista': 'Post Malone'},
 {'artista': 'G-Eazy'},
 {'artista': 'YG'},
 {'artista': 'The Alchemist'},
 {'artista': 'Westside Gunn'},
 {'artista': 'Conway the Machine'},
 {'artista': 'Fabolous'},
 {'artista': 'Eminem'},
 {'artista': 'C.R.O'},
 {'artista': 'C.R.O'},
 {'artista': 'Ours Samplus'},
 {'artista': 'Baby Smoove'},
 {'artista': 'JayDaYoungan'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Lary Over'},
 {'artista': 'Aerophon'},
 {'artista': 'Juan Pablo Vega'},
 {'artista': 'Sfera Ebbasta'},
 {'artista': 'Quavo'},
 {'artista': 'KIDS SEE GHOSTS'},
 {'artista': 'Awon'},
 {'artista': 'Phoniks'},
 {'artista': 'Tiff the Gift'},
 {'artista': 'Rejjie Snow'},
 {'artista': 'Caroline Smith'},
 {'artista': 'Nanpa Básico'},
 {'artista': 'Lil Wayne'},
 {'artista': 'Kendrick Lamar'},
 {'artista': 'Lil Wayne'},
 {'artista': 'Wet Bed Gang'},
 {'artista': 'Lomepal'},
 {'artista': 'J. Cole'},
 {'artista': 'Jamby El Favo'},
 {'artista': 'Bas'},
 {'artista': 'J. Cole'},
 {'artista': 'Sidhu Moose Wala'},
 {'artista': 'KHEA'},
 {'artista': 'Post Malone'},
 {'artista': "Heuss L'enfoiré"},
 {'artista': 'A$AP Rocky'},
 {'artista': 'Achille Lauro'},
 {'artista': 'Boss Doms'},
 {'artista': 'Gemitaiz'},
 {'artista': 'Quentin40'},
 {'artista': 'Puritano'},
 {'artista': 'Capo Plaza'},
 {'artista': 'Ninho'},
 {'artista': 'Ninho'},
 {'artista': 'Nipsey Hussle'},
 {'artista': 'Stacy Barthe'},
 {'artista': 'La Gra$a'},
 {'artista': 'Granuja'},
 {'artista': 'Crudo Means Raw'},
 {'artista': 'Zof Ziro'},
 {'artista': 'Doble Porción'},
 {'artista': 'Métricas Frías'},
 {'artista': 'Mañas Ru-Fino'},
 {'artista': 'C.R.O'},
 {'artista': 'Ronpe 99'},
 {'artista': 'La Gra$a'},
 {'artista': 'Granuja'},
 {'artista': 'Crudo Means Raw'},
 {'artista': 'Zof Ziro'},
 {'artista': 'Doble Porción'},
 {'artista': 'Métricas Frías'},
 {'artista': 'Mañas Ru-Fino'},
 {'artista': 'Redimi2'},
 {'artista': 'Alexis Velez'},
 {'artista': 'Oveja Cosmica'},
 {'artista': 'Metro Boomin'},
 {'artista': 'Gunna'},
 {'artista': 'Young Thug'},
 {'artista': 'PNL'},
 {'artista': 'Sfera Ebbasta'},
 {'artista': 'DrefGold'},
 {'artista': 'Cartel De Santa'},
 {'artista': 'YSY A'},
 {'artista': 'Drake'},
 {'artista': 'C.R.O'},
 {'artista': 'CA7RIEL & Paco Amoroso'},
 {'artista': 'Kendrick Lamar'},
 {'artista': 'Travis Scott'},
 {'artista': 'novaly'},
 {'artista': 'Niska'},
 {'artista': 'Alemán'},
 {'artista': 'Emy Soul'},
 {'artista': 'Josman'},
 {'artista': 'J Balvin'},
 {'artista': 'G-Eazy'},
 {'artista': 'Sfera Ebbasta'},
 {'artista': 'Anitta'},
 {'artista': 'MC Fioti'},
 {'artista': 'Duki'},
 {'artista': 'Jeon'},
 {'artista': 'El Jose'},
 {'artista': 'Nito NB'},
 {'artista': 'A$AP Rocky'},
 {'artista': 'Noiseferatu'},
 {'artista': 'Rochy RD'},
 {'artista': 'SCH'},
 {'artista': 'Dharius'},
 {'artista': 'Capo Plaza'},
 {'artista': 'Prieto Gang'},
 {'artista': 'Millonario'},
 {'artista': 'Luck Ra'},
 {'artista': 'Seven Kayne'},
 {'artista': 'Rah-C'},
 {'artista': 'Wolty'},
 {'artista': 'Awon'},
 {'artista': 'Phoniks'},
 {'artista': 'Kali Uchis'},
 {'artista': 'Tyler, The Creator'},
 {'artista': 'Bootsy Collins'},
 {'artista': 'Pete Rock'},
 {'artista': 'La Santa Grifa'},
 {'artista': 'A$AP Rocky'},
 {'artista': 'Tyler, The Creator'},
 {'artista': '6LACK'},
 {'artista': 'Jay Rock'},
 {'artista': 'Kendrick Lamar'},
 {'artista': 'Ninho'},
 {'artista': 'Neo Pistea'},
 {'artista': 'KHEA'},
 {'artista': 'Omar Varela'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Aerophon'},
 {'artista': 'Alcolirykoz'},
 {'artista': 'Moha La Squale'},
 {'artista': 'Logic'},
 {'artista': 'Wiz Khalifa'},
 {'artista': 'Maes'},
 {'artista': 'Money Man'},
 {'artista': 'SCH'},
 {'artista': 'El Redcode'},
 {'artista': 'Moha La Squale'},
 {'artista': 'C.R.O'},
 {'artista': 'C.R.O'},
 {'artista': 'T&K'},
 {'artista': 'Al2 El Aldeano'},
 {'artista': 'BL@CKBOX'},
 {'artista': 'Fratelli-B'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'Shad'},
 {'artista': 'Bfd'},
 {'artista': 'Benny Blanco 650'},
 {'artista': 'Maffy'},
 {'artista': 'D-Weez'},
 {'artista': 'M.C. Mack'},
 {'artista': 'M.C. Mack'},
 {'artista': 'K Kutta'},
 {'artista': 'Khaotic'},
 {'artista': 'Alias'},
 {'artista': 'CISKO'},
 {'artista': 'Dj Clen'},
 {'artista': 'Scooby Nero'},
 {'artista': 'Solareye'},
 {'artista': 'Bakersteez'},
 {'artista': 'Quan Duke'},
 {'artista': 'Mickey Ali'},
 {'artista': 'YFilla'},
 {'artista': 'Sleekk Blaze'},
 {'artista': 'Jairzinho'},
 {'artista': 'Eligh'},
 {'artista': 'Kwasi'},
 {'artista': 'HFNR'},
 {'artista': 'C.W. Da YoungBlood'},
 {'artista': 'S Beater'},
 {'artista': 'Myahri'},
 {'artista': 'Sean Gonzalez'},
 {'artista': 'MTM'},
 {'artista': "John'nay Lasha"},
 {'artista': 'CSABA'},
 {'artista': 'Hyu'},
 {'artista': 'Solareye'},
 {'artista': 'Chegs'},
 {'artista': 'Mic O'},
 {'artista': 'Benjahvites'},
 {'artista': 'Zorimawi'},
 {'artista': 'Dintluanga Tochhawng'},
 {'artista': 'Element A.U.'},
 {'artista': "John'nay Lasha"},
 {'artista': 'Conjuro Epiléptico'},
 {'artista': 'The Jacka'},
 {'artista': 'Young Lox'},
 {'artista': 'Nyukyung'},
 {'artista': 'Hancoq'},
 {'artista': 'Checkmate'},
 {'artista': 'Preme Dibiasi'},
 {'artista': 'Baby Brown'},
 {'artista': 'Nyanda'},
 {'artista': 'Playbwoi Tha Great'},
 {'artista': 'ShabZi Madallion'},
 {'artista': 'Badhabitz'},
 {'artista': 'BKO'},
 {'artista': 'iiiCONIC'},
 {'artista': 'Travy P'},
 {'artista': 'I.E.'},
 {'artista': 'Hoodini'},
 {'artista': 'Lil Los'},
 {'artista': 'Luke Vallen'},
 {'artista': 'Baby Brown'},
 {'artista': 'Ampichino'},
 {'artista': 'Chey Dolla'},
 {'artista': 'Malvo'},
 {'artista': 'P3'},
 {'artista': 'Q052'},
 {'artista': 'Urban Hype'},
 {'artista': 'The Architect'},
 {'artista': 'The Architect'},
 {'artista': 'Mill Bill'},
 {'artista': 'Chaugs'},
 {'artista': 'Murs'},
 {'artista': 'Conjuro Epiléptico'},
 {'artista': 'M.C. Mack'},
 {'artista': 'Kano'},
 {'artista': 'Solja'},
 {'artista': 'Vincent Van Great'},
 {'artista': 'Dana Coppafeel'},
 {'artista': 'Yo-Dot'},
 {'artista': 'Rich The Factor'},
 {'artista': 'Sophiegrophy'},
 {'artista': 'Jia Lih'},
 {'artista': 'Swelto'},
 {'artista': 'Factor'},
 {'artista': 'Tacit'},
 {'artista': 'Lil Los'},
 {'artista': '12mé'},
 {'artista': 'DJ Kaka'},
 {'artista': 'B.I.G'},
 {'artista': 'Lil Los'},
 {'artista': 'Tony Stone'},
 {'artista': 'Mill Bill'},
 {'artista': 'Murda'},
 {'artista': "John'nay Lasha"},
 {'artista': 'Rydah J. Klyde'},
 {'artista': "Al'Tarba"},
 {'artista': 'DJ Nixon'},
 {'artista': 'Dizzy Wright'},
 {'artista': 'Gabriel Máni'},
 {'artista': 'Ágúst Karel'},
 {'artista': 'D-Weez'},
 {'artista': 'Lil Juu Widdas'},
 {'artista': 'Dj Spinna'},
 {'artista': 'Lil Los'},
 {'artista': 'Astreaux Guillotine'},
 {'artista': 'Lord Jordvn'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'Dena'},
 {'artista': 'Icewear Vezzo'},
 {'artista': 'Maxy Jay'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'Hyu'},
 {'artista': 'Anja Kotar'},
 {'artista': 'Leanbeatz'},
 {'artista': 'Shun Millions'},
 {'artista': 'Kane'},
 {'artista': 'King Ameas'},
 {'artista': 'Kyril'},
 {'artista': 'Quan Duke'},
 {'artista': 'Oriole'},
 {'artista': 'Kaele Bigger'},
 {'artista': 'Tal Hefter'},
 {'artista': 'Icee'},
 {'artista': 'Pain Loc'},
 {'artista': 'Venom'},
 {'artista': 'Ray Dog'},
 {'artista': 'Yung Stackz'},
 {'artista': 'Quan Duke'},
 {'artista': 'NUUXS'},
 {'artista': 'J Soulja'},
 {'artista': 'Amirah Tiye'},
 {'artista': 'D-Weez'},
 {'artista': 'The Architect'},
 {'artista': 'Lil Los'},
 {'artista': 'Odd Nosdam'},
 {'artista': 'Solareye'},
 {'artista': 'Lil Los'},
 {'artista': 'Mattis'},
 {'artista': 'Blezz'},
 {'artista': 'ShabZi Madallion'},
 {'artista': 'Erick Rush'},
 {'artista': 'M.C. Mack'},
 {'artista': 'YFilla'},
 {'artista': 'Armanie'},
 {'artista': 'Leanbeatz'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'DJ Sem'},
 {'artista': 'Makassy'},
 {'artista': 'Sarah'},
 {'artista': 'Hancoq'},
 {'artista': 'TL Jones'},
 {'artista': 'Nati Hassid'},
 {'artista': 'טוכטי'},
 {'artista': 'Shlomi Alon'},
 {'artista': 'Myke Bogan'},
 {'artista': 'Kid Indigo'},
 {'artista': 'DELTA ARTHUR'},
 {'artista': 'Q052'},
 {'artista': 'ШЕFF'},
 {'artista': 'Fratelli-B'},
 {'artista': 'ШЕFF'},
 {'artista': 'Furagain'},
 {'artista': 'Ryda'},
 {'artista': 'Ryda'},
 {'artista': 'ShabZi Madallion'},
 {'artista': 'Lil Los'},
 {'artista': 'Luke Vallen'},
 {'artista': 'Lesley Kwam'},
 {'artista': 'Ryda'},
 {'artista': 'Rain'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'Yb Flee'},
 {'artista': 'Donk'},
 {'artista': 'Playbwoi Tha Great'},
 {'artista': 'Trae Trap'},
 {'artista': 'Boona Badazz'},
 {'artista': 'Vaze Haze'},
 {'artista': 'D-Weez'},
 {'artista': 'Eazy Racks'},
 {'artista': 'Camb'},
 {'artista': 'Benjahvites'},
 {'artista': 'JURI'},
 {'artista': 'The Architect'},
 {'artista': 'G-rdz'},
 {'artista': 'Jairzinho'},
 {'artista': 'Badhabitz'},
 {'artista': 'Thug Lucciano'},
 {'artista': 'Rizzo Rizzo'},
 {'artista': 'Cinnay'},
 {'artista': 'Mabuyu'},
 {'artista': 'Leanbeatz'},
 {'artista': 'K Kutta'},
 {'artista': 'Ikaz Boi'},
 {'artista': 'Козачок'},
 {'artista': '615 Exclusive'},
 {'artista': 'Hyu'},
 {'artista': 'Ezra'},
 {'artista': 'Ro9'},
 {'artista': 'M.C. Mack'},
 {'artista': 'Yung Skeet'},
 {'artista': 'Dj Burn One'},
 {'artista': 'The Five Points Bakery'},
 {'artista': 'Lakshane'},
 {'artista': 'Mill Bill'},
 {'artista': 'Gena'},
 {'artista': 'J-Wats'},
 {'artista': 'Ace Cino'},
 {'artista': 'Damedot'},
 {'artista': 'Al Major Rob'},
 {'artista': 'CMDWN'},
 {'artista': 'FIJI'},
 {'artista': 'CASTRO'},
 {'artista': 'Zeptah'},
 {'artista': 'M.C. Mack'},
 {'artista': "So'"},
 {'artista': 'Tay Dee'},
 {'artista': 'Pe2ny'},
 {'artista': 'M.C. Mack'},
 {'artista': 'Cilvaringz'},
 {'artista': 'Chip Charlez'},
 {'artista': 'J-Wats'},
 {'artista': 'Xtacy'},
 {'artista': 'Eric the Red'},
 {'artista': 'Illinformed'},
 {'artista': 'D-Weez'},
 {'artista': 'Lash Quan'},
 {'artista': 'Hoodini'},
 {'artista': 'Luke Vallen'},
 {'artista': 'Micall Parknsun'},
 {'artista': 'Mr. Thing'},
 {'artista': 'Warriorz'},
 {'artista': 'Öökülm'},
 {'artista': 'Mart Rauba'},
 {'artista': 'Pe2ny'},
 {'artista': 'Lay Lay'},
 {'artista': 'Assim'},
 {'artista': 'Chaugs'},
 {'artista': 'DJ Manipulator'},
 {'artista': 'Lil Los'},
 {'artista': 'Nate Bone'},
 {'artista': 'Ampichino'},
 {'artista': 'Chey Dolla'},
 {'artista': 'Rush Boarda'},
 {'artista': 'Playboy Shane'},
 {'artista': 'The Architect'},
 {'artista': 'Playbwoi Tha Great'},
 {'artista': 'Lil Dubie'},
 {'artista': 'Pe2ny'},
 {'artista': 'Task Force'},
 {'artista': 'K Kutta'},
 {'artista': 'M.C. Mack'},
 {'artista': 'Kami Kaze Inc.'},
 {'artista': 'M.C. Mack'},
 {'artista': 'Mac-Yo'},
 {'artista': 'Sean Gonzalez'},
 {'artista': 'K Kutta'},
 {'artista': 'Adje'},
 {'artista': 'roselilah'},
 {'artista': 'Tr1ckmusic'},
 {'artista': "5 o'clock"},
 {'artista': 'ГРОТ'},
 {'artista': "Tre'shon"},
 {'artista': 'J-Wats'},
 {'artista': 'Ofiri'},
 {'artista': 'Snow'},
 {'artista': '506'},
 {'artista': 'TinTin V.'},
 {'artista': "John'nay Lasha"},
 {'artista': 'Risskant'},
 {'artista': 'Ace'},
 {'artista': 'Tenchoo'},
 {'artista': 'Promotioneel'},
 {'artista': 'Rumbull'},
 {'artista': 'Seize'},
 {'artista': 'Solareye'},
 {'artista': 'Tokztero'},
 {'artista': 'Joker N Toker'},
 {'artista': 'Serengeti'},
 {'artista': 'CY Muzik'},
 {'artista': 'Eli'},
 {'artista': 'J-Wats'},
 {'artista': 'Tao Quit'},
 {'artista': 'Gnrl Ape1'},
 {'artista': 'ШЕFF'},
 {'artista': 'Mr. Simon'},
 {'artista': 'Радуга'},
 {'artista': 'Johnny Gee'},
 {'artista': "John'nay Lasha"},
 {'artista': 'Fratelli-B'},
 {'artista': 'Wasaru'},
 {'artista': 'Silvestro Dice'},
 {'artista': 'Gena'},
 {'artista': 'Graci'},
 {'artista': 'ШЕFF'},
 {'artista': 'The Architect'},
 {'artista': 'Lady J'},
 {'artista': 'Phidizz'},
 {'artista': 'Rendition'},
 {'artista': 'The Architect'},
 {'artista': 'Dutch Rebelle'},
 {'artista': 'Tal Hefter'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'D-Weez'},
 {'artista': 'Scoot Da Kidd'},
 {'artista': 'Feinos'},
 {'artista': 'Sean Gonzalez'},
 {'artista': 'K Kutta'},
 {'artista': 'Christian'},
 {'artista': 'Dora Moroni'},
 {'artista': 'Dolla Dame'},
 {'artista': 'Prezi'},
 {'artista': 'Cash Click Boog'},
 {'artista': 'Paper Tiger'},
 {'artista': 'Captain Over'},
 {'artista': 'Mill Bill'},
 {'artista': 'Young Thug'},
 {'artista': 'Travis Scott'},
 {'artista': 'Eladio Carrion'},
 {'artista': 'Bad Bunny'},
 {'artista': 'Arce'},
 {'artista': 'Kidd Keo'},
 {'artista': 'Ele A El Dominio'},
 {'artista': 'Rels B'},
 {'artista': 'Lil Tecca'},
 {'artista': 'XXXTENTACION'},
 {'artista': 'Arce'},
 {'artista': 'Al Safir'},
 {'artista': 'Arce'},
 {'artista': "Heuss L'enfoiré"},
 {'artista': 'Jul'},
 {'artista': 'Delaossa'},
 {'artista': 'J.Moods'},
 {'artista': 'Paulo Londra'},
 {'artista': 'Matasvandals'},
 {'artista': 'Da Silva'},
 {'artista': 'Al Safir'},
 {'artista': 'Matasvandals'},
 {'artista': 'Mauri'},
 {'artista': 'Al Safir'},
 {'artista': 'SFDK'},
 {'artista': 'Blake'},
 {'artista': 'Zaidbreak'},
 {'artista': 'Miranda'},
 {'artista': 'El Jincho'},
 {'artista': 'LosNiñosDelCaminito'},

In [ ]:
# Se puede guardar y extraer en un JSON el contenido de la variable 'lista_artistas_hip_hop' y repetir el proceso de: Cargar JSON y Función con este JSON

with open("hiphop_artistas_unicos.json", "w") as f: # Guardar Artistas Únicos en un JSON
    json.dump(lista_artistas_hip_hop, f, indent = 4, ensure_ascii =  False)
print("JSON guardado correctamente")

JSON guardado correctamente

In [ ]:
# FUNCIÓN 2: Extraer información de la API teniendo en cuenta los artistas de Hip-Hop (En mi caso, no lo hice con el último JSON extraído y guardado)

def filtrar_artistas_comunes (lista_artistas_hip_hop):
    artistas_comun = []
  
    print(f"Iniciando comparación de datos para {len(lista_artistas_hip_hop)} artistas")
    print("----")

    for elemento in lista_artistas_hip_hop:
        print(f"Buscando información de: {elemento}")
        url = "http://ws.audioscrobbler.com/2.0/" # Url 
        params = { # Para configurar el diccionario 
            "method": "artist.getInfo", # Para mirar dentro de esa lista específica del URL
            "artist": elemento,  # Usamos la variable del bucle, no la lista completa para buscar el nombre del artista
            "api_key" : "e313d3e1e9201b89cf4199ad1591d3d7", # Identificador de 'Last.fm'
            "format": "json"} # Para que la respuesta sea procesable por Python  
            
        try:
            
            response = requests.get(url, params=params) # La petición ocurre DENTRO del bucle
            datos_api = response.json() 
            print(f"Se ha logrado la conexion: {response.status_code}")
            print("----")

            if "artist" in datos_api:
                artistas_comun.append(elemento)  # Guardamos el resultado en nuestra lista
            
        except Exception as e:
            print(f"Error con {elemento}: {e}")
            print("----")

    print(f"¡Proceso finalizado! Se han recuperado {len(artistas_comun)} artistas en común entre el JSON y en la API")

    return artistas_comun

In [55]:
lista_artistas = filtrar_artistas_comunes(lista_artistas_hip_hop)

Iniciando comparación de datos para 3642 artistas
----
Buscando información de: {'artista': 'XXXTENTACION'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'The Alchemist'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Action Bronson'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Arcángel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'LosNiñosDelCaminito'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'KHEA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Duki'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Cazzu'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Duki'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Becky G'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Prince Royce'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'DJ Luian'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Mambo Kingz'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Anuel AA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'C. Tangana'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Alizzz'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kanye West'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kidd Keo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Delaossa'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Carrion GodBle$$'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Perea'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'J.Moods'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Trueno'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Blake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'j-hope'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Supreme Boi'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Soolking'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Matasvandals'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Da Silva'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rels B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Diplo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'FERNANDOCOSTA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Chicho Beats'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kidd Keo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Blake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'j-hope'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Denom'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Vengui'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nadal015'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kaze'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Dj Figu'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'El Perla'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Fazzini'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Franky Style'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kidd Keo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Miranda'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'WOS'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Matasvandals'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Carlytos Vela'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'JAVI BAMBINI CATTIVI'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'FERNANDOCOSTA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Chicho Beats'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'j-hope'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rels B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kidd Keo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Alemán'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Blake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Fazzini'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Franky Style'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Revol'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'J Balvin'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Arcángel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'De La Ghetto'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Dirty Porko'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Duki'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'DrefQuila'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'XXXTENTACION'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Lil Pump'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Swae Lee'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Maluma'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Diplo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Trippie Redd'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Eladio Carrion'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Big Soto'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rels B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kidd Keo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'YSY A'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Hard GZ'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'FERNANDOCOSTA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Denom'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Blasfem'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Eminem'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Subze'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Edoby'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Denom'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Mac Miller'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Hard GZ'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Lil GZ'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Calero LDN'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Trap Capos'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Noriel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Gadiel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bryant Myers'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Walls'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'El Jincho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'SFDK'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Cardi B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Eminem'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Joyner Lucas'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Lil Baby'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Gunna'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Underdann'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Trueno'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rels B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'El Jincho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Costa'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Costa'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natos y Waor'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Ninho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Residente'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nach'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nicky Jam'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Arcángel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'A Boogie Wit da Hoodie'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Post Malone'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kanye West'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'YSY A'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nanpa Básico'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'ToteKing'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Eladio Carrion'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Delaossa'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Raggio'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Chicolisto'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Saske'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'J.Moods'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Dheformer Galinier'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bizarrap'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bartofso'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': '3robi'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Mula B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nanpa Básico'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Benny Benni'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Daddy Yankee'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Bad Bunny'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Pusho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Farruko'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Noriel'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Miky Woodz'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Soolking'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Maes'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Booba'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Maes'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Alemán'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Charlie Hijos Bastardos'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'YSY A'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Akapellah'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Alemán'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'C. Tangana'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Fntxy'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Felo Blonck'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Jamby El Favo'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'ECKO'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'KHEA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Seven Kayne'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Iacho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Omar Varela'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': "Rim'K"}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Ninho'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Mula B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': '3robi'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Metro Boomin'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Offset'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Ñengo Flow'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kanye West'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'XXXTENTACION'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Joey Bada$$'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'C.R.O'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Duki'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'C.R.O'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'KHEA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Teo LB'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Nanpa Básico'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Drake'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'KIDS SEE GHOSTS'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Louis Prima'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Cosculluela'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Migos'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Post Malone'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kanye West'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Miky Woodz'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rels B'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Moha La Squale'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Eladio Carrion'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Cazzu'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'KHEA'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'ECKO'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Alemán'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Yung Sarria'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Fntxy'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'DrefQuila'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Kanye West'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'PARTYNEXTDOOR'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Crudo Means Raw'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Aaron May'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Dinos'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'NAV'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Travis Scott'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rejjie Snow'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Aminé'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Dana Williams'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Pablo Chill-E'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Duki'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Redimi2'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Natan El Profeta'}
Se ha logrado la conexion: 200
----
Buscando información de: {'artista': 'Rubinsky Rbk'}
Se ha logrado la conexion: 200

In [56]:
len(lista_artistas) # Para ver la cantidad total de artistas (¿Coindice con el JSON?)

3642

In [57]:
response = requests.get("http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Slipknot&api_key=dffc96fb5e37b49d6382379a54a66094&format=json") # Volvemos a llamar a la API para mirar su contenido

In [58]:
response.status_code # Comprobamos que se ha conectado a la API

200

In [59]:
datos_api = response.json() # Creamos la variable para poder utilizarlo y extraemos los datos de la API

In [60]:
datos_api # Para ver la estructura general

{'artist': {'name': 'Slipknot',
  'mbid': 'a466c2a2-6517-42fb-a160-1087c3bafd9f',
  'url': 'https://www.last.fm/music/Slipknot',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}],
  'streamable': '0',
  'ontour': '0',
  'stats': {'listeners': '4165992', 'playcount': '356201353'},
  'similar': {'artist': [{'name': 'Korn',
     'url': 'https://www.last.fm/music/Korn',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Stone Sour',
     'url': 'https://www.last.fm/music/Stone+Sour',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'System of a Down',
     'url': 'https://www.last.fm/music/System+of+a+Down',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Mudvayne',
     'url': 'https://www.last.fm/music/Mudvayne',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Vended',
     'url': 'https://www.last.fm/music/Vended',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]}]},
  'tags': {'tag': [{'name': 'Nu Metal',
     'url': 'https://www.last.fm/tag/Nu+Metal'},
    {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
    {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
    {'name': 'Nu-metal', 'url': 'https://www.last.fm/tag/Nu-metal'},
    {'name': 'rock', 'url': 'https://www.last.fm/tag/rock'}]},
  'bio': {'links': {'link': {'#text': '',
     'rel': 'original',
     'href': 'https://last.fm/music/Slipknot/+wiki'}},
   'published': '10 Feb 2006, 21:16',
   'summary': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>',
   'content': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [61]:
datos_api.keys() # Para sacar las Key

dict_keys(['artist'])

In [62]:
datos_api["artist"].keys()

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [63]:
datos_api["artist"]["name"] # Nombre del Artista

'Slipknot'

In [64]:
datos_api["artist"]["bio"]

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/Slipknot/+wiki'}},
 'published': '10 Feb 2006, 21:16',
 'summary': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>',
 'content': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [65]:
datos_api["artist"]["bio"]["summary"] # Biografía del Artista

'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>'

In [66]:
datos_api["artist"]["stats"]

{'listeners': '4165992', 'playcount': '356201353'}

In [67]:
datos_api["artist"]["stats"]["listeners"] # Audencia del Artista (num veces escuchadas)

'4165992'

In [68]:
datos_api["artist"]["stats"]["playcount"] # Reproducciones del Artista

'356201353'

In [69]:
datos_api["artist"]["similar"]

{'artist': [{'name': 'Korn',
   'url': 'https://www.last.fm/music/Korn',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Stone Sour',
   'url': 'https://www.last.fm/music/Stone+Sour',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'System of a Down',
   'url': 'https://www.last.fm/music/System+of+a+Down',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Mudvayne',
   'url': 'https://www.last.fm/music/Mudvayne',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]},
  {'name': 'Vended',
   'url': 'https://www.last.fm/music/Vended',
   'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'small'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'medium'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'large'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': 'mega'},
    {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
     'size': ''}]}]}

In [70]:
datos_api["artist"]["similar"]["artist"]

[{'name': 'Korn',
  'url': 'https://www.last.fm/music/Korn',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}]},
 {'name': 'Stone Sour',
  'url': 'https://www.last.fm/music/Stone+Sour',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}]},
 {'name': 'System of a Down',
  'url': 'https://www.last.fm/music/System+of+a+Down',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}]},
 {'name': 'Mudvayne',
  'url': 'https://www.last.fm/music/Mudvayne',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}]},
 {'name': 'Vended',
  'url': 'https://www.last.fm/music/Vended',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}]}]

In [71]:
datos_api["artist"]["similar"]["artist"][0]

{'name': 'Korn',
 'url': 'https://www.last.fm/music/Korn',
 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'small'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'medium'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'large'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'extralarge'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'mega'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': ''}]}

In [72]:
datos_api["artist"]["similar"]["artist"][0]["name"] # Nombre del Artista Similar

'Korn'

In [73]:
artistas_similares = datos_api["artist"]["similar"]["artist"] 
nombres_similares = [art["name"] for art in artistas_similares[:5]] # Esto crea una lista de strings: ['Megadeth', 'Slayer', 'Pantera'...]
print(nombres_similares)

['Korn', 'Stone Sour', 'System of a Down', 'Mudvayne', 'Vended']

In [74]:
# Información que necesito sobre el Artista:

# - Nombre --> datos_api["artist"]["name"] 📌
# - Biografía --> datos_api["artist"]["bio"]["summary"] 📌
# - Popularidad --> datos_api["artist"]["stats"]["listeners"] 📌
# - Estadístcas de Reproducción --> datos_api["artist"]["stats"]["playcount"] 📌
# - Artistas Similares --> datos_api["artist"]["similar"]["artist"][0]["name"] --> List comprenhension: nombres_similares = [art["name"] for art in artistas_similares[:5]] 📌

# (📌)

In [ ]:
# FUNCIÓN 3: Extraer información de los Artistas

def analizar_artistas (lista_artistas):
    datos_artistas = []
    lista_errores = [] # Lista para los fallos

    print(f"Iniciando comparación de datos para {len(lista_artistas_hip_hop)} artistas")
    print("----")

    for elemento in lista_artistas:
        nombre_artista = elemento["artista"] # Para iterar directamente por la Key del diccionario 

        url = "http://ws.audioscrobbler.com/2.0/" 
        params = { 
            "method": "artist.getInfo",
            "artist": nombre_artista, 
            "api_key" : "e313d3e1e9201b89cf4199ad1591d3d7",
            "format": "json"}
            
        try:
            response = requests.get(url, params=params) 
            datos_api = response.json() 
            print(f"Se ha logrado la conexion: {response.status_code}")
            print("----")

            if "artist" not in datos_api: # Si la API responde pero el artista no existe
                lista_errores.append({"artista" : nombre_artista})
                continue

            try: # Si el artista existe, intentamos sacar sus datos
                artistas_similares = datos_api["artist"]["similar"]["artist"] # Para iterar directamente desde las Key del diccionario 
                nombres_similares = [art["name"] for art in artistas_similares[:5]] # Para encontrar más de 1 artista similar, hasta 5
                
                informacion = { 
                        "artista": datos_api["artist"]["name"],
                        "audiencia": datos_api["artist"]["stats"]["listeners"],
                        "reproducciones" : datos_api["artist"]["stats"]["playcount"],
                        "similares" : nombres_similares, 
                        "biografía" : datos_api["artist"]["bio"]["summary"]}
                datos_artistas.append(informacion)

            except Exception as e: # Exception = "Captura cualquier error que ocurra"
                lista_errores.append({"artista" : nombre_artista})
                    
        except Exception as e:
            print(f"Error con {elemento}: {e}")
            print("----")

    print(f"Se han encontrado {len(lista_errores)} artistas que han dado algún error")
    print("----")
    print(f"Se han filtrado con éxito {len(datos_artistas)} artistas")

    return datos_artistas

In [79]:
artistas = analizar_artistas(lista_artistas)

Iniciando comparación de datos para 3642 artistas
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----
Se ha logrado la conexion: 200
----

In [ ]:
df_artistas = pd.DataFrame(artistas)

In [ ]:
print("--- PRIMEROS 5 REGISTROS ---") # Observamos los 5 primeros registros de la tabla
df_artistas.head()

--- PRIMEROS 5 REGISTROS ---

,artista,audiencia,reproducciones,similares,biografía
0,XXXTENTACION,2774772,335541691,Kid Trunks,"Jahseh Dwayne Onfroy (January 23, 1998 – June ..."
1,The Alchemist,1347530,47088057,Roc Marciano,"Alan Daniel Maman (born October 25, 1977), bet..."
2,Action Bronson,807075,25853544,Action Bronson & The Alchemist,"Ariyan Arslani (born December 2, 1983), better..."
3,Natos y Waor,52124,2763301,FERNANDOCOSTA,Dúo de rap madrileño. Cuentan con 8 trabajos a...
4,Arcángel,433430,14000648,De La Ghetto,"Austin Santos, conocido como Arcangel, nació e..."

In [ ]:
print("--- ÚLTIMOS 5 REGISTROS ---")  # Observamos los 5 últimos registros
df_artistas.tail()

--- ÚLTIMOS 5 REGISTROS ---

,artista,audiencia,reproducciones,similares,biografía
3240,KmoneyBeats,108,1219,Ponae,"<a href=""https://www.last.fm/music/KmoneyBeat..."
3241,Ali Gatie,574541,8120175,Sam Fischer,"Ali Gatie is an Iraqi–Canadian rapper, singer ..."
3242,Swelto,2114,56387,Pathos,"<a href=""https://www.last.fm/music/Swelto"">Re..."
3243,Lonewolf,26331,318516,Blazon Stone,There are two bands named Lonewolf:\n\n\n1) Lo...
3244,Pathos,7581,114066,Treasure Land,There are at least five bands who have used th...

In [ ]:
with open("artistas_hip_hop.json", "w") as f: # Guardar los datos de los Artistas en un JSON
    json.dump(artistas, f, indent = 4, ensure_ascii =  False)
print("JSON guardado correctamente")

JSON guardado correctamente