In [1]:
import json
import pandas as pd
import requests

In [2]:
#primero voy a abrir el archivo json, definitivo.json
with open('Files/definitivo.json', 'r') as archivo_json:
    fuente_json = json.load(archivo_json)

In [3]:
type(fuente_json)

list

In [4]:
fuente_json

[{'id': '7AlYBA5M9FVXDqN31cbExE',
  'artist_name': 'Remedios Amaya',
  'track_name': 'El zarandeo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4uqcES2h19TKAXQlciycrO',
  'artist_name': 'Nobuo Uematsu',
  'track_name': "Vamo'alla flamenco",
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0z6xGK2u3nSsbk9XeKYwZQ',
  'artist_name': 'Maurice Ravel',
  'track_name': 'Flamenco Bolero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6DjfWx0fXi0uQpedpvaCD9',
  'artist_name': 'Mark Towns',
  'track_name': 'After the Rain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1t91qQaPbOoo4pumaLih4W',
  'artist_name': 'Franz Schubert',
  'track_name': 'Tango Serenata (Ständchen)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7Kuasu0H7jArcADoFIHGUk',
  'artist_name': 'Mark Towns',
  'track_name': 'Corriente',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '02jM23k8pgm9gcZpyIn8Wk',
  'artist_name': 'Georges Moustaki',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2tnnbPGlhpY1420firAE7v',
  'artist_name': 'El Arrebato',
  'track_name': 'Rumba Canalla',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5OFZgm7YRtEHkoUdgIdMhF',
  'artist_name': 'Mark Towns',
  'track_name': 'Medley: The Way/La Via',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3dVVMsZCVGxce42Nd9a0XC',
  'artist_name': 'Tomaso Albinoni',
  'track_name': 'Tango Adagio',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4EOgdSxqtZZGvOrzuyQAGz',
  'artist_name': 'Johann Pachelbel',
  'track_name': 'Soleá Canon',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73KHkT0m5CW2xWgJAxCmoA',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, con baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1xikd54XPRJeJwRIv0yIzO',
  'artist_name': 'Mark Towns',
  'track_name': 'Sabrosa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0sKS1f30oQdGw903RR7fBN',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2eLniDU3Fbg6QUTbreLUrF',
  'artist_name': 'Márquez El Zapatero',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo de Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77242gtA1Jymsu2Vl9LGxR',
  'artist_name': 'Rocio Ruiz',
  'track_name': 'Flamenco,Cante por Martinete',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5YKBLRuQrbRDyrJaH7nywI',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, sin baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6mpQYMq1l1gU0ltQ0nO1IW',
  'artist_name': 'Antonio Vivaldi',
  'track_name': 'Primavera Tango (Four Seasons)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5pG5LCEvPX175P4ukUCFmR',
  'artist_name': 'La Carmen',
  'track_name': 'Flamencos a volar',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5qhcnvZmA4lm7fClwUbGwB',
  'artist_name': 'Enaldo Barrera',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XNVIE3jSJUoGzehQN9m9g',
  'artist_name': 'Chano Lobato',
  'track_name': 'Tanguillos de Cádiz',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6Nm0bBmYBI74CyApeaVZhF',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Rumba Allegro (Symphony no.40)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2L2ObU16rqwFvOIfbseBLX',
  'artist_name': 'Chiqui de Jerez',
  'track_name': 'El Teléfono de Mi Casa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2w6JLw4LmLEl57uUKhRldQ',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 190',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2edeklaJKKKx9ZyxDD2bSG',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Moonlight Rumba (Moonlight Sonata)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '71AKM5R1HijC743bGDWJBy',
  'artist_name': 'Mark Towns',
  'track_name': 'Merengue Gitano',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6dOwfELGupyrMHzkVegViT',
  'artist_name': 'Mark Towns',
  'track_name': 'Selva Urbana',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MJgtHcv1Wjv4Wxc9nJATo',
  'artist_name': 'Johann Sebastian Bach',
  'track_name': 'Tango Aria (Air on the G String)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2zEhscbOlOC6Bl6OVcWfL1',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo Compás 132',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6l2HTLRp8mTasMXOtvFEhb',
  'artist_name': 'Mark Towns',
  'track_name': 'Chucho',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5PGy4rzoVYQwMTfa4Svvgr',
  'artist_name': 'Levantito',
  'track_name': 'El Jardín de Mis Sueños',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5xA7tKg7QPsvAUVWap88rN',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Fandango for Elise (Für Elise)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1OkfxOngQIpLS7atBmCQSQ',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Media (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3QnvDtqgg8KGq8QypBbsv0',
  'artist_name': 'Dorantes',
  'track_name': 'Orobroy',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XvJsSuXS1iZxlpYojYj0W',
  'artist_name': 'Felix Mendelssohn',
  'track_name': 'Andante Rumba (Symphony 5)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZfMZkSi4itskqn6PNNBAc',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Rápida (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1AaqOJEurORS9gIjdeEHTD',
  'artist_name': 'Mark Towns',
  'track_name': 'Wondering',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0R3lPDIKv89qWEmYWTIoNE',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Bulería Adagio (Piano Concerto No.21)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1CVS0YLa7YpB4wRIQYiJPf',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 225',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ro8lFaoIHAv2chG3hq4xg',
  'artist_name': 'La Macanita',
  'track_name': 'Cantiñas del Marinero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5zNOlWjHpmZymXQ7jvxq1T',
  'artist_name': 'Mark Towns',
  'track_name': 'Like the Wind',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55fV0QtDYtaLfB3aTID6RF',
  'artist_name': 'Mark Towns',
  'track_name': 'Wind on the Mountain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cH2C7YxjpZQ7yhEwjs2AW',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos con baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '14mstquH2GHwuYmVp9qL1y',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Granaina: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5GW7kNyJpij82MhhnkIqAA',
  'artist_name': 'Traditional',
  'track_name': 'Medina Azahara (Granainas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZWMF5j3taR7DESgZLq8FU',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Lentas (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0d92SBPncK0zSR6IzhXxIM',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Surrender 2 Love - 2000 Remastered',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0kruq9DXxP9Lm0PdfbYBs0',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Medias (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bZvLAST6NXKOVBOocVzPr',
  'artist_name': 'Traditional',
  'track_name': 'Acera del Rio (Soleares)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0aberAzTHOxf4XH1JeUfnK',
  'artist_name': 'Traditional',
  'track_name': 'Salobre (Malagueñas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IMAOBRpQt9NLxheodkd18',
  'artist_name': 'Chonchi Heredia',
  'track_name': 'El Camino de Mi Destino',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1ggH47au252TP4T692rE0T',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'After The Rain - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77tmRwrSvrvHEHqku7OpXT',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Barcelona Nights - 2000 Digital Remaster',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4FsDuVJo6xLs8XTbdLP49D',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Malagueña: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '32aXQMl5U8lsVqk4n12waz',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 246',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jcdqacg2QJ3GHQujEuR5H',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 260',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jig5Z8KciCU2QXmnCBnnc',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Media (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5jsifLClBCWoE1nlasPiZh',
  'artist_name': 'Traditional',
  'track_name': 'Los Veleros (Alegrías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZPVwZFwsJ9SpcyEhrEBBR',
  'artist_name': 'Traditional',
  'track_name': 'Cancion (Peteneras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6ZFNcrtjNOn9bGrlPgnvt7',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Rondeña',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '28CDw1t8f0LwNQ0X3aUrGV',
  'artist_name': 'Ana Salazar',
  'track_name': 'Tu Eres para Mi',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '16UK3SdKxsyQojGZ2Xzn7u',
  'artist_name': 'Traditional',
  'track_name': 'Solquema (Bulerías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4JoAqRjk6ZbyYbSfTiKSVu',
  'artist_name': 'Traditional',
  'track_name': 'Mantilla y Peina (Guajiras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2NUssxdoSQRkZYyZykmnLb',
  'artist_name': 'Mark Towns',
  'track_name': 'Salamanca',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '314x76MVwlmB76sL1VMON2',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos sin baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '30xWhibl7o3ki0DsldxXr6',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 234',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6CGcj8K2ZZdPWqUbyJjxMK',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Cantes de Levante: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2qiy4xV66GJOllkMaPDD3M',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Peteneras: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4Z7Uf6yZA3Vqb0NED9c71j',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Rápida (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '593pSt7bzylRcc7CcsHqUK',
  'artist_name': 'El Trini',
  'track_name': 'Zambra: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0lxBV7AmHRY5uIWgR5ywtb',
  'artist_name': 'El Trini',
  'track_name': 'Fandangos Naturales: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79wfu1liWB4PZszqmQJuEu',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0pPUllW2drfZeyFF50aQp7',
  'artist_name': 'Traditional',
  'track_name': 'Riomar (Fandangos de Huelva)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cr6W8t5INBKw7zSupZY8R',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Farrucas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '515ndth3zLBPv4SY6JkJEZ',
  'artist_name': 'Los Activos',
  'track_name': 'Divertimiento Callejero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '38NCXxFi771HBggW1EC8If',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Granaína',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77yb0X5ESIBmkVYxlRZzO5',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Soléa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cvP0pwydWW64Akm14VlXs',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Zambra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ADzQCu8UnyZAnBie5bV57',
  'artist_name': 'Manuel de Angustias',
  'track_name': 'Te Tengo Que Querer',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1QESy53hSMNaiaNbmbBNuE',
  'artist_name': 'Traditional',
  'track_name': 'Claroscuro (Tangos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7oQQuYMbQBBtzSHMRKUXju',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Fandangos',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5A8FVt6fFmsXIRVIYD4iEG',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Tango - mayor y menor',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3Y2exCd1xymfuTmD9611BO',
  'artist_name': 'Ramon Montoya',
  'track_name': '"La Rosa" - Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6J7QoPhijQk8A0RLUvInFe',
  'artist_name': 'Mark Towns',
  'track_name': 'Touch',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2jSNj63K0JiyjA2q7UszKd',
  'artist_name': 'Traditional',
  'track_name': 'Las Ferialas (Sevillanas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6qZpjbbfNC8E3Efr70nIku',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Bulerías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6JTyUehuFzwzFZgCK3Wksj',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Tarantas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5UycZV2sto9vywMtNGzYYT',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3nWHz7o8trM4gwRrlx8wpu',
  'artist_name': 'Traditional',
  'track_name': 'Puerto Aguila (Tientos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5Tn3I3OYCPmZE4Adizv0HD',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Minera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2FNZ1W6NQJ6i2oaS9wNvil',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Seguiriyas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4csZty0AxR9WAIWVCDLjR5',
  'artist_name': 'Traditional',
  'track_name': 'Pedregales (Serranas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '48XjQujCABfBTZKi3j6pr9',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Santa Fe - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bUmOYqEMPGiv3gFJ2jB30',
  'artist_name': 'El Trini',
  'track_name': 'Toná: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IN6Zi7yjbeVK069J3QUEn',
  'artist_name': 'El Trini',
  'track_name': 'Debla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MyvQtdefpdadVUgGm4JD4',
  'artist_name': 'Acoustic Alchemy',
  'track_name': 'The Last Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4B55Q4PWuniTmPFr1Opw2Y',
  'artist_name': '植松 伸夫',
  'track_name': 'Vamo alla Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3yIsUXghgtMK3MuWVTsdsc',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Passing Storm - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0vqOXN6bhA4nWNjB5M5YuI',
  'artist_name': 'El Trini',
  'track_name': 'Livianas: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1uLokmb1H3AEfYM7K48DUY',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Rápida Cuatro Cuerpos (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3zLYx27eMIRdlw8xDMeIP7',
  'artist_name': 'El Trini',
  'track_name': 'Martinete: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1izTZlIOJCgHOaGJMoyr6N',
  'artist_name': 'El Trini',
  'track_name': 'Serrana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6OFw0tKxEAxkYnC5Qnfu6P',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Boleras (Guitarra, Laud y Bandurria)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0t27O9Fk0I0T1mRdJbE2Mz',
  'artist_name': 'El Trini',
  'track_name': 'Nana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79EWFLYoVfEUyzjNVVQIwJ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 120',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4369URVfz7QM9AwKqYz5nd',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6QshtnzwUzZsMkrPm3UkcZ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 160',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2pQ6wESsjj5mEKBAibYFat',
  'artist_name': 'El Trini',
  'track_name': 'Granaina y Media Granaina: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7uHQvzFgU7ViE8ES0qR3pc',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '26dXN84ePUqIHuR6e40D6E',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3lD2mjspXgh3hkIdrJuRZQ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4caAGy3SvHorRmh9RSFFd2',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6et3COTopxtId4gCpElGaU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4s8VgVoI16ILUFVXNDFZpl',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3KHA7uGRQrft6goXandJGU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3skYj3zKvIOXArFlT5h1aY',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 140',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7vr6MibrK67KqENxb6WKU8',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1SRAiujmU4mmYfF3mBDHP9',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '06stEj7Zoupi6o3lOD7vfx',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2VU3v2sjK6yg98fv0mG8MU',
  'artist_name': 'Ottmar Liebert',
  'track_name': '3 Women Walking - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3BfsufA6s2iPAmhTgmJ2HH',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Media (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1oWz1iu6eyOpc5u6AGHQU1',
  'artist_name': 'El Trini',
  'track_name': 'Trilla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55H080ETLO2D4787FpTCHv',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5XBXF86fIWxYLDpEzMfw8z',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 220',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1DzMgYzPaH4H6ugXNAfWFv',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'El Angelito',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2BLUSXzTKkp9yJ54ELJSLT',
  'artist_name': 'Ottmar Liebert',
  'track_name': '2 The Night - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6UvU9cOu3MjWbDxiF2h3ug',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Que bonita va',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1n1Cr82fHJ7dg1n6VPGD5V',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Moon Over Trees - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73XZI6jT8OKrCikrK7EYK4',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Un año de espera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2DVp3fA4JwfYseQU9wR67W',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Cohetes en el aire',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4SRtBNkq160IcE1Z8zRDmG',

In [5]:
len(fuente_json)

61617

In [6]:
df_fuente_json = pd.read_json('Files/definitivo.json') 
df_fuente_json.head(1000)

,id,artist_name,track_name,genre,year
0,7AlYBA5M9FVXDqN31cbExE,Remedios Amaya,El zarandeo,flamenco,2000
1,4uqcES2h19TKAXQlciycrO,Nobuo Uematsu,Vamo'alla flamenco,flamenco,2000
2,0z6xGK2u3nSsbk9XeKYwZQ,Maurice Ravel,Flamenco Bolero,flamenco,2000
3,6DjfWx0fXi0uQpedpvaCD9,Mark Towns,After the Rain,flamenco,2000
4,1t91qQaPbOoo4pumaLih4W,Franz Schubert,Tango Serenata (Ständchen),flamenco,2000
...,...,...,...,...,...
995,0l1VmlgGHZXYL0CR27ryRz,Jo Basile,Je T'Aime Encore Plus,indie,2000
996,4rs0A9RRJy6BPR1Mq1czcZ,Guddu Rangila,Ab Naahi Sutem Kinara,indie,2000
997,57eMvbS96z94E6KzRaEOEj,Lindisfarne,Shine On,indie,2000
998,6A8Nhein0Z7Ug2Gfh08ox1,Marcos Sabino,Paz e Harmonia,indie,2000
999,3WoVUGUsSc5hvpLQnyJqRa,Ted Heath,I Like To Recognise The Tune,indie,2000

In [7]:
df_fuente_json=pd.DataFrame(fuente_json)

In [8]:
print (df_fuente_json.head())

                       id     artist_name                  track_name  \
0  7AlYBA5M9FVXDqN31cbExE  Remedios Amaya                 El zarandeo
1  4uqcES2h19TKAXQlciycrO   Nobuo Uematsu          Vamo'alla flamenco
2  0z6xGK2u3nSsbk9XeKYwZQ   Maurice Ravel             Flamenco Bolero
3  6DjfWx0fXi0uQpedpvaCD9      Mark Towns              After the Rain
4  1t91qQaPbOoo4pumaLih4W  Franz Schubert  Tango Serenata (Ständchen)

      genre  year
0  flamenco  2000
1  flamenco  2000
2  flamenco  2000
3  flamenco  2000
4  flamenco  2000

In [9]:
pd.read_json
pd.json_normalize(fuente_json)

,id,artist_name,track_name,genre,year
0,7AlYBA5M9FVXDqN31cbExE,Remedios Amaya,El zarandeo,flamenco,2000
1,4uqcES2h19TKAXQlciycrO,Nobuo Uematsu,Vamo'alla flamenco,flamenco,2000
2,0z6xGK2u3nSsbk9XeKYwZQ,Maurice Ravel,Flamenco Bolero,flamenco,2000
3,6DjfWx0fXi0uQpedpvaCD9,Mark Towns,After the Rain,flamenco,2000
4,1t91qQaPbOoo4pumaLih4W,Franz Schubert,Tango Serenata (Ständchen),flamenco,2000
...,...,...,...,...,...
61612,6Lv0uLFhPt6e4qcmoeltAq,Jade Macrae,Ain’t Nobody Home,rock,2026
61613,6Lv0uLFhPt6e4qcmoeltAq,Robben Ford,Ain’t Nobody Home,rock,2026
61614,4PtUbfBR2U2BC0uUrT9hnM,No Te Va Gustar,Todo Mal,rock,2026
61615,4PtUbfBR2U2BC0uUrT9hnM,Ciro y los Persas,Todo Mal,rock,2026
61616,762E489aCXNDuRg1sZaWmC,Artemas,time alone w u,rock,2026

In [10]:
# sacar de fuente.json todos los archivos que lleva 'pop'
archivos_latin = [] # en esta variable introduzco todos los archivos que son de genre=pop

for elemento in fuente_json:
    
    if 'latin' in elemento['genre'].lower():
        archivos_latin.append(elemento)

print(archivos_latin)

[{'id': '4FXSEdmbbeGmPIQltH27C8', 'artist_name': 'La Oreja de Van Gogh', 'track_name': 'Pop', 'genre': 'latin', 'year': 2000}, {'id': '0plPN6zr3r0vW4VA0cTlmO', 'artist_name': 'Dany Bpm', 'track_name': 'I Want to Know what Love Is', 'genre': 'latin', 'year': 2000}, {'id': '4ZFvUk3xhvofhh3rCaQbq0', 'artist_name': 'D-4-MA', 'track_name': 'The Promise', 'genre': 'latin', 'year': 2000}, {'id': '3JISoccsWqVz9KGZUK6pPX', 'artist_name': 'Enigmatik', 'track_name': 'Apache', 'genre': 'latin', 'year': 2000}, {'id': '1Hb0K8CGqKNaj2sBvvSkT7', 'artist_name': 'Nina Gordon', 'track_name': '2003', 'genre': 'latin', 'year': 2000}, {'id': '5N0cZG9UCMBMeetIPGW8G5', 'artist_name': 'Nostalgi-K', 'track_name': 'The Spirit - 2001 Remix', 'genre': 'latin', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Chenoa', 'track_name': 'Lady Marmalade', 'genre': 'latin', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Gisela', 'track_name': 'Lady Marmalade', 'genre': 'latin', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Verónica Romero', 'track_name': 'Lady Marmalade', 'genre': 'latin', 'year': 2001}, {'id': '0Ppu3VRq2skQDIfjcowHcZ', 'artist_name': 'NAIM', 'track_name': 'Guilty', 'genre': 'latin', 'year': 2001}, {'id': '0Ppu3VRq2skQDIfjcowHcZ', 'artist_name': 'Verónica Romero', 'track_name': 'Guilty', 'genre': 'latin', 'year': 2001}, {'id': '6eXUFbNK4uhqDsPTOKOuh0', 'artist_name': 'Naim', 'track_name': "Don't Let The Sun Go Down On Me", 'genre': 'latin', 'year': 2001}, {'id': '6eXUFbNK4uhqDsPTOKOuh0', 'artist_name': 'Alejandro Parreño', 'track_name': "Don't Let The Sun Go Down On Me", 'genre': 'latin', 'year': 2001}, {'id': '2NwBOhoA4xiJK2jmWp5FNd', 'artist_name': 'Nostalgi-K', 'track_name': 'Electricity - 2001Remix', 'genre': 'latin', 'year': 2001}, {'id': '1URps6RTulUZzTHmNmmyKW', 'artist_name': 'Technoiser', 'track_name': 'Water 2001', 'genre': 'latin', 'year': 2001}, {'id': '3FrhNoBm5cy8iuUlOUDdkJ', 'artist_name': 'DJ Ricardo', 'track_name': 'The Sound Barrier', 'genre': 'latin', 'year': 2001}, {'id': '1JbAj245mmW4GVX1ohOmLS', 'artist_name': 'Los Piratas', 'track_name': 'Gen 14', 'genre': 'latin', 'year': 2001}, {'id': '3vdxdwKTljNZPLEX7hcrMe', 'artist_name': 'TCR', 'track_name': 'P.o.p', 'genre': 'latin', 'year': 2001}, {'id': '70PRAaiRpevoPI4zbs2VGa', 'artist_name': 'X-Que, Vol. 8', 'track_name': 'When I Sleep', 'genre': 'latin', 'year': 2002}, {'id': '0sF8c858LGAUaTMPWihEvw', 'artist_name': '2002', 'track_name': 'The Sound of Still Water', 'genre': 'latin', 'year': 2002}, {'id': '3rkE8IiFy0z893ZqUzDFLk', 'artist_name': 'Tessa', 'track_name': 'Tú Volverás', 'genre': 'latin', 'year': 2002}, {'id': '5HLQc8z7BpfrNHmY0o5Ugu', 'artist_name': 'X-Que, Vol. 8', 'track_name': 'Beautiful Day - Home Version', 'genre': 'latin', 'year': 2002}, {'id': '1IudL4RSthUP5kWD0HLZUP', 'artist_name': '2002', 'track_name': 'City of Peace', 'genre': 'latin', 'year': 2002}, {'id': '4UzbnrVB4sKrYxlWRGNzBR', 'artist_name': 'Merche', 'track_name': 'El Barman', 'genre': 'latin', 'year': 2002}, {'id': '4xUeb0mgEljSLJIxFXLKPF', 'artist_name': 'Factoria X', 'track_name': "Rewards (feat. The Moreno's)", 'genre': 'latin', 'year': 2002}, {'id': '4xUeb0mgEljSLJIxFXLKPF', 'artist_name': "The Moreno's", 'track_name': "Rewards (feat. The Moreno's)", 'genre': 'latin', 'year': 2002}, {'id': '7tX0V2ikN9Y9UNH4d3w77F', 'artist_name': 'Sidonie', 'track_name': 'Mode', 'genre': 'latin', 'year': 2002}, {'id': '7sT8zEGhVsw85dCYP4MNUy', 'artist_name': 'Luis Morera', 'track_name': 'Generacion 2000', 'genre': 'latin', 'year': 2002}, {'id': '4UmOcKAtCNjlDFtHcxWcvh', 'artist_name': 'Toy Soldiers', 'track_name': 'Popcorn', 'genre': 'latin', 'year': 2002}, {'id': '5OsJWplppfqtByGFVx49je', 'artist_name': 'Bellepop', 'track_name': 'La vida que va (Heart in Distress)', 'genre': 'latin', 'year': 2002}, {'id': '0k9o36zHjfM2Oh79dGQTNs', 'artist_name': 'Sidonie', 'track_name': 'In Da Sun', 'genre': 'latin', 'year': 2002}, {'id': '2o4osHcCkrkaVFZ4d0i7rL', 'artist_name': 'Bellepop', 'track_name': 'Paraíso (Paradise)', 'genre': 'latin', 'year': 2002}, {'id': '5YQZJha9tq0pF9E7zCPJd4', 'artist_name': 'Dover', 'track_name': 'The Flame', 'genre': 'latin', 'year': 2003}, {'id': '5oz2AGkudJ4st3CaBz5Toa', 'artist_name': 'Melody', 'track_name': 'Será', 'genre': 'latin', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': 'H.A.W.K.', 'track_name': 'Freestyle', 'genre': 'latin', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': "Lil' Head", 'track_name': 'Freestyle', 'genre': 'latin', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': 'Kevo', 'track_name': 'Freestyle', 'genre': 'latin', 'year': 2003}, {'id': '7tbS96G0V7WMTxopfpe0nH', 'artist_name': 'Dj David Max', 'track_name': 'News 2003 - La Gaita Hard Mix', 'genre': 'latin', 'year': 2003}, {'id': '6ciXx0fgkmAnaiX3iv9Hjd', 'artist_name': 'Papas Fritas', 'track_name': 'Way You Walk', 'genre': 'latin', 'year': 2003}, {'id': '3X9e9mQzcQD15VlIkDnLKv', 'artist_name': 'Saturn DJ', 'track_name': 'Take Me 2003', 'genre': 'latin', 'year': 2003}, {'id': '3VVnAoNIHeTG8TYLxMymnv', 'artist_name': 'Melody', 'track_name': 'Será', 'genre': 'latin', 'year': 2003}, {'id': '74lY6ixYn1cHqacjoBPSD2', 'artist_name': 'Revolver', 'track_name': 'Fuera de lugar (feat. José Manuel Casañ)', 'genre': 'latin', 'year': 2003}, {'id': '74lY6ixYn1cHqacjoBPSD2', 'artist_name': 'Jose Manuel Casañ', 'track_name': 'Fuera de lugar (feat. José Manuel Casañ)', 'genre': 'latin', 'year': 2003}, {'id': '5IrU3wUKCbAjDxKjgdQfpm', 'artist_name': 'Deluxe', 'track_name': 'It Could Have Been My Mirror', 'genre': 'latin', 'year': 2003}, {'id': '5qbrqNka0MDjGAA00iTII6', 'artist_name': 'Deluxe', 'track_name': 'Hey Brother!', 'genre': 'latin', 'year': 2003}, {'id': '3zGzzKCLu6EDWVSldHivxu', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Skokian', 'genre': 'latin', 'year': 2004}, {'id': '7abWn4FXEvAhlLtIchWX0X', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Cerezo Rosa', 'genre': 'latin', 'year': 2004}, {'id': '3bgItdWfQfkG8xE1OEBIQm', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Mambo en Sax', 'genre': 'latin', 'year': 2004}, {'id': '4Jd8st6f7YT8cWCu4rfUl3', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Guadalajara', 'genre': 'latin', 'year': 2004}, {'id': '54nFeLRjuLsTO1V2nBNBda', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Concierto para Bongo', 'genre': 'latin', 'year': 2004}, {'id': '3zg5CC8Njjv51gU9BkyeJj', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Patricia', 'genre': 'latin', 'year': 2004}, {'id': '6QYSVloTcuUUbgLSkyNbZi', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Ni Hablar', 'genre': 'latin', 'year': 2004}, {'id': '2AWrydr4ZvpRRxKG1hdMtC', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Mambo en Trompeta', 'genre': 'latin', 'year': 2004}, {'id': '0qwoeKL8Lr9henafAPmWQH', 'artist_name': 'Xavier Cugat', 'track_name': 'Park Avenue Mambo', 'genre': 'latin', 'year': 2004}, {'id': '485Ym99WPK9AnQfrdavTGF', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Mambo #5', 'genre': 'latin', 'year': 2004}, {'id': '30VdK5HCUxmfFnxBUs3ZKn', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Mania', 'genre': 'latin', 'year': 2004}, {'id': '4BVKxdPXqi5BxiIm1HTB6p', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo No.5', 'genre': 'latin', 'year': 2004}, {'id': '58uwbL5DgZbr8dnViTGeVw', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Mambo 8', 'genre': 'latin', 'year': 2004}, {'id': '0bcE645A9OKeIINxcpHrtr', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Pianolo', 'genre': 'latin', 'year': 2004}, {'id': '75V6PU5qDIe0Qboc0zmBey', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Mary Dungue', 'genre': 'latin', 'year': 2004}, {'id': '3fi6iRg9CzqwlPoYkg3ORW', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Cose, Cose, Cose', 'genre': 'latin', 'year': 2004}, {'id': '5fwU1gFY2n2d7020R2Pzom', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Que Rico Mambo', 'genre': 'latin', 'year': 2004}, {'id': '4u75RzElHXjnoWU1WgScuX', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Al Compas del Mambo', 'genre': 'latin', 'year': 2004}, {'id': '5oPMlaCPFqRSsuwc3JPhmP', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'La Niña Popof', 'genre': 'latin', 'year': 2004}, {'id': '4ufHuDO722ddEqx9horHXG', 'artist_name': 'The Mambo All Stars Orchestra', 'track_name': 'Bonito Y Sabroso', 'genre': 'latin', 'year': 2004}, {'id': '4KS151YPj3MNNSXvB7OqLa', 'artist_name': 'Ruben Ramos', 'track_name': 'Thirteen Years', 'genre': 'latin', 'year': 2004}, {'id': '38z0tDFKUURu2iz8IXYPh7', 'artist_name': 'Jamband', 'track_name': 'Redman (Live)', 'genre': 'latin', 'year': 2004}, {'id': '2NyS5zAYQFkRVREOkLYohd', 'artist_name': 'Jamband', 'track_name': 'Yessi (Live)', 'genre': 'latin', 'year': 2004}, {'id': '2TZ63DAuzYmZVwzvdLzI2s', 'artist_name': 'Jamband', 'track_name': 'Crowd Ah People (Live)', 'genre': 'latin', 'year': 2004}, {'id': '17YOPI4nUkFkiwW8xcNev1', 'artist_name': 'Cal Tjader', 'track_name': 'Linda Chicana', 'genre': 'latin', 'year': 2004}, {'id': '75Vk1xw3X86erwnOp0UecK', 'artist_name': 'Jamband', 'track_name': 'Session Mus Irie 50 Years in the Bvi (Live)', 'genre': 'latin', 'year': 2004}, {'id': '4lS0onDdHpdvk46WUbwbz7', 'artist_name': 'The Treniers', 'track_name': "Devil's Mambo - 78rpm Version", 'genre': 'latin', 'year': 2004}, {'id': '0zDbuSCBrDJoeWQX376Ppq', 'artist_name': 'Cal Tjader', 'track_name': 'Speak Low', 'genre': 'latin', 'year': 2004}, {'id': '7KQYObTopYOSJrFZePskvr', 'artist_name': 'Xavier Cugat', 'track_name': 'Anything Can Happen-Mambo', 'genre': 'latin', 'year': 2004}, {'id': '7KQYObTopYOSJrFZePskvr', 'artist_name': 'Abbe Lane', 'track_name': 'Anything Can Happen-Mambo', 'genre': 'latin', 'year': 2004}, {'id': '52DqJWkR7OwZNJJQvgwhzV', 'artist_name': 'Jamband', 'track_name': 'Para Ah You (Live)', 'genre': 'latin', 'year': 2004}, {'id': '7lfMwwQgnNXGLsZcGFe1wu', 'artist_name': 'Jamband', 'track_name': 'Big Car Show (Live)', 'genre': 'latin', 'year': 2004}, {'id': '3LVeDKGh2VB4FZn2uSaARu', 'artist_name': 'Jamband', 'track_name': 'No Fraid Dem (Live)', 'genre': 'latin', 'year': 2004}, {'id': '2Ute3FoOMCtAyir8ou9mTP', 'artist_name': 'Jamband', 'track_name': 'All True Jamband Soldiers (Live)', 'genre': 'latin', 'year': 2004}, {'id': '2TVeeSLXclMEi4ClAJ5M60', 'artist_name': 'Jamband', 'track_name': 'Deh Music Exciting (Live)', 'genre': 'latin', 'year': 2004}, {'id': '0tzXx1CSOzM1gGTjiqH5FA', 'artist_name': 'Jamband', 'track_name': 'Crowd a People (Live)', 'genre': 'latin', 'year': 2004}, {'id': '2acMfrIVrR6434BbFNgNcD', 'artist_name': 'Jamband', 'track_name': 'You Know What I Wanna See (Live)', 'genre': 'latin', 'year': 2004}, {'id': '7CAwv9EfExHwBGC9N8ssIy', 'artist_name': 'Jamband', 'track_name': 'Music from the Vi (Live)', 'genre': 'latin', 'year': 2004}, {'id': '61gBEHEt0rdhgahK2ISoWY', 'artist_name': 'Jamband', 'track_name': 'Yuh Waist (Live)', 'genre': 'latin', 'year': 2004}, {'id': '6ViuY5lhrTs57vr8EZKKfE', 'artist_name': 'Jamband', 'track_name': 'Everybody in the Village (Live)', 'genre': 'latin', 'year': 2004}, {'id': '0K2sbXKDDGGXgDbRub6rea', 'artist_name': 'Jamband', 'track_name': 'Lala Lala (Live)', 'genre': 'latin', 'year': 2004}, {'id': '7p7Ikkey7BpbDryxidA3Kh', 'artist_name': 'Jamband', 'track_name': 'Ben Down Lo Riddim (Live)', 'genre': 'latin', 'year': 2004}, {'id': '0vhVUt4nr516qA6nkaxPKJ', 'artist_name': 'Jamband', 'track_name': 'Wait for Me (Live)', 'genre': 'latin', 'year': 2004}, {'id': '1PMe9QOs22zvYcvV36Hr1z', 'artist_name': 'Jamband', 'track_name': 'Yeah Yeah Yeah Yeah (Live)', 'genre': 'latin', 'year': 2004}, {'id': '6VTGiOlkw3kQ8znslyKNYD', 'artist_name': 'Jamband', 'track_name': 'Get Your Groove on (Live)', 'genre': 'latin', 'year': 2004}, {'id': '3RcZ8otRLuxOyo0Uu5s67p', 'artist_name': 'Jamband', 'track_name': 'And the Beat Goes on (Live)', 'genre': 'latin', 'year': 2004}, {'id': '3C7hhWWAhVYylYet8PJ87u', 'artist_name': 'Jamband', 'track_name': 'Party Start Now (Live', 'genre': 'latin', 'year': 2004}, {'id': '3dWQN1Q61IJ18brhZxd9kJ', 'artist_name': 'Jamband', 'track_name': 'Yuh Getting Pay (Live)', 'genre': 'latin', 'year': 2004}, {'id': '5lsxKY3KyluQmqSkkMGZ4L', 'artist_name': 'Jamband', 'track_name': 'Give Me My Bass Line Now (Live)', 'genre': 'latin', 'year': 2004}, {'id': '3qOjdDY2eI8If0Vgx2qhIj', 'artist_name': 'Jamband', 'track_name': 'Tempreture Rising (Live)', 'genre': 'latin', 'year': 2004}, {'id': '4im1aGIbTLBEAG7zxMBAns', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'La Nubes', 'genre': 'latin', 'year': 2004}, {'id': '2ycwQf0ZeIAAmmEMH3Ux63', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Un Puno De Tierra', 'genre': 'latin', 'year': 2004}, {'id': '6C1jRnjEy1NwzhsdowiLbA', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Este Amor Que Tengo', 'genre': 'latin', 'year': 2004}, {'id': '015cEVa6swnQviLe0cR3L2', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Cumbia Del Sol', 'genre': 'latin', 'year': 2004}, {'id': '11fMRJBe65Zp3aaZA7uOEH', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'In My House', 'genre': 'latin', 'year': 2004}, {'id': '6S7YZFUpYfJYixDu1oWlhO', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'La Luna', 'genre': 'latin', 'year': 2004}, {'id': '6vmQLduQ0RhbxW32FDJA5o', 'artist_name': 'Jamband', 'track_name': 'Wuk up Harder (Live)', 'genre': 'latin', 'year': 2004}, {'id': '0BkGu0hrI3vqoMy0wNRvp8', 'artist_name': 'Jamband', 'track_name': 'Jouvert Shirts from Myron (Live)', 'genre': 'latin', 'year': 2004}, {'id': '3Lqv29lmwfWfNcLPqbALEM', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Dos Hojas Sin Rumbo', 'genre': 'latin', 'year': 2004}, {'id': '407SZzyW1w7MqhnbKy5oZv', 'artist_name': 'Jamband', 'track_name': 'Happy Birthday Pretta (Live)', 'genre': 'latin', 'year': 2004}, {'id': '6ZJefFLPWtajHtRIprh9zC', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Wasted Days, Wasted Nights', 'genre': 'latin', 'year': 2004}, {'id': '14Dyw1Mw0CjFP0MCU7ZScp', 'artist_name': 'Tango For 3', 'track_name': 'Milonga Del Angel', 'genre': 'latin', 'year': 2004}, {'id': '5Svf7RNq61feLxcKcipACY', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Volver Volver', 'genre': 'latin', 'year': 2004}, {'id': '00j6vfAr60Lx2HZQ0jdfXF', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Cartas Marcadas', 'genre': 'latin', 'year': 2004}, {'id': '6emFKXn9lb2JpJu016KXLt', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'La Puerta Negra', 'genre': 'latin', 'year': 2004}, {'id': '6lrABF30wkwmbyvMO7Rvu4', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Via El Valle', 'genre': 'latin', 'year': 2004}, {'id': '4YqV6cVpisuIKYzatvgzWc', 'artist_name': 'Crooked Stilo', 'track_name': 'Naturally Crooked', 'genre': 'latin', 'year': 2004}, {'id': '2pLoO3raJFR7zWdepdzDqW', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Sabor A Mi', 'genre': 'latin', 'year': 2004}, {'id': '0ksYlVNYmtYLf6CIhrdo3P', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'No Me Queda Mas', 'genre': 'latin', 'year': 2004}, {'id': '6FHXGuCG0PURSmARs4AyMc', 'artist_name': 'Jay And The Latin Sounds', 'track_name': 'Un Rinconcito En El Cielo', 'genre': 'latin', 'year': 2004}, {'id': '0k14MPzBf1HM9YMjvvUgJ4', 'artist_name': 'Krosfyah', 'track_name': 'Keep Rolling It', 'genre': 'latin', 'year': 2004}, {'id': '0k14MPzBf1HM9YMjvvUgJ4', 'artist_name': 'Edwin Yearwood', 'track_name': 'Keep Rolling It', 'genre': 'latin', 'year': 2004}, {'id': '0AKF7UpCRXvO5NgkfSNKc3', 'artist_name': 'Krosfyah', 'track_name': 'Keep Rolling It - Raw', 'genre': 'latin', 'year': 2004}, {'id': '0AKF7UpCRXvO5NgkfSNKc3', 'artist_name': 'Edwin Yearwood', 'track_name': 'Keep Rolling It - Raw', 'genre': 'latin', 'year': 2004}, {'id': '7wfTQsy2Cp0yjOuoNpwTYU', 'artist_name': 'Krosfyah Feat. Edwin Yearwood', 'track_name': 'French Kiss', 'genre': 'latin', 'year': 2004}, {'id': '4H7EZETK2oIjNwpQzVeSL9', 'artist_name': 'Krosfyah', 'track_name': 'All Is Mine', 'genre': 'latin', 'year': 2004}, {'id': '4H7EZETK2oIjNwpQzVeSL9', 'artist_name': 'Edwin Yearwood', 'track_name': 'All Is Mine', 'genre': 'latin', 'year': 2004}, {'id': '5jgrjVA7kA6Zr5zMFHAC3m', 'artist_name': 'Krosfyah', 'track_name': 'Sugar Cane - Road Mix', 'genre': 'latin', 'year': 2004}, {'id': '5jgrjVA7kA6Zr5zMFHAC3m', 'artist_name': 'Edwin Yearwood', 'track_name': 'Sugar Cane - Road Mix', 'genre': 'latin', 'year': 2004}, {'id': '1TpdbQiVcDcFRkr9ScJdxe', 'artist_name': 'Krosfyah', 'track_name': 'Invasion', 'genre': 'latin', 'year': 2004}, {'id': '1TpdbQiVcDcFRkr9ScJdxe', 'artist_name': 'Edwin Yearwood', 'track_name': 'Invasion', 'genre': 'latin', 'year': 2004}, {'id': '45xT78itKUbIJLhGljlI7g', 'artist_name': 'Krosfyah', 'track_name': 'Sugar Cane', 'genre': 'latin', 'year': 2004}, {'id': '45xT78itKUbIJLhGljlI7g', 'artist_name': 'Edwin Yearwood', 'track_name': 'Sugar Cane', 'genre': 'latin', 'year': 2004}, {'id': '55OwnW95xqA5cIDXMKAib9', 'artist_name': 'Stavros Kapsalis', 'track_name': 'Liaskovikiariko', 'genre': 'latin', 'year': 2004}, {'id': '6P7bC48BsaqweODyenFpzA', 'artist_name': 'Krosfyah', 'track_name': 'Holes', 'genre': 'latin', 'year': 2004}, {'id': '6P7bC48BsaqweODyenFpzA', 'artist_name': 'Edwin Yearwood', 'track_name': 'Holes', 'genre': 'latin', 'year': 2004}, {'id': '2mWt70c5q39CcU0n1bpdCz', 'artist_name': 'Xavier Cugat', 'track_name': 'Donde Estabas Tú', 'genre': 'latin', 'year': 2004}, {'id': '59sG98RKeK2MxCez2hY2eQ', 'artist_name': 'Xavier Cugat', 'track_name': 'Carnival in Uruguay', 'genre': 'latin', 'year': 2004}, {'id': '2yd5ctdrdvi6QU3kVUtzxp', 'artist_name': 'Xavier Cugat', 'track_name': 'Flute Nightmare', 'genre': 'latin', 'year': 2004}, {'id': '7fTj6qbZFhUauwyM1uZzS3', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Gallego', 'genre': 'latin', 'year': 2004}, {'id': '5EPndW1j8gdgDXRi6L7jGo', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Retozón', 'genre': 'latin', 'year': 2004}, {'id': '7xvYezyqQlM2rgfASffqG4', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Gordo', 'genre': 'latin', 'year': 2004}, {'id': '7Duw4J2m0DDtbjp6kLQuAQ', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Gitano', 'genre': 'latin', 'year': 2004}, {'id': '6UF3jmhT7ciDlcl9nGsVJy', 'artist_name': 'Xavier Cugat', 'track_name': 'Cerezo Rosa Y Manzano Blanco', 'genre': 'latin', 'year': 2004}, {'id': '4Cg4NDXrby5FyJeLY0Nwlo', 'artist_name': 'Xavier Cugat', 'track_name': 'Uuuh!', 'genre': 'latin', 'year': 2004}, {'id': '6RPxHOiflPzjscVNbFmHrg', 'artist_name': 'Xavier Cugat', 'track_name': 'Africano Soy', 'genre': 'latin', 'year': 2004}, {'id': '6RPxHOiflPzjscVNbFmHrg', 'artist_name': 'Juan Manuel', 'track_name': 'Africano Soy', 'genre': 'latin', 'year': 2004}, {'id': '4phOmPxqoUZkKhrXqpKT4s', 'artist_name': 'Xavier Cugat', 'track_name': 'Maracaibo', 'genre': 'latin', 'year': 2004}, {'id': '09B2L7O1qAr7hubRAJAYn3', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo at the Waldorf', 'genre': 'latin', 'year': 2004}, {'id': '2iNKWZ4ToIFxE9GeG0E618', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambolete', 'genre': 'latin', 'year': 2004}, {'id': '7uKdj1Mfbs1zRZ0wVECVL9', 'artist_name': 'Xavier Cugat', 'track_name': 'Mi Prieta', 'genre': 'latin', 'year': 2004}, {'id': '0qmDrfAG7wpTftwyUsvAIo', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo En España', 'genre': 'latin', 'year': 2004}, {'id': '2jWgnvD98168KSJvfIJrOa', 'artist_name': 'Xavier Cugat', 'track_name': 'Mambo Nº8', 'genre': 'latin', 'year': 2004}, {'id': '1SG4zb3lOY9ni2VRpnO5RM', 'artist_name': 'Xavier Cugat', 'track_name': 'Humpty Dumpty', 'genre': 'latin', 'year': 2004}, {'id': '1SG4zb3lOY9ni2VRpnO5RM', 'artist_name': 'Abbe Lane', 'track_name': 'Humpty Dumpty', 'genre': 'latin', 'year': 2004}, {'id': '0sSUyeGmdZsmG7hw17l2KU', 'artist_name': 'Xavier Cugat', 'track_name': 'Qué Rico El Mambo', 'genre': 'latin', 'year': 20

In [11]:
archivos_latin

[{'id': '4FXSEdmbbeGmPIQltH27C8',
  'artist_name': 'La Oreja de Van Gogh',
  'track_name': 'Pop',
  'genre': 'latin',
  'year': 2000},
 {'id': '0plPN6zr3r0vW4VA0cTlmO',
  'artist_name': 'Dany Bpm',
  'track_name': 'I Want to Know what Love Is',
  'genre': 'latin',
  'year': 2000},
 {'id': '4ZFvUk3xhvofhh3rCaQbq0',
  'artist_name': 'D-4-MA',
  'track_name': 'The Promise',
  'genre': 'latin',
  'year': 2000},
 {'id': '3JISoccsWqVz9KGZUK6pPX',
  'artist_name': 'Enigmatik',
  'track_name': 'Apache',
  'genre': 'latin',
  'year': 2000},
 {'id': '1Hb0K8CGqKNaj2sBvvSkT7',
  'artist_name': 'Nina Gordon',
  'track_name': '2003',
  'genre': 'latin',
  'year': 2000},
 {'id': '5N0cZG9UCMBMeetIPGW8G5',
  'artist_name': 'Nostalgi-K',
  'track_name': 'The Spirit - 2001 Remix',
  'genre': 'latin',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Chenoa',
  'track_name': 'Lady Marmalade',
  'genre': 'latin',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Gisela',
  'track_name': 'Lady Marmalade',
  'genre': 'latin',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Verónica Romero',
  'track_name': 'Lady Marmalade',
  'genre': 'latin',
  'year': 2001},
 {'id': '0Ppu3VRq2skQDIfjcowHcZ',
  'artist_name': 'NAIM',
  'track_name': 'Guilty',
  'genre': 'latin',
  'year': 2001},
 {'id': '0Ppu3VRq2skQDIfjcowHcZ',
  'artist_name': 'Verónica Romero',
  'track_name': 'Guilty',
  'genre': 'latin',
  'year': 2001},
 {'id': '6eXUFbNK4uhqDsPTOKOuh0',
  'artist_name': 'Naim',
  'track_name': "Don't Let The Sun Go Down On Me",
  'genre': 'latin',
  'year': 2001},
 {'id': '6eXUFbNK4uhqDsPTOKOuh0',
  'artist_name': 'Alejandro Parreño',
  'track_name': "Don't Let The Sun Go Down On Me",
  'genre': 'latin',
  'year': 2001},
 {'id': '2NwBOhoA4xiJK2jmWp5FNd',
  'artist_name': 'Nostalgi-K',
  'track_name': 'Electricity - 2001Remix',
  'genre': 'latin',
  'year': 2001},
 {'id': '1URps6RTulUZzTHmNmmyKW',
  'artist_name': 'Technoiser',
  'track_name': 'Water 2001',
  'genre': 'latin',
  'year': 2001},
 {'id': '3FrhNoBm5cy8iuUlOUDdkJ',
  'artist_name': 'DJ Ricardo',
  'track_name': 'The Sound Barrier',
  'genre': 'latin',
  'year': 2001},
 {'id': '1JbAj245mmW4GVX1ohOmLS',
  'artist_name': 'Los Piratas',
  'track_name': 'Gen 14',
  'genre': 'latin',
  'year': 2001},
 {'id': '3vdxdwKTljNZPLEX7hcrMe',
  'artist_name': 'TCR',
  'track_name': 'P.o.p',
  'genre': 'latin',
  'year': 2001},
 {'id': '70PRAaiRpevoPI4zbs2VGa',
  'artist_name': 'X-Que, Vol. 8',
  'track_name': 'When I Sleep',
  'genre': 'latin',
  'year': 2002},
 {'id': '0sF8c858LGAUaTMPWihEvw',
  'artist_name': '2002',
  'track_name': 'The Sound of Still Water',
  'genre': 'latin',
  'year': 2002},
 {'id': '3rkE8IiFy0z893ZqUzDFLk',
  'artist_name': 'Tessa',
  'track_name': 'Tú Volverás',
  'genre': 'latin',
  'year': 2002},
 {'id': '5HLQc8z7BpfrNHmY0o5Ugu',
  'artist_name': 'X-Que, Vol. 8',
  'track_name': 'Beautiful Day - Home Version',
  'genre': 'latin',
  'year': 2002},
 {'id': '1IudL4RSthUP5kWD0HLZUP',
  'artist_name': '2002',
  'track_name': 'City of Peace',
  'genre': 'latin',
  'year': 2002},
 {'id': '4UzbnrVB4sKrYxlWRGNzBR',
  'artist_name': 'Merche',
  'track_name': 'El Barman',
  'genre': 'latin',
  'year': 2002},
 {'id': '4xUeb0mgEljSLJIxFXLKPF',
  'artist_name': 'Factoria X',
  'track_name': "Rewards (feat. The Moreno's)",
  'genre': 'latin',
  'year': 2002},
 {'id': '4xUeb0mgEljSLJIxFXLKPF',
  'artist_name': "The Moreno's",
  'track_name': "Rewards (feat. The Moreno's)",
  'genre': 'latin',
  'year': 2002},
 {'id': '7tX0V2ikN9Y9UNH4d3w77F',
  'artist_name': 'Sidonie',
  'track_name': 'Mode',
  'genre': 'latin',
  'year': 2002},
 {'id': '7sT8zEGhVsw85dCYP4MNUy',
  'artist_name': 'Luis Morera',
  'track_name': 'Generacion 2000',
  'genre': 'latin',
  'year': 2002},
 {'id': '4UmOcKAtCNjlDFtHcxWcvh',
  'artist_name': 'Toy Soldiers',
  'track_name': 'Popcorn',
  'genre': 'latin',
  'year': 2002},
 {'id': '5OsJWplppfqtByGFVx49je',
  'artist_name': 'Bellepop',
  'track_name': 'La vida que va (Heart in Distress)',
  'genre': 'latin',
  'year': 2002},
 {'id': '0k9o36zHjfM2Oh79dGQTNs',
  'artist_name': 'Sidonie',
  'track_name': 'In Da Sun',
  'genre': 'latin',
  'year': 2002},
 {'id': '2o4osHcCkrkaVFZ4d0i7rL',
  'artist_name': 'Bellepop',
  'track_name': 'Paraíso (Paradise)',
  'genre': 'latin',
  'year': 2002},
 {'id': '5YQZJha9tq0pF9E7zCPJd4',
  'artist_name': 'Dover',
  'track_name': 'The Flame',
  'genre': 'latin',
  'year': 2003},
 {'id': '5oz2AGkudJ4st3CaBz5Toa',
  'artist_name': 'Melody',
  'track_name': 'Será',
  'genre': 'latin',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': 'H.A.W.K.',
  'track_name': 'Freestyle',
  'genre': 'latin',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': "Lil' Head",
  'track_name': 'Freestyle',
  'genre': 'latin',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': 'Kevo',
  'track_name': 'Freestyle',
  'genre': 'latin',
  'year': 2003},
 {'id': '7tbS96G0V7WMTxopfpe0nH',
  'artist_name': 'Dj David Max',
  'track_name': 'News 2003 - La Gaita Hard Mix',
  'genre': 'latin',
  'year': 2003},
 {'id': '6ciXx0fgkmAnaiX3iv9Hjd',
  'artist_name': 'Papas Fritas',
  'track_name': 'Way You Walk',
  'genre': 'latin',
  'year': 2003},
 {'id': '3X9e9mQzcQD15VlIkDnLKv',
  'artist_name': 'Saturn DJ',
  'track_name': 'Take Me 2003',
  'genre': 'latin',
  'year': 2003},
 {'id': '3VVnAoNIHeTG8TYLxMymnv',
  'artist_name': 'Melody',
  'track_name': 'Será',
  'genre': 'latin',
  'year': 2003},
 {'id': '74lY6ixYn1cHqacjoBPSD2',
  'artist_name': 'Revolver',
  'track_name': 'Fuera de lugar (feat. José Manuel Casañ)',
  'genre': 'latin',
  'year': 2003},
 {'id': '74lY6ixYn1cHqacjoBPSD2',
  'artist_name': 'Jose Manuel Casañ',
  'track_name': 'Fuera de lugar (feat. José Manuel Casañ)',
  'genre': 'latin',
  'year': 2003},
 {'id': '5IrU3wUKCbAjDxKjgdQfpm',
  'artist_name': 'Deluxe',
  'track_name': 'It Could Have Been My Mirror',
  'genre': 'latin',
  'year': 2003},
 {'id': '5qbrqNka0MDjGAA00iTII6',
  'artist_name': 'Deluxe',
  'track_name': 'Hey Brother!',
  'genre': 'latin',
  'year': 2003},
 {'id': '3zGzzKCLu6EDWVSldHivxu',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Skokian',
  'genre': 'latin',
  'year': 2004},
 {'id': '7abWn4FXEvAhlLtIchWX0X',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Cerezo Rosa',
  'genre': 'latin',
  'year': 2004},
 {'id': '3bgItdWfQfkG8xE1OEBIQm',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Mambo en Sax',
  'genre': 'latin',
  'year': 2004},
 {'id': '4Jd8st6f7YT8cWCu4rfUl3',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Guadalajara',
  'genre': 'latin',
  'year': 2004},
 {'id': '54nFeLRjuLsTO1V2nBNBda',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Concierto para Bongo',
  'genre': 'latin',
  'year': 2004},
 {'id': '3zg5CC8Njjv51gU9BkyeJj',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Patricia',
  'genre': 'latin',
  'year': 2004},
 {'id': '6QYSVloTcuUUbgLSkyNbZi',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Ni Hablar',
  'genre': 'latin',
  'year': 2004},
 {'id': '2AWrydr4ZvpRRxKG1hdMtC',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Mambo en Trompeta',
  'genre': 'latin',
  'year': 2004},
 {'id': '0qwoeKL8Lr9henafAPmWQH',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Park Avenue Mambo',
  'genre': 'latin',
  'year': 2004},
 {'id': '485Ym99WPK9AnQfrdavTGF',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Mambo #5',
  'genre': 'latin',
  'year': 2004},
 {'id': '30VdK5HCUxmfFnxBUs3ZKn',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo Mania',
  'genre': 'latin',
  'year': 2004},
 {'id': '4BVKxdPXqi5BxiIm1HTB6p',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo No.5',
  'genre': 'latin',
  'year': 2004},
 {'id': '58uwbL5DgZbr8dnViTGeVw',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Mambo 8',
  'genre': 'latin',
  'year': 2004},
 {'id': '0bcE645A9OKeIINxcpHrtr',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Pianolo',
  'genre': 'latin',
  'year': 2004},
 {'id': '75V6PU5qDIe0Qboc0zmBey',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Mary Dungue',
  'genre': 'latin',
  'year': 2004},
 {'id': '3fi6iRg9CzqwlPoYkg3ORW',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Cose, Cose, Cose',
  'genre': 'latin',
  'year': 2004},
 {'id': '5fwU1gFY2n2d7020R2Pzom',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Que Rico Mambo',
  'genre': 'latin',
  'year': 2004},
 {'id': '4u75RzElHXjnoWU1WgScuX',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Al Compas del Mambo',
  'genre': 'latin',
  'year': 2004},
 {'id': '5oPMlaCPFqRSsuwc3JPhmP',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'La Niña Popof',
  'genre': 'latin',
  'year': 2004},
 {'id': '4ufHuDO722ddEqx9horHXG',
  'artist_name': 'The Mambo All Stars Orchestra',
  'track_name': 'Bonito Y Sabroso',
  'genre': 'latin',
  'year': 2004},
 {'id': '4KS151YPj3MNNSXvB7OqLa',
  'artist_name': 'Ruben Ramos',
  'track_name': 'Thirteen Years',
  'genre': 'latin',
  'year': 2004},
 {'id': '38z0tDFKUURu2iz8IXYPh7',
  'artist_name': 'Jamband',
  'track_name': 'Redman (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '2NyS5zAYQFkRVREOkLYohd',
  'artist_name': 'Jamband',
  'track_name': 'Yessi (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '2TZ63DAuzYmZVwzvdLzI2s',
  'artist_name': 'Jamband',
  'track_name': 'Crowd Ah People (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '17YOPI4nUkFkiwW8xcNev1',
  'artist_name': 'Cal Tjader',
  'track_name': 'Linda Chicana',
  'genre': 'latin',
  'year': 2004},
 {'id': '75Vk1xw3X86erwnOp0UecK',
  'artist_name': 'Jamband',
  'track_name': 'Session Mus Irie 50 Years in the Bvi (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '4lS0onDdHpdvk46WUbwbz7',
  'artist_name': 'The Treniers',
  'track_name': "Devil's Mambo - 78rpm Version",
  'genre': 'latin',
  'year': 2004},
 {'id': '0zDbuSCBrDJoeWQX376Ppq',
  'artist_name': 'Cal Tjader',
  'track_name': 'Speak Low',
  'genre': 'latin',
  'year': 2004},
 {'id': '7KQYObTopYOSJrFZePskvr',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Anything Can Happen-Mambo',
  'genre': 'latin',
  'year': 2004},
 {'id': '7KQYObTopYOSJrFZePskvr',
  'artist_name': 'Abbe Lane',
  'track_name': 'Anything Can Happen-Mambo',
  'genre': 'latin',
  'year': 2004},
 {'id': '52DqJWkR7OwZNJJQvgwhzV',
  'artist_name': 'Jamband',
  'track_name': 'Para Ah You (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '7lfMwwQgnNXGLsZcGFe1wu',
  'artist_name': 'Jamband',
  'track_name': 'Big Car Show (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '3LVeDKGh2VB4FZn2uSaARu',
  'artist_name': 'Jamband',
  'track_name': 'No Fraid Dem (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '2Ute3FoOMCtAyir8ou9mTP',
  'artist_name': 'Jamband',
  'track_name': 'All True Jamband Soldiers (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '2TVeeSLXclMEi4ClAJ5M60',
  'artist_name': 'Jamband',
  'track_name': 'Deh Music Exciting (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '0tzXx1CSOzM1gGTjiqH5FA',
  'artist_name': 'Jamband',
  'track_name': 'Crowd a People (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '2acMfrIVrR6434BbFNgNcD',
  'artist_name': 'Jamband',
  'track_name': 'You Know What I Wanna See (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '7CAwv9EfExHwBGC9N8ssIy',
  'artist_name': 'Jamband',
  'track_name': 'Music from the Vi (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '61gBEHEt0rdhgahK2ISoWY',
  'artist_name': 'Jamband',
  'track_name': 'Yuh Waist (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '6ViuY5lhrTs57vr8EZKKfE',
  'artist_name': 'Jamband',
  'track_name': 'Everybody in the Village (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '0K2sbXKDDGGXgDbRub6rea',
  'artist_name': 'Jamband',
  'track_name': 'Lala Lala (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '7p7Ikkey7BpbDryxidA3Kh',
  'artist_name': 'Jamband',
  'track_name': 'Ben Down Lo Riddim (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '0vhVUt4nr516qA6nkaxPKJ',
  'artist_name': 'Jamband',
  'track_name': 'Wait for Me (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '1PMe9QOs22zvYcvV36Hr1z',
  'artist_name': 'Jamband',
  'track_name': 'Yeah Yeah Yeah Yeah (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '6VTGiOlkw3kQ8znslyKNYD',
  'artist_name': 'Jamband',
  'track_name': 'Get Your Groove on (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '3RcZ8otRLuxOyo0Uu5s67p',
  'artist_name': 'Jamband',
  'track_name': 'And the Beat Goes on (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '3C7hhWWAhVYylYet8PJ87u',
  'artist_name': 'Jamband',
  'track_name': 'Party Start Now (Live',
  'genre': 'latin',
  'year': 2004},
 {'id': '3dWQN1Q61IJ18brhZxd9kJ',
  'artist_name': 'Jamband',
  'track_name': 'Yuh Getting Pay (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '5lsxKY3KyluQmqSkkMGZ4L',
  'artist_name': 'Jamband',
  'track_name': 'Give Me My Bass Line Now (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '3qOjdDY2eI8If0Vgx2qhIj',
  'artist_name': 'Jamband',
  'track_name': 'Tempreture Rising (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '4im1aGIbTLBEAG7zxMBAns',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'La Nubes',
  'genre': 'latin',
  'year': 2004},
 {'id': '2ycwQf0ZeIAAmmEMH3Ux63',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Un Puno De Tierra',
  'genre': 'latin',
  'year': 2004},
 {'id': '6C1jRnjEy1NwzhsdowiLbA',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Este Amor Que Tengo',
  'genre': 'latin',
  'year': 2004},
 {'id': '015cEVa6swnQviLe0cR3L2',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Cumbia Del Sol',
  'genre': 'latin',
  'year': 2004},
 {'id': '11fMRJBe65Zp3aaZA7uOEH',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'In My House',
  'genre': 'latin',
  'year': 2004},
 {'id': '6S7YZFUpYfJYixDu1oWlhO',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'La Luna',
  'genre': 'latin',
  'year': 2004},
 {'id': '6vmQLduQ0RhbxW32FDJA5o',
  'artist_name': 'Jamband',
  'track_name': 'Wuk up Harder (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '0BkGu0hrI3vqoMy0wNRvp8',
  'artist_name': 'Jamband',
  'track_name': 'Jouvert Shirts from Myron (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '3Lqv29lmwfWfNcLPqbALEM',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Dos Hojas Sin Rumbo',
  'genre': 'latin',
  'year': 2004},
 {'id': '407SZzyW1w7MqhnbKy5oZv',
  'artist_name': 'Jamband',
  'track_name': 'Happy Birthday Pretta (Live)',
  'genre': 'latin',
  'year': 2004},
 {'id': '6ZJefFLPWtajHtRIprh9zC',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Wasted Days, Wasted Nights',
  'genre': 'latin',
  'year': 2004},
 {'id': '14Dyw1Mw0CjFP0MCU7ZScp',
  'artist_name': 'Tango For 3',
  'track_name': 'Milonga Del Angel',
  'genre': 'latin',
  'year': 2004},
 {'id': '5Svf7RNq61feLxcKcipACY',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Volver Volver',
  'genre': 'latin',
  'year': 2004},
 {'id': '00j6vfAr60Lx2HZQ0jdfXF',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Cartas Marcadas',
  'genre': 'latin',
  'year': 2004},
 {'id': '6emFKXn9lb2JpJu016KXLt',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'La Puerta Negra',
  'genre': 'latin',
  'year': 2004},
 {'id': '6lrABF30wkwmbyvMO7Rvu4',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Via El Valle',
  'genre': 'latin',
  'year': 2004},
 {'id': '4YqV6cVpisuIKYzatvgzWc',
  'artist_name': 'Crooked Stilo',
  'track_name': 'Naturally Crooked',
  'genre': 'latin',
  'year': 2004},
 {'id': '2pLoO3raJFR7zWdepdzDqW',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Sabor A Mi',
  'genre': 'latin',
  'year': 2004},
 {'id': '0ksYlVNYmtYLf6CIhrdo3P',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'No Me Queda Mas',
  'genre': 'latin',
  'year': 2004},
 {'id': '6FHXGuCG0PURSmARs4AyMc',
  'artist_name': 'Jay And The Latin Sounds',
  'track_name': 'Un Rinconcito En El Cielo',
  'genre': 'latin',
  'year': 2004},
 {'id': '0k14MPzBf1HM9YMjvvUgJ4',
  'artist_name': 'Krosfyah',
  'track_name': 'Keep Rolling It',
  'genre': 'latin',
  'year': 2004},
 {'id': '0k14MPzBf1HM9YMjvvUgJ4',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Keep Rolling It',
  'genre': 'latin',
  'year': 2004},
 {'id': '0AKF7UpCRXvO5NgkfSNKc3',
  'artist_name': 'Krosfyah',
  'track_name': 'Keep Rolling It - Raw',
  'genre': 'latin',
  'year': 2004},
 {'id': '0AKF7UpCRXvO5NgkfSNKc3',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Keep Rolling It - Raw',
  'genre': 'latin',
  'year': 2004},
 {'id': '7wfTQsy2Cp0yjOuoNpwTYU',
  'artist_name': 'Krosfyah Feat. Edwin Yearwood',
  'track_name': 'French Kiss',
  'genre': 'latin',
  'year': 2004},
 {'id': '4H7EZETK2oIjNwpQzVeSL9',
  'artist_name': 'Krosfyah',
  'track_name': 'All Is Mine',
  'genre': 'latin',
  'year': 2004},
 {'id': '4H7EZETK2oIjNwpQzVeSL9',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'All Is Mine',
  'genre': 'latin',
  'year': 2004},
 {'id': '5jgrjVA7kA6Zr5zMFHAC3m',
  'artist_name': 'Krosfyah',
  'track_name': 'Sugar Cane - Road Mix',
  'genre': 'latin',
  'year': 2004},
 {'id': '5jgrjVA7kA6Zr5zMFHAC3m',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Sugar Cane - Road Mix',
  'genre': 'latin',
  'year': 2004},
 {'id': '1TpdbQiVcDcFRkr9ScJdxe',
  'artist_name': 'Krosfyah',
  'track_name': 'Invasion',
  'genre': 'latin',
  'year': 2004},
 {'id': '1TpdbQiVcDcFRkr9ScJdxe',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Invasion',
  'genre': 'latin',
  'year': 2004},
 {'id': '45xT78itKUbIJLhGljlI7g',
  'artist_name': 'Krosfyah',
  'track_name': 'Sugar Cane',
  'genre': 'latin',
  'year': 2004},
 {'id': '45xT78itKUbIJLhGljlI7g',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Sugar Cane',
  'genre': 'latin',
  'year': 2004},
 {'id': '55OwnW95xqA5cIDXMKAib9',
  'artist_name': 'Stavros Kapsalis',
  'track_name': 'Liaskovikiariko',
  'genre': 'latin',
  'year': 2004},
 {'id': '6P7bC48BsaqweODyenFpzA',
  'artist_name': 'Krosfyah',
  'track_name': 'Holes',
  'genre': 'latin',
  'year': 2004},
 {'id': '6P7bC48BsaqweODyenFpzA',
  'artist_name': 'Edwin Yearwood',
  'track_name': 'Holes',
  'genre': 'latin',
  'year': 2004},
 {'id': '2mWt70c5q39CcU0n1bpdCz',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Donde Estabas Tú',
  'genre': 'latin',
  'year': 2004},
 {'id': '59sG98RKeK2MxCez2hY2eQ',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Carnival in Uruguay',
  'genre': 'latin',
  'year': 2004},
 {'id': '2yd5ctdrdvi6QU3kVUtzxp',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Flute Nightmare',
  'genre': 'latin',
  'year': 2004},
 {'id': '7fTj6qbZFhUauwyM1uZzS3',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo Gallego',
  'genre': 'latin',
  'year': 2004},
 {'id': '5EPndW1j8gdgDXRi6L7jGo',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo Retozón',
  'genre': 'latin',
  'year': 2004},
 {'id': '7xvYezyqQlM2rgfASffqG4',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo Gordo',
  'genre': 'latin',
  'year': 2004},
 {'id': '7Duw4J2m0DDtbjp6kLQuAQ',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Mambo Gitano',
  'genre': 'latin',
  'year': 2004},
 {'id': '6UF3jmhT7ciDlcl9nGsVJy',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Cerezo Rosa Y Manzano Blanco',
  'genre': 'latin',
  'year': 2004},
 {'id': '4Cg4NDXrby5FyJeLY0Nwlo',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Uuuh!',
  'genre': 'latin',
  'year': 2004},
 {'id': '6RPxHOiflPzjscVNbFmHrg',
  'artist_name': 'Xavier Cugat',
  'track_name': 'Africano Soy',
  'genre': 'latin',

In [12]:
#creo variables para pasar cada archivo por años
latin_2018=[]
latin_2019=[]
latin_2020=[]
latin_2021=[]
latin_2022=[]

# lo meto por un bucle for para iterar por el 

for archivo in archivos_latin:

    año_del_archivo = archivo['year']

    if año_del_archivo == 2018:
            latin_2018.append(archivo)

    elif año_del_archivo == 2019:
            latin_2019.append(archivo)

    elif año_del_archivo == 2020:
            latin_2020.append(archivo)

    elif año_del_archivo == 2021:
            latin_2021.append(archivo)

    elif año_del_archivo == 2022:
            latin_2022.append(archivo)

# Ahora puedes ver cuántos hay en cada una

print(f"En 2018 hay {len(latin_2018)} archivos latin.")
 
print(f"En 2019 hay {len(latin_2019)} archivos latin.")
print(f"En 2020 hay {len(latin_2020)} archivos latin.")
print(f"En 2021 hay {len(latin_2021)} archivos latin.")
print(f"En 2022 hay {len(latin_2022)} archivos latin.")

En 2018 hay 476 archivos latin.
En 2019 hay 520 archivos latin.
En 2020 hay 446 archivos latin.
En 2021 hay 372 archivos latin.
En 2022 hay 388 archivos latin.

In [ ]:
##una vez tengo esto si quiero guardar este json.poop??

In [ ]:
with open("Files/archivo.json") as archivo_json:
    fuente_json = json.load(archivo_json)

In [13]:
artistas_unicos = sorted({ #Creamos un set (colección de elementos únicos, sin duplicados) y le ponemos un sorted porque los sets no tienen orden.
    elemento["artist_name"]
    for elemento in fuente_json #Recorre cada elemento de nuestro JSON (cada canción).
    if 2018 <= elemento["year"] <= 2022 and elemento["genre"].lower() == "latin" # Filtra solo las canciones cuyo año esté entre 2018 y 2022.Nos aseguramos de que asegura que solo se consideren elementos(canciones) de pop, sin importar mayúsculas/minúsculas
})

print("Artistas únicos de latin entre 2018 y 2022:")
for artista in artistas_unicos:
    print(artista)

Artistas únicos de latin entre 2018 y 2022:
$kyhook
3AM
6ix9ine
ABHIR
ABRA
Abraham Mateo
Aitana
Alberdi
Alejo
Alex Gargolas
Alex Goot
Alex Rose
Almighty
Alvaro Diaz
Alvaro Soler
Alzate
Amenazzy
Ana Mena
Andy Rivera
Anne-Marie
Antonio Banderas
Antonio José
Anuel
Anuel AA
Arcángel
Asan
Atomic Otro Way
Aventura
B-Case
BEJO
BM
Baby Rasta
Bad Bunny
Bad Gyal
Bad Milk
Bandaga
Bardero$
Bassy
Beatriz Luengo
Bebe
Becky G
Belinda
Beny Jr
Beret
Beéle
Big Soto
Billie Eilish
Billy Chester
Biwan La Pauta
Bizarrap
Blessd
BlueFire
Bomba Estéreo
Boricua Boys
Boy Wonder CF
Boza
Brray
Bruno Romano
Bryant Myers
Brytiago
Bujan
Buscabulla
Busy Signal
C de Cama
C. Tangana
C.R.O
CJ
CNCO
Cadenza
Caleb Calloway
Cam Steady
Came Beats
Camilo
Camin
Cano
Cardi B
Carlitos Rossy
Carly
Carín León
Casper Magico
Cauty
Cazzu
Ceky Viciny
Celebration Guns
Chael Produciendo
Chanell
Chema Rivas
Chencho Corleone
Chiki El De La Vaina
Chimbala
Chris Brown
Chris Jedi
Chris Lebron
Chris Viz
Christian Daniel
Christian Nodal
Cojo Crazy
Coqeéin Montana
Corina Smith
Cosculluela
Costa
Cotorra Music Grup
Cris MJ
Cruz Cafuné
Cumbiafrica
Cyril Kamer
D' La Crem
DELLAFUENTE
DICC
DJ Conds
DJ Luian
DJ Nelson
DJ Pablito
DJ Pana
DJ Premier
DJ Snake
Daddy Yankee
Dalex
Dalmata
Danny Ocean
Darell
Darkiel
Darío Gómez
David Marley
Daviles de Novelda
Dayme y El High
Dayvi
De La Ghetto
De La Rose
Dei V
Demi Lovato
Descemer Bueno
Dinamarca
Diplo
Doc Psych
Doja Cat
Don Miguelo
Don Omar
Don Patricio
Drago200
Drake
Dua Lipa
Dubbel Dutch
Duki
Duncan Dhu
Dylan Fuentes
Dímelo Flow
ECKO
EL IMA
ELENA ROSE
Earthadox
Eddie Dee
Eddie Santiago
Eduarny Morales
Eix
El Alfa
El Bobe
El Charrito Negro
El Chaval de la Bachata
El Cherry Scom
El Chuky De Lewa
El Completo Rd
El Conejo
El Daddy
El Guincho
El Kanka
El Perla
El Taiger
El Yman
Eladio Carrion
Ele A
Ele A El Dominio
Elilluminari
Elisabeth Roma
Eloy
Emilia
Enrique Iglesias
Evaluna Montaner
Fabbio
Fakeguido
Famous
Farruko
Fat Dolsk
Feid
Felino Brown
Fito la R
Flow La Movie
FlowZeta
Floyd
Foking
Foreign Teck
Fred De Palma
Freshy Kanal
Fresto Music
Fuego
Funk.Shu
GARABATTO
GIMS
Gaby Music
Galvan Real
Gangster Bunny
Gigolo Y La Exce
Gloosito
Gote
Grupo Niche
Guaynaa
Guitarricadelafuente
HUGEL
Harry Nach
Haze
Homer El Mero Mero
Hydro
ICON
Invadable Harmony
Ir Sais
Irrita el Indio
Israel B
J Balvin
J-Xtreme
JC Reyes
JC el Diamante
JHAYCO
Jada Facer
Jamby El Favo
Jarabe De Palo
Javiielo
Jay Menez
Jay Wheeler
Jedis
Jenny "La Sexy Voz"
Jerry Di
Jessi Uribe
Jey Blessing
Jhon Alex Castaño
Jhonny Rivera
Joaquín Sabina
Joel Santos
Joey Montana
John Doe The First
John Pollõn
Jon Z
Jone Quest
Joniel
Joost
Jorge Drexler
Jossef
Jowell
Jowell & Randy
Joycee
Juacko
Juan Magán
Juanka
Juhn
Julianno Sosa
Julieta Venegas
Juseph
Justin Quiles
KAROL G
KEVIN ROLDAN
KEVVO
KHEA
KREAM
Kabasaki
Kafu Banton
Kaio Viana
Karetta el Gucci
Kasher Quon
Kaydy Cain
Keen Levy
Kelly Ruíz
Kenai
Kendo Kaponi
Kevin Kaarl
Kevin Krust
Khaled
Kidd Keo
Kikimoteleba
Kiko Rodriguez
Killatonez
Kion Studio
Kiubbah Malon
Kurt Hugo Schneider
L-Gante
LAGOS
LATIN MAFIA
LIT killah
LZYXLR
La Decada Prodigiosa
La Factoria
La Fortaleza Real
La Húngara
La Insuperable
La Nueva Escuela
La Pantera
La Secta
La Suprema Corte
La Zowi
La mano de oro
Lalo Ebratt
Lary Over
Leby
Leebrian
Leiva
Lele Pons
Lenny Santos
Lenny Tavárez
Lenuel
Leo Rizzi
Leoni Torres
Leslie Grace
LiL CaKe
Liderj
Linton
Lirico En La Casa
Lola Indigo
Los 40
Los Fantastikos
Los G4
Los Legendarios
Los Lobos
Los del Control
Los Ángeles Azules
Luar La L
Lucho RK
Lucho SSJ
Luis Alberto Posada
Luis Figueroa
Luis Fonsi
Lunay
Lyanno
Lérica
MC Bin Laden
MC CJ
MYGAL
Maffio
Maikel Delacalle
Major Lazer
Maka
Mala Rodríguez
Maluma
Mama Dousha
Mambo Kingz
Manuel Medrano
Manuel Turizo
Marc Anthony
Marc Seguí
Marciano Cantero
Marcianos Crew
Maria Becerra
Mariah Angeliq
Mat4yo
Mathew
Mau y Ricky
Mdmoney
Melody
Micro TDH
Migrantes
Mike Morato
Miky Woodz
Milo j
Moncho Chavea
Mora
Morad
Morat
Mozart La Para
Mr Eazi
Mr. Naisgai
Musicologo The Libro
Myke Towers
NATHY PELUSO
NATTI NATASHA
NOREH
Nacho
Naim
Nanpa Básico
Natalia Lafourcade
Natos y Waor
Nego do Borel
Neo Pistea
Neutro Shorty
Nicki Minaj
Nicki Nicole
Nicky Jam
Nico Valdi
Nio Garcia
Niño de Elche
Nolep
Noriel
Nyno Vargas
Obie Wanshot
Offset
Oken
Omar Courtz
Omar Montes
Omar Varela
Omega
Original Elias
Oscar el Ruso
Ovy On The Drums
Ozuna
PMP
Pablo Chill-E
Pablo Mas
Pailita
Paloma Mami
Paul Marmota
Paul Sonoria
Paulo Londra
Pedro Calderon
Pedro Capó
Pepe y Vizio
Phontana
Pipe Bueno
Pipo Beatz
Piso 21
Pj Sin Suela
Plan B
Playa Cuberris
Pol Granch
Polimá Westcoast
Prince Royce
Princesa Alba
Ptazeta
Pure Negga
Pyllo Cortes
Quevedo
ROBI
ROSALÍA
Rafa Pabön
Raffa Fl
Ralphie Choo
Randy Nota Loca
Rasel
Raul Clyde
Rauw Alejandro
Rei
Reik
Rels B
Rema
Residente
Revol
Rich Music LTD
Rios
Rita Payés
RobGz
Robert Hesser
Roberto Ferrante
Rocco Hunt
Rochy RD
Rokero
Romeo Santos
Rusherking
Rvfv
Rvssian
Ryan Castro
SAIKO
SHARIF RAFAEL
Sammy Baby
Santa Fe Klan
Scarlett Miller
Scotty DK
Sean Paul
Sebastian Yatra
Sech
Secreto "El Famoso Biberon"
Selena Gomez
Sen Senra
Shadow Blow
Shaggy
Shakira
Shelow Shaq
Sia
Sick Luke
Skillz Beatz
Skrillex
Sky Rompiendo
Snova
Snow
Soben
Soge Culebra
Soto Asa
Spice
Spiff TV
Standly
Stars Music Chile
Stefflon Don
Steve Lean
Sticky M.A.
Super Yei
Tainy
Taiu
Tapia El Sikario
Taxi
Teejayx6
Tego Calderón
Tempo
The Marías
The Tyets
The Weeknd
Thiago Muller
Tiago PZK
Tito Nieves
Tokischa
Tony Dize
Tory Lanez
Totoy El Frio
Trap Capos
Travis Scott
Trueno
Tyga
Unorthodocks
Uzii Gaang
Verónica Romero
Victor Cardenas
Villano Antillano
Viti Ruiz
Waste
Wesh Music
Will Smith
Willy William
Wisin
Wisin & Yandel
Wiso Rivera
Xules
YOVNGCHIMI
YSY A
Yami Safdie
Yan Block
Yandar & Yostin
Yandel
Yannc
Yaviah
Yeison Jimenez
Yiyo Sarante
Yotuel
Young Vene
Yung Beef
Zion
Zion & Lennox
ajan
integrityoficial
l0rna
lil eli young bapestah
o2 Tbb
paopao
rusowsky
shattered
tatool
Çantamarta
Íñigo Quintero
Ñejo
Ñengo Flow

In [14]:
# Guardar en un archivo JSON - #Guardamos minijson_pop


with open("artistas_latin_2018_2022.json", "w", encoding="utf-8") as minijson_latin: #utf-8 asegura que los caracteres especiales (como acentos) se guarden correctamente
    json.dump(artistas_unicos, minijson_latin, ensure_ascii=False, indent=4) #ensure_ascii=False permite que el JSON guarde los caracteres especiales correctamente en su forma natural(tildes,ñ etc)indent :Cada elemento está en su propia línea y sangrado con 4 espacios

Tenemos un minijson del Json definitivo_spoty que tiene una lista con los artistas unicos durante los años 18-22