In [1]:
import json
import pandas as pd
import requests

In [2]:
#primero voy a abrir el archivo json, definitivo.json
with open('Files/definitivo.json', 'r') as archivo_json:
    fuente_json = json.load(archivo_json)

In [3]:
type(fuente_json)

list

In [4]:
fuente_json

[{'id': '7AlYBA5M9FVXDqN31cbExE',
  'artist_name': 'Remedios Amaya',
  'track_name': 'El zarandeo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4uqcES2h19TKAXQlciycrO',
  'artist_name': 'Nobuo Uematsu',
  'track_name': "Vamo'alla flamenco",
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0z6xGK2u3nSsbk9XeKYwZQ',
  'artist_name': 'Maurice Ravel',
  'track_name': 'Flamenco Bolero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6DjfWx0fXi0uQpedpvaCD9',
  'artist_name': 'Mark Towns',
  'track_name': 'After the Rain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1t91qQaPbOoo4pumaLih4W',
  'artist_name': 'Franz Schubert',
  'track_name': 'Tango Serenata (Ständchen)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7Kuasu0H7jArcADoFIHGUk',
  'artist_name': 'Mark Towns',
  'track_name': 'Corriente',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '02jM23k8pgm9gcZpyIn8Wk',
  'artist_name': 'Georges Moustaki',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2tnnbPGlhpY1420firAE7v',
  'artist_name': 'El Arrebato',
  'track_name': 'Rumba Canalla',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5OFZgm7YRtEHkoUdgIdMhF',
  'artist_name': 'Mark Towns',
  'track_name': 'Medley: The Way/La Via',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3dVVMsZCVGxce42Nd9a0XC',
  'artist_name': 'Tomaso Albinoni',
  'track_name': 'Tango Adagio',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4EOgdSxqtZZGvOrzuyQAGz',
  'artist_name': 'Johann Pachelbel',
  'track_name': 'Soleá Canon',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73KHkT0m5CW2xWgJAxCmoA',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, con baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1xikd54XPRJeJwRIv0yIzO',
  'artist_name': 'Mark Towns',
  'track_name': 'Sabrosa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0sKS1f30oQdGw903RR7fBN',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2eLniDU3Fbg6QUTbreLUrF',
  'artist_name': 'Márquez El Zapatero',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo de Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77242gtA1Jymsu2Vl9LGxR',
  'artist_name': 'Rocio Ruiz',
  'track_name': 'Flamenco,Cante por Martinete',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5YKBLRuQrbRDyrJaH7nywI',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, sin baile',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6mpQYMq1l1gU0ltQ0nO1IW',
  'artist_name': 'Antonio Vivaldi',
  'track_name': 'Primavera Tango (Four Seasons)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5pG5LCEvPX175P4ukUCFmR',
  'artist_name': 'La Carmen',
  'track_name': 'Flamencos a volar',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5qhcnvZmA4lm7fClwUbGwB',
  'artist_name': 'Enaldo Barrera',
  'track_name': 'Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XNVIE3jSJUoGzehQN9m9g',
  'artist_name': 'Chano Lobato',
  'track_name': 'Tanguillos de Cádiz',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6Nm0bBmYBI74CyApeaVZhF',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Rumba Allegro (Symphony no.40)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2L2ObU16rqwFvOIfbseBLX',
  'artist_name': 'Chiqui de Jerez',
  'track_name': 'El Teléfono de Mi Casa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2w6JLw4LmLEl57uUKhRldQ',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 190',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2edeklaJKKKx9ZyxDD2bSG',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Moonlight Rumba (Moonlight Sonata)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '71AKM5R1HijC743bGDWJBy',
  'artist_name': 'Mark Towns',
  'track_name': 'Merengue Gitano',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6dOwfELGupyrMHzkVegViT',
  'artist_name': 'Mark Towns',
  'track_name': 'Selva Urbana',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MJgtHcv1Wjv4Wxc9nJATo',
  'artist_name': 'Johann Sebastian Bach',
  'track_name': 'Tango Aria (Air on the G String)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2zEhscbOlOC6Bl6OVcWfL1',
  'artist_name': 'Juana Amaya',
  'track_name': 'Flamenco, Soleá por Bulerias, Sólo Compás 132',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6l2HTLRp8mTasMXOtvFEhb',
  'artist_name': 'Mark Towns',
  'track_name': 'Chucho',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5PGy4rzoVYQwMTfa4Svvgr',
  'artist_name': 'Levantito',
  'track_name': 'El Jardín de Mis Sueños',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5xA7tKg7QPsvAUVWap88rN',
  'artist_name': 'Ludwig van Beethoven',
  'track_name': 'Fandango for Elise (Für Elise)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1OkfxOngQIpLS7atBmCQSQ',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Media (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3QnvDtqgg8KGq8QypBbsv0',
  'artist_name': 'Dorantes',
  'track_name': 'Orobroy',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1XvJsSuXS1iZxlpYojYj0W',
  'artist_name': 'Felix Mendelssohn',
  'track_name': 'Andante Rumba (Symphony 5)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZfMZkSi4itskqn6PNNBAc',
  'artist_name': 'El Trini',
  'track_name': 'Sevillanas: Rápida (Cante y Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1AaqOJEurORS9gIjdeEHTD',
  'artist_name': 'Mark Towns',
  'track_name': 'Wondering',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0R3lPDIKv89qWEmYWTIoNE',
  'artist_name': 'Wolfgang Amadeus Mozart',
  'track_name': 'Bulería Adagio (Piano Concerto No.21)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1CVS0YLa7YpB4wRIQYiJPf',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 225',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ro8lFaoIHAv2chG3hq4xg',
  'artist_name': 'La Macanita',
  'track_name': 'Cantiñas del Marinero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5zNOlWjHpmZymXQ7jvxq1T',
  'artist_name': 'Mark Towns',
  'track_name': 'Like the Wind',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55fV0QtDYtaLfB3aTID6RF',
  'artist_name': 'Mark Towns',
  'track_name': 'Wind on the Mountain',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cH2C7YxjpZQ7yhEwjs2AW',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos con baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '14mstquH2GHwuYmVp9qL1y',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Granaina: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5GW7kNyJpij82MhhnkIqAA',
  'artist_name': 'Traditional',
  'track_name': 'Medina Azahara (Granainas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZWMF5j3taR7DESgZLq8FU',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Lentas (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0d92SBPncK0zSR6IzhXxIM',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Surrender 2 Love - 2000 Remastered',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0kruq9DXxP9Lm0PdfbYBs0',
  'artist_name': 'Pedro Campos',
  'track_name': 'Sevillanas: Rocieras Medias (Tambor y Flauta)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bZvLAST6NXKOVBOocVzPr',
  'artist_name': 'Traditional',
  'track_name': 'Acera del Rio (Soleares)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0aberAzTHOxf4XH1JeUfnK',
  'artist_name': 'Traditional',
  'track_name': 'Salobre (Malagueñas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IMAOBRpQt9NLxheodkd18',
  'artist_name': 'Chonchi Heredia',
  'track_name': 'El Camino de Mi Destino',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1ggH47au252TP4T692rE0T',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'After The Rain - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77tmRwrSvrvHEHqku7OpXT',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Barcelona Nights - 2000 Digital Remaster',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4FsDuVJo6xLs8XTbdLP49D',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Malagueña: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '32aXQMl5U8lsVqk4n12waz',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 246',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jcdqacg2QJ3GHQujEuR5H',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 260',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0Jig5Z8KciCU2QXmnCBnnc',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Media (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5jsifLClBCWoE1nlasPiZh',
  'artist_name': 'Traditional',
  'track_name': 'Los Veleros (Alegrías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2ZPVwZFwsJ9SpcyEhrEBBR',
  'artist_name': 'Traditional',
  'track_name': 'Cancion (Peteneras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6ZFNcrtjNOn9bGrlPgnvt7',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Rondeña',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '28CDw1t8f0LwNQ0X3aUrGV',
  'artist_name': 'Ana Salazar',
  'track_name': 'Tu Eres para Mi',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '16UK3SdKxsyQojGZ2Xzn7u',
  'artist_name': 'Traditional',
  'track_name': 'Solquema (Bulerías)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4JoAqRjk6ZbyYbSfTiKSVu',
  'artist_name': 'Traditional',
  'track_name': 'Mantilla y Peina (Guajiras)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2NUssxdoSQRkZYyZykmnLb',
  'artist_name': 'Mark Towns',
  'track_name': 'Salamanca',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '314x76MVwlmB76sL1VMON2',
  'artist_name': 'Grupo de María del Mar Moreno',
  'track_name': 'Tarantos sin baile flamenco completo',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '30xWhibl7o3ki0DsldxXr6',
  'artist_name': 'Jose Fernandez',
  'track_name': 'Bulerias Solo Compas flamenco 234',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6CGcj8K2ZZdPWqUbyJjxMK',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Cantes de Levante: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2qiy4xV66GJOllkMaPDD3M',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Peteneras: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4Z7Uf6yZA3Vqb0NED9c71j',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Rápida (Guitarra)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '593pSt7bzylRcc7CcsHqUK',
  'artist_name': 'El Trini',
  'track_name': 'Zambra: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0lxBV7AmHRY5uIWgR5ywtb',
  'artist_name': 'El Trini',
  'track_name': 'Fandangos Naturales: Sólo Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79wfu1liWB4PZszqmQJuEu',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Lenta (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0pPUllW2drfZeyFF50aQp7',
  'artist_name': 'Traditional',
  'track_name': 'Riomar (Fandangos de Huelva)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cr6W8t5INBKw7zSupZY8R',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Farrucas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '515ndth3zLBPv4SY6JkJEZ',
  'artist_name': 'Los Activos',
  'track_name': 'Divertimiento Callejero',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '38NCXxFi771HBggW1EC8If',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Granaína',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '77yb0X5ESIBmkVYxlRZzO5',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Soléa',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3cvP0pwydWW64Akm14VlXs',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Zambra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3ADzQCu8UnyZAnBie5bV57',
  'artist_name': 'Manuel de Angustias',
  'track_name': 'Te Tengo Que Querer',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1QESy53hSMNaiaNbmbBNuE',
  'artist_name': 'Traditional',
  'track_name': 'Claroscuro (Tangos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7oQQuYMbQBBtzSHMRKUXju',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Fandangos',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5A8FVt6fFmsXIRVIYD4iEG',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Tango - mayor y menor',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3Y2exCd1xymfuTmD9611BO',
  'artist_name': 'Ramon Montoya',
  'track_name': '"La Rosa" - Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6J7QoPhijQk8A0RLUvInFe',
  'artist_name': 'Mark Towns',
  'track_name': 'Touch',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2jSNj63K0JiyjA2q7UszKd',
  'artist_name': 'Traditional',
  'track_name': 'Las Ferialas (Sevillanas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6qZpjbbfNC8E3Efr70nIku',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Bulerías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6JTyUehuFzwzFZgCK3Wksj',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Tarantas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5UycZV2sto9vywMtNGzYYT',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Alegrías',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3nWHz7o8trM4gwRrlx8wpu',
  'artist_name': 'Traditional',
  'track_name': 'Puerto Aguila (Tientos)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5Tn3I3OYCPmZE4Adizv0HD',
  'artist_name': 'Ramon Montoya',
  'track_name': 'Minera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2FNZ1W6NQJ6i2oaS9wNvil',
  'artist_name': 'Niño Ricardo',
  'track_name': 'Seguiriyas',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4csZty0AxR9WAIWVCDLjR5',
  'artist_name': 'Traditional',
  'track_name': 'Pedregales (Serranas)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '48XjQujCABfBTZKi3j6pr9',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Santa Fe - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5bUmOYqEMPGiv3gFJ2jB30',
  'artist_name': 'El Trini',
  'track_name': 'Toná: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6IN6Zi7yjbeVK069J3QUEn',
  'artist_name': 'El Trini',
  'track_name': 'Debla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0MyvQtdefpdadVUgGm4JD4',
  'artist_name': 'Acoustic Alchemy',
  'track_name': 'The Last Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4B55Q4PWuniTmPFr1Opw2Y',
  'artist_name': '植松 伸夫',
  'track_name': 'Vamo alla Flamenco',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3yIsUXghgtMK3MuWVTsdsc',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Passing Storm - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0vqOXN6bhA4nWNjB5M5YuI',
  'artist_name': 'El Trini',
  'track_name': 'Livianas: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1uLokmb1H3AEfYM7K48DUY',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Rápida Cuatro Cuerpos (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3zLYx27eMIRdlw8xDMeIP7',
  'artist_name': 'El Trini',
  'track_name': 'Martinete: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1izTZlIOJCgHOaGJMoyr6N',
  'artist_name': 'El Trini',
  'track_name': 'Serrana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6OFw0tKxEAxkYnC5Qnfu6P',
  'artist_name': 'Victor M. Rosa',
  'track_name': 'Sevillanas: Boleras (Guitarra, Laud y Bandurria)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '0t27O9Fk0I0T1mRdJbE2Mz',
  'artist_name': 'El Trini',
  'track_name': 'Nana: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '79EWFLYoVfEUyzjNVVQIwJ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 120',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4369URVfz7QM9AwKqYz5nd',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6QshtnzwUzZsMkrPm3UkcZ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 160',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2pQ6wESsjj5mEKBAibYFat',
  'artist_name': 'El Trini',
  'track_name': 'Granaina y Media Granaina: Cante y Guitarra',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7uHQvzFgU7ViE8ES0qR3pc',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '26dXN84ePUqIHuR6e40D6E',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3lD2mjspXgh3hkIdrJuRZQ',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4caAGy3SvHorRmh9RSFFd2',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6et3COTopxtId4gCpElGaU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4s8VgVoI16ILUFVXNDFZpl',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3KHA7uGRQrft6goXandJGU',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 180',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3skYj3zKvIOXArFlT5h1aY',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 4 - 3/4 140',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '7vr6MibrK67KqENxb6WKU8',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 3 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1SRAiujmU4mmYfF3mBDHP9',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 200',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '06stEj7Zoupi6o3lOD7vfx',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 1 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2VU3v2sjK6yg98fv0mG8MU',
  'artist_name': 'Ottmar Liebert',
  'track_name': '3 Women Walking - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '3BfsufA6s2iPAmhTgmJ2HH',
  'artist_name': 'Mariló García',
  'track_name': 'Sevillanas: Media (Solo Compás)',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1oWz1iu6eyOpc5u6AGHQU1',
  'artist_name': 'El Trini',
  'track_name': 'Trilla: Cante',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '55H080ETLO2D4787FpTCHv',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 2 - 3/4 240',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '5XBXF86fIWxYLDpEzMfw8z',
  'artist_name': 'Mariló García',
  'track_name': 'Contratiempos Palmas 5 - 4/4 220',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1DzMgYzPaH4H6ugXNAfWFv',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'El Angelito',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2BLUSXzTKkp9yJ54ELJSLT',
  'artist_name': 'Ottmar Liebert',
  'track_name': '2 The Night - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '6UvU9cOu3MjWbDxiF2h3ug',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Que bonita va',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '1n1Cr82fHJ7dg1n6VPGD5V',
  'artist_name': 'Ottmar Liebert',
  'track_name': 'Moon Over Trees - Digitally Remastered 1999',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '73XZI6jT8OKrCikrK7EYK4',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Un año de espera',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '2DVp3fA4JwfYseQU9wR67W',
  'artist_name': 'Coro Flamenco de la Hermandad de la Asunción de Cantillana',
  'track_name': 'Cohetes en el aire',
  'genre': 'flamenco',
  'year': 2000},
 {'id': '4SRtBNkq160IcE1Z8zRDmG',

In [5]:
len(fuente_json)

61617

In [6]:
df_fuente_json = pd.read_json('Files/definitivo.json') 
df_fuente_json.head(1000)

,id,artist_name,track_name,genre,year
0,7AlYBA5M9FVXDqN31cbExE,Remedios Amaya,El zarandeo,flamenco,2000
1,4uqcES2h19TKAXQlciycrO,Nobuo Uematsu,Vamo'alla flamenco,flamenco,2000
2,0z6xGK2u3nSsbk9XeKYwZQ,Maurice Ravel,Flamenco Bolero,flamenco,2000
3,6DjfWx0fXi0uQpedpvaCD9,Mark Towns,After the Rain,flamenco,2000
4,1t91qQaPbOoo4pumaLih4W,Franz Schubert,Tango Serenata (Ständchen),flamenco,2000
...,...,...,...,...,...
995,0l1VmlgGHZXYL0CR27ryRz,Jo Basile,Je T'Aime Encore Plus,indie,2000
996,4rs0A9RRJy6BPR1Mq1czcZ,Guddu Rangila,Ab Naahi Sutem Kinara,indie,2000
997,57eMvbS96z94E6KzRaEOEj,Lindisfarne,Shine On,indie,2000
998,6A8Nhein0Z7Ug2Gfh08ox1,Marcos Sabino,Paz e Harmonia,indie,2000
999,3WoVUGUsSc5hvpLQnyJqRa,Ted Heath,I Like To Recognise The Tune,indie,2000

In [7]:
df_fuente_json=pd.DataFrame(fuente_json)

In [8]:
print (df_fuente_json.head())

                       id     artist_name                  track_name  \
0  7AlYBA5M9FVXDqN31cbExE  Remedios Amaya                 El zarandeo
1  4uqcES2h19TKAXQlciycrO   Nobuo Uematsu          Vamo'alla flamenco
2  0z6xGK2u3nSsbk9XeKYwZQ   Maurice Ravel             Flamenco Bolero
3  6DjfWx0fXi0uQpedpvaCD9      Mark Towns              After the Rain
4  1t91qQaPbOoo4pumaLih4W  Franz Schubert  Tango Serenata (Ständchen)

      genre  year
0  flamenco  2000
1  flamenco  2000
2  flamenco  2000
3  flamenco  2000
4  flamenco  2000

In [9]:
pd.read_json
pd.json_normalize(fuente_json)

,id,artist_name,track_name,genre,year
0,7AlYBA5M9FVXDqN31cbExE,Remedios Amaya,El zarandeo,flamenco,2000
1,4uqcES2h19TKAXQlciycrO,Nobuo Uematsu,Vamo'alla flamenco,flamenco,2000
2,0z6xGK2u3nSsbk9XeKYwZQ,Maurice Ravel,Flamenco Bolero,flamenco,2000
3,6DjfWx0fXi0uQpedpvaCD9,Mark Towns,After the Rain,flamenco,2000
4,1t91qQaPbOoo4pumaLih4W,Franz Schubert,Tango Serenata (Ständchen),flamenco,2000
...,...,...,...,...,...
61612,6Lv0uLFhPt6e4qcmoeltAq,Jade Macrae,Ain’t Nobody Home,rock,2026
61613,6Lv0uLFhPt6e4qcmoeltAq,Robben Ford,Ain’t Nobody Home,rock,2026
61614,4PtUbfBR2U2BC0uUrT9hnM,No Te Va Gustar,Todo Mal,rock,2026
61615,4PtUbfBR2U2BC0uUrT9hnM,Ciro y los Persas,Todo Mal,rock,2026
61616,762E489aCXNDuRg1sZaWmC,Artemas,time alone w u,rock,2026

In [10]:
# sacar de fuente.json todos los archivos que lleva 'pop'
archivos_rap= [] # en esta variable introduzco todos los archivos que son de genre=pop

for elemento in fuente_json:
    
    if 'rap' in elemento['genre'].lower():
        archivos_rap.append(elemento)

print(archivos_rap)

[{'id': '4FXSEdmbbeGmPIQltH27C8', 'artist_name': 'La Oreja de Van Gogh', 'track_name': 'Pop', 'genre': 'rap', 'year': 2000}, {'id': '0plPN6zr3r0vW4VA0cTlmO', 'artist_name': 'Dany Bpm', 'track_name': 'I Want to Know what Love Is', 'genre': 'rap', 'year': 2000}, {'id': '4ZFvUk3xhvofhh3rCaQbq0', 'artist_name': 'D-4-MA', 'track_name': 'The Promise', 'genre': 'rap', 'year': 2000}, {'id': '3JISoccsWqVz9KGZUK6pPX', 'artist_name': 'Enigmatik', 'track_name': 'Apache', 'genre': 'rap', 'year': 2000}, {'id': '1Hb0K8CGqKNaj2sBvvSkT7', 'artist_name': 'Nina Gordon', 'track_name': '2003', 'genre': 'rap', 'year': 2000}, {'id': '5N0cZG9UCMBMeetIPGW8G5', 'artist_name': 'Nostalgi-K', 'track_name': 'The Spirit - 2001 Remix', 'genre': 'rap', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Chenoa', 'track_name': 'Lady Marmalade', 'genre': 'rap', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Gisela', 'track_name': 'Lady Marmalade', 'genre': 'rap', 'year': 2001}, {'id': '3Z7mrMsAdiAVtmhQXkWHQV', 'artist_name': 'Verónica Romero', 'track_name': 'Lady Marmalade', 'genre': 'rap', 'year': 2001}, {'id': '0Ppu3VRq2skQDIfjcowHcZ', 'artist_name': 'NAIM', 'track_name': 'Guilty', 'genre': 'rap', 'year': 2001}, {'id': '0Ppu3VRq2skQDIfjcowHcZ', 'artist_name': 'Verónica Romero', 'track_name': 'Guilty', 'genre': 'rap', 'year': 2001}, {'id': '6eXUFbNK4uhqDsPTOKOuh0', 'artist_name': 'Naim', 'track_name': "Don't Let The Sun Go Down On Me", 'genre': 'rap', 'year': 2001}, {'id': '6eXUFbNK4uhqDsPTOKOuh0', 'artist_name': 'Alejandro Parreño', 'track_name': "Don't Let The Sun Go Down On Me", 'genre': 'rap', 'year': 2001}, {'id': '2NwBOhoA4xiJK2jmWp5FNd', 'artist_name': 'Nostalgi-K', 'track_name': 'Electricity - 2001Remix', 'genre': 'rap', 'year': 2001}, {'id': '1URps6RTulUZzTHmNmmyKW', 'artist_name': 'Technoiser', 'track_name': 'Water 2001', 'genre': 'rap', 'year': 2001}, {'id': '3FrhNoBm5cy8iuUlOUDdkJ', 'artist_name': 'DJ Ricardo', 'track_name': 'The Sound Barrier', 'genre': 'rap', 'year': 2001}, {'id': '1JbAj245mmW4GVX1ohOmLS', 'artist_name': 'Los Piratas', 'track_name': 'Gen 14', 'genre': 'rap', 'year': 2001}, {'id': '3vdxdwKTljNZPLEX7hcrMe', 'artist_name': 'TCR', 'track_name': 'P.o.p', 'genre': 'rap', 'year': 2001}, {'id': '70PRAaiRpevoPI4zbs2VGa', 'artist_name': 'X-Que, Vol. 8', 'track_name': 'When I Sleep', 'genre': 'rap', 'year': 2002}, {'id': '0sF8c858LGAUaTMPWihEvw', 'artist_name': '2002', 'track_name': 'The Sound of Still Water', 'genre': 'rap', 'year': 2002}, {'id': '3rkE8IiFy0z893ZqUzDFLk', 'artist_name': 'Tessa', 'track_name': 'Tú Volverás', 'genre': 'rap', 'year': 2002}, {'id': '5HLQc8z7BpfrNHmY0o5Ugu', 'artist_name': 'X-Que, Vol. 8', 'track_name': 'Beautiful Day - Home Version', 'genre': 'rap', 'year': 2002}, {'id': '1IudL4RSthUP5kWD0HLZUP', 'artist_name': '2002', 'track_name': 'City of Peace', 'genre': 'rap', 'year': 2002}, {'id': '4UzbnrVB4sKrYxlWRGNzBR', 'artist_name': 'Merche', 'track_name': 'El Barman', 'genre': 'rap', 'year': 2002}, {'id': '4xUeb0mgEljSLJIxFXLKPF', 'artist_name': 'Factoria X', 'track_name': "Rewards (feat. The Moreno's)", 'genre': 'rap', 'year': 2002}, {'id': '4xUeb0mgEljSLJIxFXLKPF', 'artist_name': "The Moreno's", 'track_name': "Rewards (feat. The Moreno's)", 'genre': 'rap', 'year': 2002}, {'id': '7tX0V2ikN9Y9UNH4d3w77F', 'artist_name': 'Sidonie', 'track_name': 'Mode', 'genre': 'rap', 'year': 2002}, {'id': '7sT8zEGhVsw85dCYP4MNUy', 'artist_name': 'Luis Morera', 'track_name': 'Generacion 2000', 'genre': 'rap', 'year': 2002}, {'id': '4UmOcKAtCNjlDFtHcxWcvh', 'artist_name': 'Toy Soldiers', 'track_name': 'Popcorn', 'genre': 'rap', 'year': 2002}, {'id': '5OsJWplppfqtByGFVx49je', 'artist_name': 'Bellepop', 'track_name': 'La vida que va (Heart in Distress)', 'genre': 'rap', 'year': 2002}, {'id': '0k9o36zHjfM2Oh79dGQTNs', 'artist_name': 'Sidonie', 'track_name': 'In Da Sun', 'genre': 'rap', 'year': 2002}, {'id': '2o4osHcCkrkaVFZ4d0i7rL', 'artist_name': 'Bellepop', 'track_name': 'Paraíso (Paradise)', 'genre': 'rap', 'year': 2002}, {'id': '5YQZJha9tq0pF9E7zCPJd4', 'artist_name': 'Dover', 'track_name': 'The Flame', 'genre': 'rap', 'year': 2003}, {'id': '5oz2AGkudJ4st3CaBz5Toa', 'artist_name': 'Melody', 'track_name': 'Será', 'genre': 'rap', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': 'H.A.W.K.', 'track_name': 'Freestyle', 'genre': 'rap', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': "Lil' Head", 'track_name': 'Freestyle', 'genre': 'rap', 'year': 2003}, {'id': '4rnocqCFjDi5UBzuf4Xvto', 'artist_name': 'Kevo', 'track_name': 'Freestyle', 'genre': 'rap', 'year': 2003}, {'id': '7tbS96G0V7WMTxopfpe0nH', 'artist_name': 'Dj David Max', 'track_name': 'News 2003 - La Gaita Hard Mix', 'genre': 'rap', 'year': 2003}, {'id': '6ciXx0fgkmAnaiX3iv9Hjd', 'artist_name': 'Papas Fritas', 'track_name': 'Way You Walk', 'genre': 'rap', 'year': 2003}, {'id': '3X9e9mQzcQD15VlIkDnLKv', 'artist_name': 'Saturn DJ', 'track_name': 'Take Me 2003', 'genre': 'rap', 'year': 2003}, {'id': '3VVnAoNIHeTG8TYLxMymnv', 'artist_name': 'Melody', 'track_name': 'Será', 'genre': 'rap', 'year': 2003}, {'id': '74lY6ixYn1cHqacjoBPSD2', 'artist_name': 'Revolver', 'track_name': 'Fuera de lugar (feat. José Manuel Casañ)', 'genre': 'rap', 'year': 2003}, {'id': '74lY6ixYn1cHqacjoBPSD2', 'artist_name': 'Jose Manuel Casañ', 'track_name': 'Fuera de lugar (feat. José Manuel Casañ)', 'genre': 'rap', 'year': 2003}, {'id': '5IrU3wUKCbAjDxKjgdQfpm', 'artist_name': 'Deluxe', 'track_name': 'It Could Have Been My Mirror', 'genre': 'rap', 'year': 2003}, {'id': '5qbrqNka0MDjGAA00iTII6', 'artist_name': 'Deluxe', 'track_name': 'Hey Brother!', 'genre': 'rap', 'year': 2003}, {'id': '1YksCvyydKFrisWiHj6zOI', 'artist_name': 'Beltway 8', 'track_name': 'Track 11 (Eighted & Chopped)', 'genre': 'rap', 'year': 2004}, {'id': '6DUoQwbCJLYRFkkaGmtx85', 'artist_name': 'Beltway 8', 'track_name': 'Track 3 (Eighted & Chopped)', 'genre': 'rap', 'year': 2004}, {'id': '3MB5IcaYZ2wx6uFL7OyL2f', 'artist_name': 'Naiara', 'track_name': 'Adelante', 'genre': 'rap', 'year': 2004}, {'id': '0vCx9FL3IpO9x4tcDuowcq', 'artist_name': 'Merche', 'track_name': 'Pasar De Los Demas', 'genre': 'rap', 'year': 2004}, {'id': '09ThhkdZ0awxw2MrMpJlCi', 'artist_name': '3+2', 'track_name': 'Bailando Voy', 'genre': 'rap', 'year': 2004}, {'id': '7AtoMmLJREWLdN30gOBRn6', 'artist_name': 'Marsheaux', 'track_name': 'Pop Corn', 'genre': 'rap', 'year': 2004}, {'id': '3MYqorBQjKiRYOxpLbk264', 'artist_name': 'DJ Dela', 'track_name': 'In Your Dreams 2004', 'genre': 'rap', 'year': 2004}, {'id': '3MYqorBQjKiRYOxpLbk264', 'artist_name': 'Ram J / JYD', 'track_name': 'In Your Dreams 2004', 'genre': 'rap', 'year': 2004}, {'id': '39xF0oDv6pG4CDuv8ut2u6', 'artist_name': 'Sírex', 'track_name': 'Hey Dude', 'genre': 'rap', 'year': 2004}, {'id': '0033iBCIlHfCkRMS0cRJ6F', 'artist_name': 'OG Ron C', 'track_name': 'Freestyle Eighteen', 'genre': 'rap', 'year': 2005}, {'id': '0033iBCIlHfCkRMS0cRJ6F', 'artist_name': 'Wreckin’ Yard', 'track_name': 'Freestyle Eighteen', 'genre': 'rap', 'year': 2005}, {'id': '1ga2RPfGkXxoQ5mpm9JQGw', 'artist_name': 'Jacky', 'track_name': 'My name is sex', 'genre': 'rap', 'year': 2005}, {'id': '3re5zLsF6dqTVW5A9Wn5GQ', 'artist_name': 'Mr Raw', 'track_name': 'Pretty Ugly', 'genre': 'rap', 'year': 2005}, {'id': '0aEQgxTsDwgTgmGDn9SLqH', 'artist_name': 'Doppel D', 'track_name': 'A bissl fetter', 'genre': 'rap', 'year': 2005}, {'id': '0aEQgxTsDwgTgmGDn9SLqH', 'artist_name': 'Monaco F', 'track_name': 'A bissl fetter', 'genre': 'rap', 'year': 2005}, {'id': '0aEQgxTsDwgTgmGDn9SLqH', 'artist_name': 'Grämsn', 'track_name': 'A bissl fetter', 'genre': 'rap', 'year': 2005}, {'id': '0aEQgxTsDwgTgmGDn9SLqH', 'artist_name': 'DJ Spliff', 'track_name': 'A bissl fetter', 'genre': 'rap', 'year': 2005}, {'id': '1OwMUSNhO5RNs6m8Q9yJLf', 'artist_name': 'Jacky', 'track_name': 'Mirise bol', 'genre': 'rap', 'year': 2005}, {'id': '11LakCcb49klYaz0pqC75T', 'artist_name': 'Uratsakidogi', 'track_name': 'Шпагоглотатель (Live)', 'genre': 'rap', 'year': 2005}, {'id': '3N9o8Zw3eZbCMRjaWoNjU1', 'artist_name': 'OG Ron C', 'track_name': 'My Hood', 'genre': 'rap', 'year': 2005}, {'id': '5atQbVKdllIQ4rO3MtErcq', 'artist_name': 'Kyle Lee', 'track_name': 'Mixtape Monster - Intro', 'genre': 'rap', 'year': 2005}, {'id': '7Jmkcy5ZdBdyWC5jkXdTZO', 'artist_name': 'OG Ron C', 'track_name': 'Diamonds and Tattoos', 'genre': 'rap', 'year': 2005}, {'id': '6WmDHd2AjZRrDVxYBWzT3P', 'artist_name': 'JasonMartin', 'track_name': 'D.j. Warrior Drop- Cali - Untouchables', 'genre': 'rap', 'year': 2005}, {'id': '3iexshbbBG3085FdFYYdVR', 'artist_name': 'OG Ron C', 'track_name': "You Don't Wanna", 'genre': 'rap', 'year': 2005}, {'id': '5k6jRgIPNgEFtyDNrhzCGJ', 'artist_name': 'Herschelwood Hardheadz', 'track_name': 'Mommie Got Ass - Chopped', 'genre': 'rap', 'year': 2005}, {'id': '4IMoghtM22vMCd3X3weqze', 'artist_name': 'JasonMartin', 'track_name': 'D.j. Skee Drop', 'genre': 'rap', 'year': 2005}, {'id': '4eK6zfv7stUSXZ59Ndw4Fk', 'artist_name': 'Doppel D', 'track_name': 'Da Bua', 'genre': 'rap', 'year': 2005}, {'id': '4eK6zfv7stUSXZ59Ndw4Fk', 'artist_name': 'Monaco F', 'track_name': 'Da Bua', 'genre': 'rap', 'year': 2005}, {'id': '4eK6zfv7stUSXZ59Ndw4Fk', 'artist_name': 'Grämsn', 'track_name': 'Da Bua', 'genre': 'rap', 'year': 2005}, {'id': '4eK6zfv7stUSXZ59Ndw4Fk', 'artist_name': 'DJ Spliff', 'track_name': 'Da Bua', 'genre': 'rap', 'year': 2005}, {'id': '5f3m7SJ0M5aSWXW4DTJ97v', 'artist_name': 'Uratsakidogi', 'track_name': 'Поросята болеют (Live)', 'genre': 'rap', 'year': 2005}, {'id': '0xbA7kllnny3wE77Gyj5v5', 'artist_name': 'Pistol', 'track_name': 'Dirty Game', 'genre': 'rap', 'year': 2005}, {'id': '73r3jyJOFj32BoUpK4EZCj', 'artist_name': 'OG Ron C', 'track_name': 'Freestyle Fifteen', 'genre': 'rap', 'year': 2005}, {'id': '73r3jyJOFj32BoUpK4EZCj', 'artist_name': 'Wreckin’ Yard', 'track_name': 'Freestyle Fifteen', 'genre': 'rap', 'year': 2005}, {'id': '58J04spfvKkSVRBTxjdOMC', 'artist_name': 'Doppel D', 'track_name': 'Irgend a Spinner', 'genre': 'rap', 'year': 2005}, {'id': '58J04spfvKkSVRBTxjdOMC', 'artist_name': 'Monaco F', 'track_name': 'Irgend a Spinner', 'genre': 'rap', 'year': 2005}, {'id': '58J04spfvKkSVRBTxjdOMC', 'artist_name': 'Grämsn', 'track_name': 'Irgend a Spinner', 'genre': 'rap', 'year': 2005}, {'id': '58J04spfvKkSVRBTxjdOMC', 'artist_name': 'DJ Spliff', 'track_name': 'Irgend a Spinner', 'genre': 'rap', 'year': 2005}, {'id': '4JwOUwSO8H0baE8iDJEmPd', 'artist_name': 'Pumpkinhead', 'track_name': 'DP One interlude', 'genre': 'rap', 'year': 2005}, {'id': '3ZOWpz0JIH0wIm8EjkAPXE', 'artist_name': 'Pistol', 'track_name': 'Shoulda Been A Pimp', 'genre': 'rap', 'year': 2005}, {'id': '01AHHO9dGXvBnD12CqORl0', 'artist_name': 'Trails', 'track_name': 'You Want More', 'genre': 'rap', 'year': 2005}, {'id': '7r0BzMewUAIjqjDRXG3Dur', 'artist_name': 'Pistol', 'track_name': 'Yall Niggaz', 'genre': 'rap', 'year': 2005}, {'id': '5M9w6Lz5XyaaFv6NBU5oON', 'artist_name': 'Mr Raw', 'track_name': 'Uwa Bu Aja', 'genre': 'rap', 'year': 2005}, {'id': '4EpqOYBxBmqq8um144rKaN', 'artist_name': 'Uratsakidogi', 'track_name': 'Здравствуйте, я – чушарёк! (Live)', 'genre': 'rap', 'year': 2005}, {'id': '68k9AqFxLeXMfnhz44MUFL', 'artist_name': '3rd Degree Entertainment', 'track_name': 'Got It On Your Mind - Feat. Worldwide', 'genre': 'rap', 'year': 2005}, {'id': '6pokZoyG6JuYJEKrcXImPs', 'artist_name': 'Dirty South Rydaz', 'track_name': 'Commercial Flows - Screwed', 'genre': 'rap', 'year': 2005}, {'id': '5n6eLw3ig6WOOxh4xQPlyM', 'artist_name': 'Mr. Pookie', 'track_name': 'Mr. Pooke - Interlude', 'genre': 'rap', 'year': 2005}, {'id': '0p1WkrRpvHAvMfB1X6PNB0', 'artist_name': 'JasonMartin', 'track_name': 'Young Maylay Drop-', 'genre': 'rap', 'year': 2005}, {'id': '6Wm6lnuth8liuOlyOBtonD', 'artist_name': 'Purple City', 'track_name': 'The Purchase Pt. 2 - Skit', 'genre': 'rap', 'year': 2005}, {'id': '7upM23ak8fi49DeRLekPLu', 'artist_name': 'Uratsakidogi', 'track_name': 'Андрей Романыч (Live)', 'genre': 'rap', 'year': 2005}, {'id': '3z9zU9IoHNHNWG446L7oUl', 'artist_name': 'Trails', 'track_name': 'Rich Girl / ft. Supa', 'genre': 'rap', 'year': 2005}, {'id': '1Vt59OU1e3eCjqGDYcqCQ5', 'artist_name': 'The Dirtball', 'track_name': 'The Drink', 'genre': 'rap', 'year': 2005}, {'id': '04YcnmSTUCP0YDgNVwcvhu', 'artist_name': 'Trails', 'track_name': 'Off da Wall', 'genre': 'rap', 'year': 2005}, {'id': '1f0ZgoNLkJykQy24bZS9gh', 'artist_name': 'Doppel D', 'track_name': 'Kine von Bayern', 'genre': 'rap', 'year': 2005}, {'id': '1f0ZgoNLkJykQy24bZS9gh', 'artist_name': 'Monaco F', 'track_name': 'Kine von Bayern', 'genre': 'rap', 'year': 2005}, {'id': '1f0ZgoNLkJykQy24bZS9gh', 'artist_name': 'Grämsn', 'track_name': 'Kine von Bayern', 'genre': 'rap', 'year': 2005}, {'id': '1f0ZgoNLkJykQy24bZS9gh', 'artist_name': 'DJ Spliff', 'track_name': 'Kine von Bayern', 'genre': 'rap', 'year': 2005}, {'id': '5pRwhxf8YtqVAc0k0bcw7f', 'artist_name': 'Mr. Knightowl', 'track_name': 'Raza Radio (Interlude)', 'genre': 'rap', 'year': 2005}, {'id': '4lQO02aBjHdPB4kTZnRdQz', 'artist_name': 'Uratsakidogi', 'track_name': 'Дедушка Бронислав (Live)', 'genre': 'rap', 'year': 2005}, {'id': '5gMHXFg1wpO3vW5O29VISD', 'artist_name': 'Trails', 'track_name': 'Da King / ft, MG da Street Sweeper', 'genre': 'rap', 'year': 2005}, {'id': '3aqmSfl7GcDHvddJMJqWLV', 'artist_name': 'Doppel D', 'track_name': 'In meim Jargon', 'genre': 'rap', 'year': 2005}, {'id': '3aqmSfl7GcDHvddJMJqWLV', 'artist_name': 'Monaco F', 'track_name': 'In meim Jargon', 'genre': 'rap', 'year': 2005}, {'id': '3aqmSfl7GcDHvddJMJqWLV', 'artist_name': 'Grämsn', 'track_name': 'In meim Jargon', 'genre': 'rap', 'year': 2005}, {'id': '3aqmSfl7GcDHvddJMJqWLV', 'artist_name': 'DJ Spliff', 'track_name': 'In meim Jargon', 'genre': 'rap', 'year': 2005}, {'id': '0Etq3NjvsrQNDjaTDjiCUz', 'artist_name': 'Trails', 'track_name': 'Im A Hustler / ft. J.Kid & Stunn', 'genre': 'rap', 'year': 2005}, {'id': '1StgwbdlxAiYg2CTH1RpqE', 'artist_name': 'Mr. Criminal', 'track_name': 'Skit (Kick Back)', 'genre': 'rap', 'year': 2005}, {'id': '1StgwbdlxAiYg2CTH1RpqE', 'artist_name': 'Mr. Silent', 'track_name': 'Skit (Kick Back)', 'genre': 'rap', 'year': 2005}, {'id': '7L4h7ME4ZPshvj9OYFsh42', 'artist_name': 'OG Ron C', 'track_name': 'Da Hood Back', 'genre': 'rap', 'year': 2005}, {'id': '03vWZTYPgMm1QespLfGMzX', 'artist_name': 'Duffel Bag Hottie', 'track_name': 'Skit, Pt. 3', 'genre': 'rap', 'year': 2005}, {'id': '03vWZTYPgMm1QespLfGMzX', 'artist_name': 'Black Soprano Family', 'track_name': 'Skit, Pt. 3', 'genre': 'rap', 'year': 2005}, {'id': '3zfktC09Dy0p2BfnEGKn0h', 'artist_name': 'Uratsakidogi', 'track_name': 'Пострел (Live)', 'genre': 'rap', 'year': 2005}, {'id': '0BrfqPlYYSFZ4P1geCT4yw', 'artist_name': 'Uratsakidogi', 'track_name': 'Очень хорошие штаны (Live)', 'genre': 'rap', 'year': 2005}, {'id': '0rQggltGX78ds2XIXpMWgm', 'artist_name': 'Pistol', 'track_name': 'Intro', 'genre': 'rap', 'year': 2005}, {'id': '4LcuzyUDnSXByu5n3msras', 'artist_name': 'Al Iman Staff', 'track_name': "K'rhyme le roi interlude", 'genre': 'rap', 'year': 2005}, {'id': '172IakbigRsIv5AWPtln6s', 'artist_name': 'Uratsakidogi', 'track_name': 'Знание – смерть, невежество – позор! (Live)', 'genre': 'rap', 'year': 2005}, {'id': '6GXynjzH0D2X2i56TsxqNj', 'artist_name': 'C-Note', 'track_name': 'Dead Body', 'genre': 'rap', 'year': 2005}, {'id': '77ABM8EUDorx3yWwiJOUBp', 'artist_name': 'Doppel D', 'track_name': 'Ober, no a Bier', 'genre': 'rap', 'year': 2005}, {'id': '77ABM8EUDorx3yWwiJOUBp', 'artist_name': 'Monaco F', 'track_name': 'Ober, no a Bier', 'genre': 'rap', 'year': 2005}, {'id': '77ABM8EUDorx3yWwiJOUBp', 'artist_name': 'Grämsn', 'track_name': 'Ober, no a Bier', 'genre': 'rap', 'year': 2005}, {'id': '77ABM8EUDorx3yWwiJOUBp', 'artist_name': 'DJ Spliff', 'track_name': 'Ober, no a Bier', 'genre': 'rap', 'year': 2005}, {'id': '4cohM6r9AK6kTKUg6TI7Ir', 'artist_name': 'Duke Da God', 'track_name': 'Duke da God Speaks', 'genre': 'rap', 'year': 2005}, {'id': '2uxYTBLkToqQDChioKIGqC', 'artist_name': 'Uratsakidogi', 'track_name': 'Ослик-поэт (Live)', 'genre': 'rap', 'year': 2005}, {'id': '4igz3jDZnwu8T5EYoTe2sY', 'artist_name': 'Liquid', 'track_name': 'Hold Me Down', 'genre': 'rap', 'year': 2005}, {'id': '24DtSpswbI0byHeEeUjJ6i', 'artist_name': 'Doppel D', 'track_name': 'Doppelt sehn', 'genre': 'rap', 'year': 2005}, {'id': '24DtSpswbI0byHeEeUjJ6i', 'artist_name': 'Monaco F', 'track_name': 'Doppelt sehn', 'genre': 'rap', 'year': 2005}, {'id': '24DtSpswbI0byHeEeUjJ6i', 'artist_name': 'Grämsn', 'track_name': 'Doppelt sehn', 'genre': 'rap', 'year': 2005}, {'id': '24DtSpswbI0byHeEeUjJ6i', 'artist_name': 'DJ Spliff', 'track_name': 'Doppelt sehn', 'genre': 'rap', 'year': 2005}, {'id': '21KGsBEE6HnHnW96rARu7a', 'artist_name': 'Soriano', 'track_name': 'Farfiza', 'genre': 'rap', 'year': 2005}, {'id': '3TBtxO6Ft1TlQNcQMRsgbo', 'artist_name': 'Doppel D', 'track_name': 'Am Stießn - Yoyoyoyo', 'genre': 'rap', 'year': 2005}, {'id': '3TBtxO6Ft1TlQNcQMRsgbo', 'artist_name': 'Monaco F', 'track_name': 'Am Stießn - Yoyoyoyo', 'genre': 'rap', 'year': 2005}, {'id': '3TBtxO6Ft1TlQNcQMRsgbo', 'artist_name': 'Grämsn', 'track_name': 'Am Stießn - Yoyoyoyo', 'genre': 'rap', 'year': 2005}, {'id': '3TBtxO6Ft1TlQNcQMRsgbo', 'artist_name': 'DJ Spliff', 'track_name': 'Am Stießn - Yoyoyoyo', 'genre': 'rap', 'year': 2005}, {'id': '5HbYIo3xwmmlVvpo1MxpUd', 'artist_name': 'Crash Crew', 'track_name': "Rockin' on the Radio - Sugar Hill Mix By the Scratch Perverts' Prime Cuts", 'genre': 'rap', 'year': 2005}, {'id': '32K25TkmWvMZKZTXrB3eh5', 'artist_name': 'OG Ron C', 'track_name': 'Play', 'genre': 'rap', 'year': 2005}, {'id': '1GGKZ3QCwxF9EanXAYnVzv', 'artist_name': 'Junebug Slim', 'track_name': 'Holiday', 'genre': 'rap', 'year': 2005}, {'id': '5TOnn7iKrDG1kYwpmXnoSp', 'artist_name': 'Monsta', 'track_name': 'Crash', 'genre': 'rap', 'year': 2005}, {'id': '3zp2F2NX2PstBA4mJ3PFGs', 'artist_name': 'Uratsakidogi', 'track_name': 'Юнаты (Live)', 'genre': 'rap', 'year': 2005}, {'id': '06Cr3WNfyUvfoC2YLNYlGZ', 'artist_name': 'Uratsakidogi', 'track_name': 'Хвастунишка (Live)', 'genre': 'rap', 'year': 2005}, {'id': '5fJgeIZiSJuKFqNec9xukr', 'artist_name': 'Doppel D', 'track_name': 'Gib ma dei Gäid', 'genre': 'rap', 'year': 2005}, {'id': '5fJgeIZiSJuKFqNec9xukr', 'artist_name': 'Monaco F', 'track_name': 'Gib ma dei Gäid', 'genre': 'rap', 'year': 2005}, {'id': '5fJgeIZiSJuKFqNec9xukr', 'artist_name': 'Grämsn', 'track_name': 'Gib ma dei Gäid', 'genre': 'rap', 'year': 2005}, {'id': '5fJgeIZiSJuKFqNec9xukr', 'artist_name': 'DJ Spliff', 'track_name': 'Gib ma dei Gäid', 'genre': 'rap', 'year': 2005}, {'id': '1leszngwbwNlNInngLCikf', 'artist_name': '63 Регион', 'track_name': 'Почему тёлки?', 'genre': 'rap', 'year': 2005}, {'id': '6gt7L38eBuB2pl1Cb7Lf97', 'artist_name': 'Uratsakidogi', 'track_name': 'Механический Karlsson (M.C.D.EAD Remix)', 'genre': 'rap', 'year': 2005}, {'id': '6gt7L38eBuB2pl1Cb7Lf97', 'artist_name': 'M.C.D.EAD', 'track_name': 'Механический Karlsson (M.C.D.EAD Remix)', 'genre': 'rap', 'year': 2005}, {'id': '2SgO5wZ3fiC8DMeqa9KqxU', 'artist_name': 'Willie Wood & Willie Wood Crew', 'track_name': 'Willie Rap', 'genre': 'rap', 'year': 2005}, {'id': '1fDF3mQlIPKQcPllRXe319', 'artist_name': 'Uratsakidogi', 'track_name': 'Толстый дитятя (Live)', 'genre': 'rap', 'year': 2005}, {'id': '3DXmw53lXqeRCYTJpDkZ15', 'artist_name': 'Pakal', 'track_name': 'Llueve Sobre Mojado (Interludio)', 'genre': 'rap', 'year': 2005}, {'id': '4agtjnIiQjRmFgwanDTox4', 'artist_name': 'Tonedeff', 'track_name': 'Disappointed - Instrumental', 'genre': 'rap', 'year': 2005}, {'id': '5veyepjqjAVMmhNPKQFrMP', 'artist_name': 'Purple City', 'track_name': 'The Purchase Pt. 1 - Skit', 'genre': 'rap', 'year': 2005}, {'id': '4h8AW9nlxL1ObLZfQqaJ25', 'artist_name': 'Liquid', 'track_name': "The Beggar's Grief", 'genre': 'rap', 'year': 2005}, {'id': '6jWl4kSgNvLekvNAh0nODy', 'artist_name': 'JasonMartin', 'track_name': 'Mark Breezy Drop', 'genre': 'rap', 'year': 2005}, {'id': '46xQC0NGczCUVmYGjC0MXp', 'art

In [11]:
archivos_rap

[{'id': '4FXSEdmbbeGmPIQltH27C8',
  'artist_name': 'La Oreja de Van Gogh',
  'track_name': 'Pop',
  'genre': 'rap',
  'year': 2000},
 {'id': '0plPN6zr3r0vW4VA0cTlmO',
  'artist_name': 'Dany Bpm',
  'track_name': 'I Want to Know what Love Is',
  'genre': 'rap',
  'year': 2000},
 {'id': '4ZFvUk3xhvofhh3rCaQbq0',
  'artist_name': 'D-4-MA',
  'track_name': 'The Promise',
  'genre': 'rap',
  'year': 2000},
 {'id': '3JISoccsWqVz9KGZUK6pPX',
  'artist_name': 'Enigmatik',
  'track_name': 'Apache',
  'genre': 'rap',
  'year': 2000},
 {'id': '1Hb0K8CGqKNaj2sBvvSkT7',
  'artist_name': 'Nina Gordon',
  'track_name': '2003',
  'genre': 'rap',
  'year': 2000},
 {'id': '5N0cZG9UCMBMeetIPGW8G5',
  'artist_name': 'Nostalgi-K',
  'track_name': 'The Spirit - 2001 Remix',
  'genre': 'rap',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Chenoa',
  'track_name': 'Lady Marmalade',
  'genre': 'rap',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Gisela',
  'track_name': 'Lady Marmalade',
  'genre': 'rap',
  'year': 2001},
 {'id': '3Z7mrMsAdiAVtmhQXkWHQV',
  'artist_name': 'Verónica Romero',
  'track_name': 'Lady Marmalade',
  'genre': 'rap',
  'year': 2001},
 {'id': '0Ppu3VRq2skQDIfjcowHcZ',
  'artist_name': 'NAIM',
  'track_name': 'Guilty',
  'genre': 'rap',
  'year': 2001},
 {'id': '0Ppu3VRq2skQDIfjcowHcZ',
  'artist_name': 'Verónica Romero',
  'track_name': 'Guilty',
  'genre': 'rap',
  'year': 2001},
 {'id': '6eXUFbNK4uhqDsPTOKOuh0',
  'artist_name': 'Naim',
  'track_name': "Don't Let The Sun Go Down On Me",
  'genre': 'rap',
  'year': 2001},
 {'id': '6eXUFbNK4uhqDsPTOKOuh0',
  'artist_name': 'Alejandro Parreño',
  'track_name': "Don't Let The Sun Go Down On Me",
  'genre': 'rap',
  'year': 2001},
 {'id': '2NwBOhoA4xiJK2jmWp5FNd',
  'artist_name': 'Nostalgi-K',
  'track_name': 'Electricity - 2001Remix',
  'genre': 'rap',
  'year': 2001},
 {'id': '1URps6RTulUZzTHmNmmyKW',
  'artist_name': 'Technoiser',
  'track_name': 'Water 2001',
  'genre': 'rap',
  'year': 2001},
 {'id': '3FrhNoBm5cy8iuUlOUDdkJ',
  'artist_name': 'DJ Ricardo',
  'track_name': 'The Sound Barrier',
  'genre': 'rap',
  'year': 2001},
 {'id': '1JbAj245mmW4GVX1ohOmLS',
  'artist_name': 'Los Piratas',
  'track_name': 'Gen 14',
  'genre': 'rap',
  'year': 2001},
 {'id': '3vdxdwKTljNZPLEX7hcrMe',
  'artist_name': 'TCR',
  'track_name': 'P.o.p',
  'genre': 'rap',
  'year': 2001},
 {'id': '70PRAaiRpevoPI4zbs2VGa',
  'artist_name': 'X-Que, Vol. 8',
  'track_name': 'When I Sleep',
  'genre': 'rap',
  'year': 2002},
 {'id': '0sF8c858LGAUaTMPWihEvw',
  'artist_name': '2002',
  'track_name': 'The Sound of Still Water',
  'genre': 'rap',
  'year': 2002},
 {'id': '3rkE8IiFy0z893ZqUzDFLk',
  'artist_name': 'Tessa',
  'track_name': 'Tú Volverás',
  'genre': 'rap',
  'year': 2002},
 {'id': '5HLQc8z7BpfrNHmY0o5Ugu',
  'artist_name': 'X-Que, Vol. 8',
  'track_name': 'Beautiful Day - Home Version',
  'genre': 'rap',
  'year': 2002},
 {'id': '1IudL4RSthUP5kWD0HLZUP',
  'artist_name': '2002',
  'track_name': 'City of Peace',
  'genre': 'rap',
  'year': 2002},
 {'id': '4UzbnrVB4sKrYxlWRGNzBR',
  'artist_name': 'Merche',
  'track_name': 'El Barman',
  'genre': 'rap',
  'year': 2002},
 {'id': '4xUeb0mgEljSLJIxFXLKPF',
  'artist_name': 'Factoria X',
  'track_name': "Rewards (feat. The Moreno's)",
  'genre': 'rap',
  'year': 2002},
 {'id': '4xUeb0mgEljSLJIxFXLKPF',
  'artist_name': "The Moreno's",
  'track_name': "Rewards (feat. The Moreno's)",
  'genre': 'rap',
  'year': 2002},
 {'id': '7tX0V2ikN9Y9UNH4d3w77F',
  'artist_name': 'Sidonie',
  'track_name': 'Mode',
  'genre': 'rap',
  'year': 2002},
 {'id': '7sT8zEGhVsw85dCYP4MNUy',
  'artist_name': 'Luis Morera',
  'track_name': 'Generacion 2000',
  'genre': 'rap',
  'year': 2002},
 {'id': '4UmOcKAtCNjlDFtHcxWcvh',
  'artist_name': 'Toy Soldiers',
  'track_name': 'Popcorn',
  'genre': 'rap',
  'year': 2002},
 {'id': '5OsJWplppfqtByGFVx49je',
  'artist_name': 'Bellepop',
  'track_name': 'La vida que va (Heart in Distress)',
  'genre': 'rap',
  'year': 2002},
 {'id': '0k9o36zHjfM2Oh79dGQTNs',
  'artist_name': 'Sidonie',
  'track_name': 'In Da Sun',
  'genre': 'rap',
  'year': 2002},
 {'id': '2o4osHcCkrkaVFZ4d0i7rL',
  'artist_name': 'Bellepop',
  'track_name': 'Paraíso (Paradise)',
  'genre': 'rap',
  'year': 2002},
 {'id': '5YQZJha9tq0pF9E7zCPJd4',
  'artist_name': 'Dover',
  'track_name': 'The Flame',
  'genre': 'rap',
  'year': 2003},
 {'id': '5oz2AGkudJ4st3CaBz5Toa',
  'artist_name': 'Melody',
  'track_name': 'Será',
  'genre': 'rap',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': 'H.A.W.K.',
  'track_name': 'Freestyle',
  'genre': 'rap',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': "Lil' Head",
  'track_name': 'Freestyle',
  'genre': 'rap',
  'year': 2003},
 {'id': '4rnocqCFjDi5UBzuf4Xvto',
  'artist_name': 'Kevo',
  'track_name': 'Freestyle',
  'genre': 'rap',
  'year': 2003},
 {'id': '7tbS96G0V7WMTxopfpe0nH',
  'artist_name': 'Dj David Max',
  'track_name': 'News 2003 - La Gaita Hard Mix',
  'genre': 'rap',
  'year': 2003},
 {'id': '6ciXx0fgkmAnaiX3iv9Hjd',
  'artist_name': 'Papas Fritas',
  'track_name': 'Way You Walk',
  'genre': 'rap',
  'year': 2003},
 {'id': '3X9e9mQzcQD15VlIkDnLKv',
  'artist_name': 'Saturn DJ',
  'track_name': 'Take Me 2003',
  'genre': 'rap',
  'year': 2003},
 {'id': '3VVnAoNIHeTG8TYLxMymnv',
  'artist_name': 'Melody',
  'track_name': 'Será',
  'genre': 'rap',
  'year': 2003},
 {'id': '74lY6ixYn1cHqacjoBPSD2',
  'artist_name': 'Revolver',
  'track_name': 'Fuera de lugar (feat. José Manuel Casañ)',
  'genre': 'rap',
  'year': 2003},
 {'id': '74lY6ixYn1cHqacjoBPSD2',
  'artist_name': 'Jose Manuel Casañ',
  'track_name': 'Fuera de lugar (feat. José Manuel Casañ)',
  'genre': 'rap',
  'year': 2003},
 {'id': '5IrU3wUKCbAjDxKjgdQfpm',
  'artist_name': 'Deluxe',
  'track_name': 'It Could Have Been My Mirror',
  'genre': 'rap',
  'year': 2003},
 {'id': '5qbrqNka0MDjGAA00iTII6',
  'artist_name': 'Deluxe',
  'track_name': 'Hey Brother!',
  'genre': 'rap',
  'year': 2003},
 {'id': '1YksCvyydKFrisWiHj6zOI',
  'artist_name': 'Beltway 8',
  'track_name': 'Track 11 (Eighted & Chopped)',
  'genre': 'rap',
  'year': 2004},
 {'id': '6DUoQwbCJLYRFkkaGmtx85',
  'artist_name': 'Beltway 8',
  'track_name': 'Track 3 (Eighted & Chopped)',
  'genre': 'rap',
  'year': 2004},
 {'id': '3MB5IcaYZ2wx6uFL7OyL2f',
  'artist_name': 'Naiara',
  'track_name': 'Adelante',
  'genre': 'rap',
  'year': 2004},
 {'id': '0vCx9FL3IpO9x4tcDuowcq',
  'artist_name': 'Merche',
  'track_name': 'Pasar De Los Demas',
  'genre': 'rap',
  'year': 2004},
 {'id': '09ThhkdZ0awxw2MrMpJlCi',
  'artist_name': '3+2',
  'track_name': 'Bailando Voy',
  'genre': 'rap',
  'year': 2004},
 {'id': '7AtoMmLJREWLdN30gOBRn6',
  'artist_name': 'Marsheaux',
  'track_name': 'Pop Corn',
  'genre': 'rap',
  'year': 2004},
 {'id': '3MYqorBQjKiRYOxpLbk264',
  'artist_name': 'DJ Dela',
  'track_name': 'In Your Dreams 2004',
  'genre': 'rap',
  'year': 2004},
 {'id': '3MYqorBQjKiRYOxpLbk264',
  'artist_name': 'Ram J / JYD',
  'track_name': 'In Your Dreams 2004',
  'genre': 'rap',
  'year': 2004},
 {'id': '39xF0oDv6pG4CDuv8ut2u6',
  'artist_name': 'Sírex',
  'track_name': 'Hey Dude',
  'genre': 'rap',
  'year': 2004},
 {'id': '0033iBCIlHfCkRMS0cRJ6F',
  'artist_name': 'OG Ron C',
  'track_name': 'Freestyle Eighteen',
  'genre': 'rap',
  'year': 2005},
 {'id': '0033iBCIlHfCkRMS0cRJ6F',
  'artist_name': 'Wreckin’ Yard',
  'track_name': 'Freestyle Eighteen',
  'genre': 'rap',
  'year': 2005},
 {'id': '1ga2RPfGkXxoQ5mpm9JQGw',
  'artist_name': 'Jacky',
  'track_name': 'My name is sex',
  'genre': 'rap',
  'year': 2005},
 {'id': '3re5zLsF6dqTVW5A9Wn5GQ',
  'artist_name': 'Mr Raw',
  'track_name': 'Pretty Ugly',
  'genre': 'rap',
  'year': 2005},
 {'id': '0aEQgxTsDwgTgmGDn9SLqH',
  'artist_name': 'Doppel D',
  'track_name': 'A bissl fetter',
  'genre': 'rap',
  'year': 2005},
 {'id': '0aEQgxTsDwgTgmGDn9SLqH',
  'artist_name': 'Monaco F',
  'track_name': 'A bissl fetter',
  'genre': 'rap',
  'year': 2005},
 {'id': '0aEQgxTsDwgTgmGDn9SLqH',
  'artist_name': 'Grämsn',
  'track_name': 'A bissl fetter',
  'genre': 'rap',
  'year': 2005},
 {'id': '0aEQgxTsDwgTgmGDn9SLqH',
  'artist_name': 'DJ Spliff',
  'track_name': 'A bissl fetter',
  'genre': 'rap',
  'year': 2005},
 {'id': '1OwMUSNhO5RNs6m8Q9yJLf',
  'artist_name': 'Jacky',
  'track_name': 'Mirise bol',
  'genre': 'rap',
  'year': 2005},
 {'id': '11LakCcb49klYaz0pqC75T',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Шпагоглотатель (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '3N9o8Zw3eZbCMRjaWoNjU1',
  'artist_name': 'OG Ron C',
  'track_name': 'My Hood',
  'genre': 'rap',
  'year': 2005},
 {'id': '5atQbVKdllIQ4rO3MtErcq',
  'artist_name': 'Kyle Lee',
  'track_name': 'Mixtape Monster - Intro',
  'genre': 'rap',
  'year': 2005},
 {'id': '7Jmkcy5ZdBdyWC5jkXdTZO',
  'artist_name': 'OG Ron C',
  'track_name': 'Diamonds and Tattoos',
  'genre': 'rap',
  'year': 2005},
 {'id': '6WmDHd2AjZRrDVxYBWzT3P',
  'artist_name': 'JasonMartin',
  'track_name': 'D.j. Warrior Drop- Cali - Untouchables',
  'genre': 'rap',
  'year': 2005},
 {'id': '3iexshbbBG3085FdFYYdVR',
  'artist_name': 'OG Ron C',
  'track_name': "You Don't Wanna",
  'genre': 'rap',
  'year': 2005},
 {'id': '5k6jRgIPNgEFtyDNrhzCGJ',
  'artist_name': 'Herschelwood Hardheadz',
  'track_name': 'Mommie Got Ass - Chopped',
  'genre': 'rap',
  'year': 2005},
 {'id': '4IMoghtM22vMCd3X3weqze',
  'artist_name': 'JasonMartin',
  'track_name': 'D.j. Skee Drop',
  'genre': 'rap',
  'year': 2005},
 {'id': '4eK6zfv7stUSXZ59Ndw4Fk',
  'artist_name': 'Doppel D',
  'track_name': 'Da Bua',
  'genre': 'rap',
  'year': 2005},
 {'id': '4eK6zfv7stUSXZ59Ndw4Fk',
  'artist_name': 'Monaco F',
  'track_name': 'Da Bua',
  'genre': 'rap',
  'year': 2005},
 {'id': '4eK6zfv7stUSXZ59Ndw4Fk',
  'artist_name': 'Grämsn',
  'track_name': 'Da Bua',
  'genre': 'rap',
  'year': 2005},
 {'id': '4eK6zfv7stUSXZ59Ndw4Fk',
  'artist_name': 'DJ Spliff',
  'track_name': 'Da Bua',
  'genre': 'rap',
  'year': 2005},
 {'id': '5f3m7SJ0M5aSWXW4DTJ97v',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Поросята болеют (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '0xbA7kllnny3wE77Gyj5v5',
  'artist_name': 'Pistol',
  'track_name': 'Dirty Game',
  'genre': 'rap',
  'year': 2005},
 {'id': '73r3jyJOFj32BoUpK4EZCj',
  'artist_name': 'OG Ron C',
  'track_name': 'Freestyle Fifteen',
  'genre': 'rap',
  'year': 2005},
 {'id': '73r3jyJOFj32BoUpK4EZCj',
  'artist_name': 'Wreckin’ Yard',
  'track_name': 'Freestyle Fifteen',
  'genre': 'rap',
  'year': 2005},
 {'id': '58J04spfvKkSVRBTxjdOMC',
  'artist_name': 'Doppel D',
  'track_name': 'Irgend a Spinner',
  'genre': 'rap',
  'year': 2005},
 {'id': '58J04spfvKkSVRBTxjdOMC',
  'artist_name': 'Monaco F',
  'track_name': 'Irgend a Spinner',
  'genre': 'rap',
  'year': 2005},
 {'id': '58J04spfvKkSVRBTxjdOMC',
  'artist_name': 'Grämsn',
  'track_name': 'Irgend a Spinner',
  'genre': 'rap',
  'year': 2005},
 {'id': '58J04spfvKkSVRBTxjdOMC',
  'artist_name': 'DJ Spliff',
  'track_name': 'Irgend a Spinner',
  'genre': 'rap',
  'year': 2005},
 {'id': '4JwOUwSO8H0baE8iDJEmPd',
  'artist_name': 'Pumpkinhead',
  'track_name': 'DP One interlude',
  'genre': 'rap',
  'year': 2005},
 {'id': '3ZOWpz0JIH0wIm8EjkAPXE',
  'artist_name': 'Pistol',
  'track_name': 'Shoulda Been A Pimp',
  'genre': 'rap',
  'year': 2005},
 {'id': '01AHHO9dGXvBnD12CqORl0',
  'artist_name': 'Trails',
  'track_name': 'You Want More',
  'genre': 'rap',
  'year': 2005},
 {'id': '7r0BzMewUAIjqjDRXG3Dur',
  'artist_name': 'Pistol',
  'track_name': 'Yall Niggaz',
  'genre': 'rap',
  'year': 2005},
 {'id': '5M9w6Lz5XyaaFv6NBU5oON',
  'artist_name': 'Mr Raw',
  'track_name': 'Uwa Bu Aja',
  'genre': 'rap',
  'year': 2005},
 {'id': '4EpqOYBxBmqq8um144rKaN',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Здравствуйте, я – чушарёк! (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '68k9AqFxLeXMfnhz44MUFL',
  'artist_name': '3rd Degree Entertainment',
  'track_name': 'Got It On Your Mind - Feat. Worldwide',
  'genre': 'rap',
  'year': 2005},
 {'id': '6pokZoyG6JuYJEKrcXImPs',
  'artist_name': 'Dirty South Rydaz',
  'track_name': 'Commercial Flows - Screwed',
  'genre': 'rap',
  'year': 2005},
 {'id': '5n6eLw3ig6WOOxh4xQPlyM',
  'artist_name': 'Mr. Pookie',
  'track_name': 'Mr. Pooke - Interlude',
  'genre': 'rap',
  'year': 2005},
 {'id': '0p1WkrRpvHAvMfB1X6PNB0',
  'artist_name': 'JasonMartin',
  'track_name': 'Young Maylay Drop-',
  'genre': 'rap',
  'year': 2005},
 {'id': '6Wm6lnuth8liuOlyOBtonD',
  'artist_name': 'Purple City',
  'track_name': 'The Purchase Pt. 2 - Skit',
  'genre': 'rap',
  'year': 2005},
 {'id': '7upM23ak8fi49DeRLekPLu',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Андрей Романыч (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '3z9zU9IoHNHNWG446L7oUl',
  'artist_name': 'Trails',
  'track_name': 'Rich Girl / ft. Supa',
  'genre': 'rap',
  'year': 2005},
 {'id': '1Vt59OU1e3eCjqGDYcqCQ5',
  'artist_name': 'The Dirtball',
  'track_name': 'The Drink',
  'genre': 'rap',
  'year': 2005},
 {'id': '04YcnmSTUCP0YDgNVwcvhu',
  'artist_name': 'Trails',
  'track_name': 'Off da Wall',
  'genre': 'rap',
  'year': 2005},
 {'id': '1f0ZgoNLkJykQy24bZS9gh',
  'artist_name': 'Doppel D',
  'track_name': 'Kine von Bayern',
  'genre': 'rap',
  'year': 2005},
 {'id': '1f0ZgoNLkJykQy24bZS9gh',
  'artist_name': 'Monaco F',
  'track_name': 'Kine von Bayern',
  'genre': 'rap',
  'year': 2005},
 {'id': '1f0ZgoNLkJykQy24bZS9gh',
  'artist_name': 'Grämsn',
  'track_name': 'Kine von Bayern',
  'genre': 'rap',
  'year': 2005},
 {'id': '1f0ZgoNLkJykQy24bZS9gh',
  'artist_name': 'DJ Spliff',
  'track_name': 'Kine von Bayern',
  'genre': 'rap',
  'year': 2005},
 {'id': '5pRwhxf8YtqVAc0k0bcw7f',
  'artist_name': 'Mr. Knightowl',
  'track_name': 'Raza Radio (Interlude)',
  'genre': 'rap',
  'year': 2005},
 {'id': '4lQO02aBjHdPB4kTZnRdQz',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Дедушка Бронислав (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '5gMHXFg1wpO3vW5O29VISD',
  'artist_name': 'Trails',
  'track_name': 'Da King / ft, MG da Street Sweeper',
  'genre': 'rap',
  'year': 2005},
 {'id': '3aqmSfl7GcDHvddJMJqWLV',
  'artist_name': 'Doppel D',
  'track_name': 'In meim Jargon',
  'genre': 'rap',
  'year': 2005},
 {'id': '3aqmSfl7GcDHvddJMJqWLV',
  'artist_name': 'Monaco F',
  'track_name': 'In meim Jargon',
  'genre': 'rap',
  'year': 2005},
 {'id': '3aqmSfl7GcDHvddJMJqWLV',
  'artist_name': 'Grämsn',
  'track_name': 'In meim Jargon',
  'genre': 'rap',
  'year': 2005},
 {'id': '3aqmSfl7GcDHvddJMJqWLV',
  'artist_name': 'DJ Spliff',
  'track_name': 'In meim Jargon',
  'genre': 'rap',
  'year': 2005},
 {'id': '0Etq3NjvsrQNDjaTDjiCUz',
  'artist_name': 'Trails',
  'track_name': 'Im A Hustler / ft. J.Kid & Stunn',
  'genre': 'rap',
  'year': 2005},
 {'id': '1StgwbdlxAiYg2CTH1RpqE',
  'artist_name': 'Mr. Criminal',
  'track_name': 'Skit (Kick Back)',
  'genre': 'rap',
  'year': 2005},
 {'id': '1StgwbdlxAiYg2CTH1RpqE',
  'artist_name': 'Mr. Silent',
  'track_name': 'Skit (Kick Back)',
  'genre': 'rap',
  'year': 2005},
 {'id': '7L4h7ME4ZPshvj9OYFsh42',
  'artist_name': 'OG Ron C',
  'track_name': 'Da Hood Back',
  'genre': 'rap',
  'year': 2005},
 {'id': '03vWZTYPgMm1QespLfGMzX',
  'artist_name': 'Duffel Bag Hottie',
  'track_name': 'Skit, Pt. 3',
  'genre': 'rap',
  'year': 2005},
 {'id': '03vWZTYPgMm1QespLfGMzX',
  'artist_name': 'Black Soprano Family',
  'track_name': 'Skit, Pt. 3',
  'genre': 'rap',
  'year': 2005},
 {'id': '3zfktC09Dy0p2BfnEGKn0h',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Пострел (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '0BrfqPlYYSFZ4P1geCT4yw',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Очень хорошие штаны (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '0rQggltGX78ds2XIXpMWgm',
  'artist_name': 'Pistol',
  'track_name': 'Intro',
  'genre': 'rap',
  'year': 2005},
 {'id': '4LcuzyUDnSXByu5n3msras',
  'artist_name': 'Al Iman Staff',
  'track_name': "K'rhyme le roi interlude",
  'genre': 'rap',
  'year': 2005},
 {'id': '172IakbigRsIv5AWPtln6s',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Знание – смерть, невежество – позор! (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '6GXynjzH0D2X2i56TsxqNj',
  'artist_name': 'C-Note',
  'track_name': 'Dead Body',
  'genre': 'rap',
  'year': 2005},
 {'id': '77ABM8EUDorx3yWwiJOUBp',
  'artist_name': 'Doppel D',
  'track_name': 'Ober, no a Bier',
  'genre': 'rap',
  'year': 2005},
 {'id': '77ABM8EUDorx3yWwiJOUBp',
  'artist_name': 'Monaco F',
  'track_name': 'Ober, no a Bier',
  'genre': 'rap',
  'year': 2005},
 {'id': '77ABM8EUDorx3yWwiJOUBp',
  'artist_name': 'Grämsn',
  'track_name': 'Ober, no a Bier',
  'genre': 'rap',
  'year': 2005},
 {'id': '77ABM8EUDorx3yWwiJOUBp',
  'artist_name': 'DJ Spliff',
  'track_name': 'Ober, no a Bier',
  'genre': 'rap',
  'year': 2005},
 {'id': '4cohM6r9AK6kTKUg6TI7Ir',
  'artist_name': 'Duke Da God',
  'track_name': 'Duke da God Speaks',
  'genre': 'rap',
  'year': 2005},
 {'id': '2uxYTBLkToqQDChioKIGqC',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Ослик-поэт (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '4igz3jDZnwu8T5EYoTe2sY',
  'artist_name': 'Liquid',
  'track_name': 'Hold Me Down',
  'genre': 'rap',
  'year': 2005},
 {'id': '24DtSpswbI0byHeEeUjJ6i',
  'artist_name': 'Doppel D',
  'track_name': 'Doppelt sehn',
  'genre': 'rap',
  'year': 2005},
 {'id': '24DtSpswbI0byHeEeUjJ6i',
  'artist_name': 'Monaco F',
  'track_name': 'Doppelt sehn',
  'genre': 'rap',
  'year': 2005},
 {'id': '24DtSpswbI0byHeEeUjJ6i',
  'artist_name': 'Grämsn',
  'track_name': 'Doppelt sehn',
  'genre': 'rap',
  'year': 2005},
 {'id': '24DtSpswbI0byHeEeUjJ6i',
  'artist_name': 'DJ Spliff',
  'track_name': 'Doppelt sehn',
  'genre': 'rap',
  'year': 2005},
 {'id': '21KGsBEE6HnHnW96rARu7a',
  'artist_name': 'Soriano',
  'track_name': 'Farfiza',
  'genre': 'rap',
  'year': 2005},
 {'id': '3TBtxO6Ft1TlQNcQMRsgbo',
  'artist_name': 'Doppel D',
  'track_name': 'Am Stießn - Yoyoyoyo',
  'genre': 'rap',
  'year': 2005},
 {'id': '3TBtxO6Ft1TlQNcQMRsgbo',
  'artist_name': 'Monaco F',
  'track_name': 'Am Stießn - Yoyoyoyo',
  'genre': 'rap',
  'year': 2005},
 {'id': '3TBtxO6Ft1TlQNcQMRsgbo',
  'artist_name': 'Grämsn',
  'track_name': 'Am Stießn - Yoyoyoyo',
  'genre': 'rap',
  'year': 2005},
 {'id': '3TBtxO6Ft1TlQNcQMRsgbo',
  'artist_name': 'DJ Spliff',
  'track_name': 'Am Stießn - Yoyoyoyo',
  'genre': 'rap',
  'year': 2005},
 {'id': '5HbYIo3xwmmlVvpo1MxpUd',
  'artist_name': 'Crash Crew',
  'track_name': "Rockin' on the Radio - Sugar Hill Mix By the Scratch Perverts' Prime Cuts",
  'genre': 'rap',
  'year': 2005},
 {'id': '32K25TkmWvMZKZTXrB3eh5',
  'artist_name': 'OG Ron C',
  'track_name': 'Play',
  'genre': 'rap',
  'year': 2005},
 {'id': '1GGKZ3QCwxF9EanXAYnVzv',
  'artist_name': 'Junebug Slim',
  'track_name': 'Holiday',
  'genre': 'rap',
  'year': 2005},
 {'id': '5TOnn7iKrDG1kYwpmXnoSp',
  'artist_name': 'Monsta',
  'track_name': 'Crash',
  'genre': 'rap',
  'year': 2005},
 {'id': '3zp2F2NX2PstBA4mJ3PFGs',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Юнаты (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '06Cr3WNfyUvfoC2YLNYlGZ',
  'artist_name': 'Uratsakidogi',
  'track_name': 'Хвастунишка (Live)',
  'genre': 'rap',
  'year': 2005},
 {'id': '5fJgeIZiSJuKFqNec9xukr',
  'artist_name': 'Doppel D',
  'track_name': 'Gib ma dei Gäid',
  'genre': 'rap',
  'year': 2005},
 {'id': '5fJgeIZiSJuKFqNec9xukr',
  'artist_name': 'Monaco F',
  'track_name': 'Gib ma dei Gäid',
  'genre': 'rap',
  'year': 2005},
 {'id': '5fJgeIZiSJuKFqNec9xukr',
  'artist_name': 'Grämsn',
  'track_name': 'Gib ma dei Gäid',
  'genre': 'rap',
  'year': 2005},
 {'id': '5fJgeIZiSJuKFqNec9xukr',
  'artist_name': 'DJ Spliff',
  'track_name': 'Gib ma dei Gäid',
  'genre': 'rap',
  'year': 2005},
 {'id': '1leszngwbwNlNInngLCikf',
  'artist_name': '63 Регион',

In [13]:
#creo variables para pasar cada archivo por años
rap_2018=[]
rap_2019=[]
rap_2020=[]
rap_2021=[]
rap_2022=[]

# lo meto por un bucle for para iterar por el 

for archivo in archivos_rap:

    año_del_archivo = archivo['year']

    if año_del_archivo == 2018:
            rap_2018.append(archivo)

    elif año_del_archivo == 2019:
            rap_2019.append(archivo)

    elif año_del_archivo == 2020:
            rap_2020.append(archivo)

    elif año_del_archivo == 2021:
            rap_2021.append(archivo)

    elif año_del_archivo == 2022:
            rap_2022.append(archivo)

# Ahora puedes ver cuántos hay en cada una

print(f"En 2018 hay {len(rap_2018)} archivos rap.")
 
print(f"En 2019 hay {len(rap_2019)} archivos rap.")
print(f"En 2020 hay {len(rap_2020)} archivos rap.")
print(f"En 2021 hay {len(rap_2021)} archivos rap.")
print(f"En 2022 hay {len(rap_2022)} archivos rap.")

En 2018 hay 402 archivos rap.
En 2019 hay 369 archivos rap.
En 2020 hay 497 archivos rap.
En 2021 hay 384 archivos rap.
En 2022 hay 319 archivos rap.

In [ ]:
##una vez tengo esto si quiero guardar este json.poop??

In [15]:
with open("Files/definitivo.json") as archivo_json:
    fuente_json = json.load(archivo_json)

In [16]:
artistas_unicos = sorted({ #Creamos un set (colección de elementos únicos, sin duplicados) y le ponemos un sorted porque los sets no tienen orden.
    elemento["artist_name"]
    for elemento in fuente_json #Recorre cada elemento de nuestro JSON (cada canción).
    if 2018 <= elemento["year"] <= 2022 and elemento["genre"].lower() == "rap" # Filtra solo las canciones cuyo año esté entre 2018 y 2022.Nos aseguramos de que asegura que solo se consideren elementos(canciones) de pop, sin importar mayúsculas/minúsculas
})

print("Artistas únicos de rap entre 2018 y 2022:")
for artista in artistas_unicos:
    print(artista)

Artistas únicos de rap entre 2018 y 2022:
#HESHTEG#
$TOKA
$crappy G
0324 Crew
10 район
100kay
16FLIP
1nonly
1of1
21 Savage
2E
31 FAM
31st Youngin'
3OH!3
3fargo
3ohBlack
3t Brax
411
6Flame
6ix9ine
6osy
7.0.4
805 Clicka
9ockin
A$AP Rocky
AANG
ANDRO
ARVEIN RAJA
ASID
Ab-Rule
Abiichiidii D
Ace Dream
Acts
Adam Levine
Adonis DaHottest
Afrodite
Afroman
Agust D
Akill Miami
Alex Goot
Alfonsina
Alkogol Posle Sporta
Alta Gracia
Amatowsky
Amenazzy
Anane
Ander Berg
Angel Brown
Ania Dudek
Anis Don Demina
Anne-Marie
Anthony Hayes
Anthony Stephens Jr.
Arizona Zervas
Arthrn
Asidity7
Atomic Otro Way
Audrey Lopes
Ava Max
Awkward African
Ayax y Prok
Ayjay
B.P.
BBY KODIE
BIA
BKO
BLOCK CREW
BLOKE
BUPPON
Baby Keem
Baby Ray
Bad Gyal
Bam
Banda Cambaia
Bandingo YGNE
Bankroll Freddie
Bardo José
Bassirou Koureissi
Baya Baye MGT Los Sosis
Becky G
Bekar
Ben Whale
Benboy
Bezo Luciano
Bhaco
Bhad Bhabie
Big E
Big Sean
Big Snow
Big T
Big Tank D
Bigghem
Bigzif
Billy Chester
Billy Cook
Bing
Black Eyed Peas
Black Jonas Point
BlackMago
Blake
Blakk Tha kid
Blauwe Uil
Blebla
Blens Tha Outlaw
Blezz
Blvck Frost
Bobby Sessions
Bodega Los
BoyWithUke
Brain Bonaparte
Breack MC
Breakitdown Dc
Bres
Brous One
Bruno Mars
Bryan
Buddha
Buffalo Bill
Bump J
Bushy B
C Grizzy
C-Rock
C.I.A.
CAIRO!
CAIROXVI.
CCMK
CETCÉ
CHIKA
CHN
CJ
CMDWN
COUPEN
CRAM
Caballero
Calero LDN
Calliope Bub
Cam Steady
Cano
Cardi B
Carlito
Carmel Zoum
Carolyn Rodriquez
Carta Preta
Castro
Cazzu
Cechri Oless
Ceddy Chieff
Cedrichearnjr
Ceesr
Ceky Viciny
Celebration Guns
Cestar
Chacheblack
Chad B
Chalie Boy
Chato Cervantes
Cheb Ruben
Chelo Home
Chevy Woods
Chimbala
Chip Charlez
Chris Brown
Chris King
Chris Tsuanna
Chucc
Chuckwavy
Cinnay
Clio BBP
Cloude
Co Santana
Cool Caddish
CosaFina
Cosmostom
Costa
Costa Stunner
Courtside
Cpt. Spacey
Craig Mack
Cramch
Credibil
Cricet
Cruz Cafuné
Curtis Heron
CutThroat JMoney
Cxenty
D'Esmorga
D.Cure
D3zz
DARKSUNN
DC The Capital
DIMA
DJ 40oz
DJ Ariel Style
DJ Candlestick
DJ Funky
DJ JS-1
DJ Koncept
DJ Michael 5000 Watts
DJ Nasa
DJ RC
DJ Red
DJ Thistle
DJ Tickles
DMG
DOUTOR MC
DR
DRZ
DTF
Da Fusão
DaBaby
Dab
Damara MP
Danindu Bandara
Dante Sito
DarkSunn
Darom Dabro
Das Ding ausm Sumpf
Dasha Ruby
David Alaba
David GotSound
De La Fe
Dead Eye Zack
Deadey
Deanshwty
Dee Low
DeeFromOakland
Delaossa
Delgao
Delict
Denzel Curry
Designer P
Detox22
Dezigna
DiBoy G
Diezel DaBeast
Digui Clodjaleen
Dilla K
Dirty Porko
DiscoTech
Divine Sounds
Dj Ita
Django
Dodo Bank$
Doesn’t K
Doidão Beats
Dolita
Domino Uno
Don Miguelo
Don Mize
Don Patricio
Don Toliver
Donny Boy
Dr. Chk
Drake
DuRap
Dubbi Du
DubbyMaple
Dubskie
Dudi
Duemila
Duendenomic
DukeeMdz
Duncan Dhu
Dé Panama
ELVEEKTOR
EZ
EZVIT 810
Earthadox
Editruz
Eiikeii
Eis
El Alfa
El Blt
El Chojin
El Impresentable
El Nota
El Pelon
El Yman
ElGrandeToto
Elicit
Eloy MQ
Eminem
EmmV
Emporio
Ergo Pro
Erick Endres
Erin Parkes
Ese Boosta
Evangelist Vicky
Evil Twin
Evill D Zayge
EyeKeem
FAKT
FIJI
FUMAÇA
Fab's Brownz
Fabiow
Faia
Faith Rap
Familia236
Famous
Fanicko
Fantom
Farog4rl
Fat Dolsk
Fat Tony
FaulenzA
Felix Krull
Felix Q
Filthy Fill
Flexo Kobain
FlipGang
Flo Rida
Fly Jet
FlygerWoods
Forest Keed
Forgiato Blow
FouKi
Foxy Myller
Foyone
Franklin
Fred Lynch
Fred Nice
Freshy Kanal
Fuego
Fulston
Funk.Shu
Funzo & Baby Loud
Future
G Man
G.A.Z LIMBO
GIMS
GMan
GOH PH
GUERLAIN
Gab Coelho
Gabby Annalyse
Gaetano Pellino
Gallego
Gatom
Gaza Toumisky
Gbaskill-D
Gemini
Gente Loca
Georgia Anne Muldrow
Geovane MC
Gera MX
Ghostluvme
Gio Dallas
Giovchenko
Gmane
Gnomo
Goest Ryder
Goldie Lookin Chain
Gorrsowtu
Gotti Da Ghost
Gr!ff The GOP
Greencowme
Grind
Guerri
Guesan
Guy Sebastian
Gym Class Heroes
HASH TAG
HTD
Hagf
Hamlet
Hans Solo
Hard GZ
Harleston
Haruko Tajima
Hazey Haze
Heemi
HellBoy9k
Hens
Hernani
Heuss L'enfoiré
Hezeleo
High Teig
Highway Yella
Hoke
HoodRich Pablo Juan
Hot Action Cop
Hurricane
Huzur
Hyumn
IAMMIND
IEZ
Ian J
Ice
Ice Lord
Ice One
Iceboy Ben
Icesis
Ill Pekeño
Innerstate Ike
Insane B
Insomnia X
Internet Money
Invadable Harmony
Israel Wusu
ItsNate
Iyaz
Izen
J Champ
J Lev
J Salt
J-Diggs
J-Easy
J-Xtreme
J. Cole
J.Broady
J.C
J360
JACKBOYS
JAVI BAMBINI CATTIVI
JGeezuz
JID
JNS
JPenJail
JSHipHop Rapper Maromba
JT
Jack Harlow
Jack Raw
Jackopp
Jacky
Jada Facer
Jairzinho
Jakk Jo
Jaman T
Jana Calero
Jansport J
Jason Bartsch
Jeepz
Jerry Loko
Jessella
Jey Blessing
Jidax
Jinmenusagi
Joey Banks
John Doe The First
Joost
Joost Hoekaf
Jordan Burgett
Jordan Joseph
Jordy Mankoto
Joshua Dietrich
Jota Infinito
Juan Gambino
Juan K
Juanpe
Juice WRLD
Juju la flamme
Jul
JunnyRast
Jxve
Jíťa
KC Purp
KD
KESHORE
KHEM
KORNDAWG
KREAM
KS1NJAO_GTR
KXLLSWXTCH
Kadec Santa Anna
Kalam
Kali Le Maître
Kaliii
Kane & Abel
Kanye West
Kari
Kase.O
Kasher Quon
Kaze
Kdabousz
Kehlani
Kelvin J.
Kendrick Lamar
Kenndog
Kenya De Silva
Kevin Krust
Kid Astronaut
Kid Rojas
Kid Vegas
Kidd Kidd
Kiga
Killaz96
Kilo Art-Of-Fact
Kilo Vasquez
King Gotit
King KJ
King Kuma
King Kyle Lee
King Nate
King Von
Kingjp
Kirko Bangz
Klondike Kat
Kodak Black
Kof
Kofs
Kojoe
Kolonel Freez
Kon Dada
Koriass
Kostaki
Kota the Friend
Kouiks
Kraneo La Oveja Negra
Kreepa
Ksenon
Kun Índika
Kurt Hugo Schneider
Kwesi TumTum
LIL Dejaniro
LIL Kee
LILCAK3
La Decada Prodigiosa
La Joaqui
La Pantera
La Santa Grifa
La Zowi
Lab51
Lady Monarkey
Ladyapatia
Ladyy Acee
Lahiru Liyanage
Last
Latina 051
LayZ PalaZuelos
Led Hendrix
Leddy
Lee Sui
Lee-Roy
LeeV
Leeko Verde
Lenni B
Leão
LieVin
Ligeh Moneh
Lil Baby
Lil Boas
Lil Cas
Lil Craccrocc
Lil Dev
Lil Escobar
Lil Force
Lil GZ
Lil Gohan
Lil Hope
Lil Koo
Lil Mosey
Lil Peep
Lil Pump
Lil Sicko
Lil Tecca
Lil Tjay
Lil Wes
Lil Yachty
Lil Yput
Lil' Rose
Lionware
Lirico En La Casa
Lloyd Banks
Los 40
Los Hijos de la Luna
Los Jinetes del Trópico
LosNiñosDelCaminito
Loud Motive
Loui
Love Yi
Lox Chatterbox
Luanna
Lucas Sang
Luck
Ludò
Lugatti & 9ine
Lugi
Lulbearrubberband
Lupe Fiasco
Lycos
Lyri
Lágrimas De Sangre
LéoDaXIII
M. Crwford
M4rtim
M4zi
MAJVR
MARKOVICH
MC Yask
MEMATARON
MIST
Mac Miller
Macbeth Uzurpátor
Maclarnaque
Magass
MagiaNegra
Maikel Delacalle
Maikholl
Mala
Mama Dousha
Mandah
Mango Rose
Manic the 17th
ManySharks
Mario Cash
Marlon Craft
Marsh
Mase
Mason
Master T
Mat4yo
Mata
Matasvandals
Matt OX
Maura da Glória
Max Minelli
Maxi
Mayo 214
Mc B.u.S
Mdmoney
Mechanst
Megan Thee Stallion
MeloGenic
Menace
Menace Society
Mene Gene
Metro Boomin
Mikael
Mike D
Milanezie
Miranda
Miserabele Johnny
Miss Honey
Missing LinX
Mo B. Dick
Moha La Squale
Moha The B
Molly Brazy
Money Boy
Montell Fish
Mooski
Morale
More 10
Mosta Man
Mozart La Para
Mr Brown
Mr Raw
Mr. 3-2
Mr. Criminal
Mr. Neva Die
Mr. Wired Up
Mr.Str8-8
MsKillah
Musicologo The Libro
Mustard
Mxntis
Myer Clarity
Myk Fresh
Myka
Método
N.E.S
N9ne11
NAHreally
NATHY PELUSO
NATTI NATASHA
NBA OG 3three
NF
NIGHTINGALE
NLE Choppa
NOSFE
Nadal015
Naes Beats
Naim
Nanno
Naps
Natalac
Natos y Waor
Natti
Neil B
Nerexx
New Boyz
NexXthursday
Ng Bling
Nicofasho
Nicy
Niklas Jeng
Nino Brown
Nino Francis
Nino Jay
NoHesi Ke
Noa Soulas
Nova Jwest
Nue
Nusky
O Nobre
OBN Jay
OBZ
OE
OG Ron C
ONNiKA
Oba Rowland
Ocean Veau
Octavian
Official D&d
Og M.E
Oh Boy Prince
Old Man Saxon
Omega
One Time
Onheels
OptycNerd
Oreo
Outasight
Ox B
Oxi Dum
P-Pain
PENOMECO
PSK-13
PSY
Pachenko Zvuk
Pakman Jitt
Pamela
Pap Nigga
Pat Anthony
Patriot J
Paul Wall
Phaser
Phatt Black
Phenomeinal
Phillippe
Philly's Most Wanted
Phyla Vell
Phước Phật
Pistol
Pivio & Aldo De Scalzi
Playa Cuberris
Playboi Carti
Point Blank
Polo G
Poltabletki
Pop Smoke
Porno Mafia
Porridge Gang
Post Malone
Powfu
Pra(Killa'Gramm)
PrettyBoiZach
Prince Bopp
Psychopads
Ptazeta
PuddaH
Pusha T
Pyrex The Enigma
Q
QUADRA-13
Quevedo
RAEL REAL
RDroots
RLaRage
RM
Rabby Racks
Raez
Randall Trevell
Rap Soumi
Rapta
Rasskulz
Rasta G
Ray J
Ray Reed
Ray Walker
Raycobeats
Rayden
Rebeld SNJ
Regional Overlord Sterling Silver
Reign Mercedes
Renizance
Res_Co
Responsa
Retin.A
Rez Burna
Richard Guaio
Rick de Vik
Rico Finesse
Rikani
Rikky Rozay
Rim'K
Rob Nollan
Robert Hesser
Rochy RD
Rockstar Ham
Rockstar Russ
Roddy Ricch
Roland Prince
Ron Browz
Ronoc 'N' Roll
Rowlan
Roxy Rosa
Royce Da 5'9"
Rubin
Ruimaraes
Rxdri
SAINt JHN
SFDK
SH Kera
SHAWY
SLAT3R
SLESH
SMO3
SOH
SWEETKID
SWIT EME
SZA
SZED
Sabrina Petrova
Saby
Sada Baby
Samuel SLZR
Samzy
Savage Ga$p
Saweetie
Scarlett Miller
Scotty DK
Sean Paul
SecondTime
Serko
Sevenlox
Sh3
ShabZi Madallion
Shai Coke
Shaybo
Shelsia Chiziane
Sho-Hai
Siadou
Sir Charles
Sity Boi
Sivaraj Chandran
Skizzo Skillz
Skrip Polovoy
Sleepy Hallow
Slovetskii
Slowpoke
Smitty the BG
Sneccio
SoSanAntone
Soge Culebra
Solar Slim
Soldier Hard
Son Rob
Sons of Aguirre
Soran
Sosad.97
Soul Sarah
Splash Zanotti
Spock X Lezser
StaFFord63
Stacy
Stafford Beats
Stanford Reid
Stann
StaySolidRocky
Stomo
Stoney Dudebro
Stuken
Summer Walker
Swifty Blue
Sybyr
T H R O N E
TSK
TT17
TURBO
TVB
Tai Dye
Takami
TangTang Ivory
Tati Xiii
Taxi
Tay Money
Tdot illdude
Teejayx6
Tesa
Texxx Pesci
Th Mark
The American Hotel System
The Audible Doctor
The Kaseta
The Tyets
The Whistlers
The White Shadow
Thimbada
Tion Wayne
Tipene
Titiden Lil Iba
Tokischa
Tom Green
Tommy Jacob
Tonho Crocco
ToonVision
Tory Lanez
ToteKing
Tout Atis
Toy Murray
Trap Beckham
Trapp Starr
Travie McCoy
Travis Carta
Travis Scott
Travis Trevor
Trevor Daniel
Trey.V
Trifln'
Trina
Troy Martiin
Tsiguidi Haki No Jungle
Turquoise Music
Tweet
Tyga
Tyler Clark
Tyler Reese
Tyler, The Creator
UM44K
Umteto
Unge Obi
Unorthodocks
Uptimo
Uzimatic
V Dot Nam
VIC MENSA
Vado
Valesia_geo
Vanno
Verbal Jint
Very Abstract
Verónica Romero
Victherockstar
Viewmasters
Vinci
Violentlyill
Vito
Vitor Pirralho
VoxPopuli
Vudik
WANYUDO
Wa11i
Waiian
Wallie the Sensei
Walls
Wander Bill
Waste
Wavele$$
Waze
Welcome 2 Thowd Town
Werepanther
Wesley Voox
Whiskey Autumn
Wild West
Witt Lowry
Wiz Khalifa
Woudley dr
XXXTENTACION
Xaje
Xavibo
Y&R Mookey
Y2K
YERAR CSQ
YNW Melly
Yakbko
Yann Barros
Yaser Binam
Yashan
Yb Puerto Rico
Yeli Fuzzo
Yeyo
Yofu
Yonn
Young Dopey
Young Havaí
Young Mex
Young Mike
Young Pô
Young Thug
Younglove823
Yumalesra
YunGun
Yung Al
Yung Feez
Yung Maaly
Yung Pacino
Yung Threat
Yurrih
Zach Zoya
Zavion
Zazza
Zekko
Zen Goody
Zero Vicious
Zetta
Zibou
Zinfidel Beats
Zoro
Zune
ajan
bambini404
bbno$
famoso tipo
internetboy
itszachquietdwn
j-hope
jinnwilliam
lil click
lil eli young bapestah
lovnee
matty
mgk
oblik
osobenniy
shattered
siccit21
swall
thug
zerardo
Àtomo
ÍRIS
АМИР
Амир
БРАТУБРАТ
Какой-то Реверс
Костя Бес
Леша Лэ
Лёша Маэстро
Майти Ди
НЕ.KURILI
ПЕРЕКРЫШКИН
ПромЗона
Робси
Совче
Стриж
ТРИДЦАТЬ ДЕВЯТЫЙ
Таймет
Цинк Уродов
Эскимос Crew

In [ ]:
# Guardar en un archivo JSON - #Guardamos minijson_rap


with open("artistas_rap_2018_2022.json", "w", encoding="utf-8") as minijson_rap_artistas_unicos: #utf-8 asegura que los caracteres especiales (como acentos) se guarden correctamente
    json.dump(artistas_unicos, minijson_rap_artistas_unicos, ensure_ascii=False, indent=4) #ensure_ascii=False permite que el JSON guarde los caracteres especiales correctamente en su forma natural(tildes,ñ etc)indent :Cada elemento está en su propia línea y sangrado con 4 espacios

Tenemos un minijson del Json definitivo_spoty que tiene una lista con los artistas unicos durante los años 18-22