In [1]:
import mysql.connector
from mysql.connector import errorcode
import pandas as pd
import requests
import json

In [2]:
api_key_last_fm = "dffc96fb5e37b49d6382379a54a66094"  
usuario = "grupoadalab" 
url2 = "http://ws.audioscrobbler.com/2.0/"

In [3]:
url = "http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Slipknot&api_key=dffc96fb5e37b49d6382379a54a66094&format=json"

In [4]:
 #Hacemos la petición a un API de ejemplo.
response = requests.get(url) # Esta dirección es el famoso "endpoint".

# Mostramos la respuesta que nos devuelve el API.

In [5]:
response.status_code

200

In [6]:
datos_artista = response.json()

In [7]:
datos_artista #hemos hecho contacto y llegado al dato del artista

{'artist': {'name': 'Slipknot',
  'mbid': 'a466c2a2-6517-42fb-a160-1087c3bafd9f',
  'url': 'https://www.last.fm/music/Slipknot',
  'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'small'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'medium'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'large'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'extralarge'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': 'mega'},
   {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
    'size': ''}],
  'streamable': '0',
  'ontour': '0',
  'stats': {'listeners': '4166810', 'playcount': '356310357'},
  'similar': {'artist': [{'name': 'Korn',
     'url': 'https://www.last.fm/music/Korn',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Stone Sour',
     'url': 'https://www.last.fm/music/Stone+Sour',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'System of a Down',
     'url': 'https://www.last.fm/music/System+of+a+Down',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Mudvayne',
     'url': 'https://www.last.fm/music/Mudvayne',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]},
    {'name': 'Vended',
     'url': 'https://www.last.fm/music/Vended',
     'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'small'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'medium'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'large'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'extralarge'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': 'mega'},
      {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
       'size': ''}]}]},
  'tags': {'tag': [{'name': 'Nu Metal',
     'url': 'https://www.last.fm/tag/Nu+Metal'},
    {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
    {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
    {'name': 'Nu-metal', 'url': 'https://www.last.fm/tag/Nu-metal'},
    {'name': 'rock', 'url': 'https://www.last.fm/tag/rock'}]},
  'bio': {'links': {'link': {'#text': '',
     'rel': 'original',
     'href': 'https://last.fm/music/Slipknot/+wiki'}},
   'published': '10 Feb 2006, 21:16',
   'summary': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>',
   'content': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [8]:
type(datos_artista)

dict

In [9]:
datos_artista.keys()

dict_keys(['artist'])

In [10]:
datos_artista['artist']

{'name': 'Slipknot',
 'mbid': 'a466c2a2-6517-42fb-a160-1087c3bafd9f',
 'url': 'https://www.last.fm/music/Slipknot',
 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'small'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'medium'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'large'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'extralarge'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': 'mega'},
  {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
   'size': ''}],
 'streamable': '0',
 'ontour': '0',
 'stats': {'listeners': '4166810', 'playcount': '356310357'},
 'similar': {'artist': [{'name': 'Korn',
    'url': 'https://www.last.fm/music/Korn',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Stone Sour',
    'url': 'https://www.last.fm/music/Stone+Sour',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'System of a Down',
    'url': 'https://www.last.fm/music/System+of+a+Down',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Mudvayne',
    'url': 'https://www.last.fm/music/Mudvayne',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]},
   {'name': 'Vended',
    'url': 'https://www.last.fm/music/Vended',
    'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'small'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'medium'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'large'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'extralarge'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': 'mega'},
     {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png',
      'size': ''}]}]},
 'tags': {'tag': [{'name': 'Nu Metal',
    'url': 'https://www.last.fm/tag/Nu+Metal'},
   {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
   {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
   {'name': 'Nu-metal', 'url': 'https://www.last.fm/tag/Nu-metal'},
   {'name': 'rock', 'url': 'https://www.last.fm/tag/rock'}]},
 'bio': {'links': {'link': {'#text': '',
    'rel': 'original',
    'href': 'https://last.fm/music/Slipknot/+wiki'}},
  'published': '10 Feb 2006, 21:16',
  'summary': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>',
  'content': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}

In [11]:
type(datos_artista['artist'])

dict

In [12]:
datos_artista['artist'].keys()

dict_keys(['name', 'mbid', 'url', 'image', 'streamable', 'ontour', 'stats', 'similar', 'tags', 'bio'])

In [13]:
datos_artista['artist']['name']

'Slipknot'

In [14]:
datos_artista['artist']['stats'].keys()

dict_keys(['listeners', 'playcount'])

In [15]:
datos_artista['artist']['stats']['listeners']

'4166810'

In [17]:
datos_artista['artist']['similar'].keys()
#exploramos como acceder al diccionario de artistas similares

dict_keys(['artist'])

In [18]:
datos_artista['artist']['similar']['artist'][0].keys()

dict_keys(['name', 'url', 'image'])

In [19]:
datos_artista['artist']['similar']['artist'][0]['name']

'Korn'

Hacemos las variables de las llamadas

In [20]:
nombre = datos_artista['artist']['name']
audiencia = datos_artista['artist']['stats']['listeners']
reproducciones = datos_artista['artist']['stats']['playcount']
artistas_similares = datos_artista['artist']['similar']['artist'][0]['name'] #aca he puesto solo la primera ocurrencia
nombres_similares = [s['name'] for s in datos_artista['artist']['similar']['artist']] #list comprehension
biografia = datos_artista['artist']['bio']['content']

In [21]:
# Esto crea una lista de strings: ['Megadeth', 'Slayer', 'Pantera'...]
nombres_similares = [s['name'] for s in datos_artista['artist']['similar']['artist']]

print(nombres_similares)

['Korn', 'Stone Sour', 'System of a Down', 'Mudvayne', 'Vended']

In [22]:
datos_artista['artist']['bio']

{'links': {'link': {'#text': '',
   'rel': 'original',
   'href': 'https://last.fm/music/Slipknot/+wiki'}},
 'published': '10 Feb 2006, 21:16',
 'summary': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>',
 'content': 'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}

In [23]:
datos_artista['artist']['bio'].keys()

dict_keys(['links', 'published', 'summary', 'content'])

In [24]:
datos_artista['artist']['bio']['content']

'Slipknot is an American heavy metal band formed in Des Moines, Iowa, in 1995 by percussionist Shawn " Clown" Crahan, vocalist/percussionist Anders Colsefni, and bassist Paul Gray. After several lineup changes in its early years, the band settled on a nine-member lineup for more than a decade, consisting of  Crahan, Gray, Joey Jordison, Craig "133" Jones, Mick Thomson, Corey Taylor, Sid Wilson, Chris Fehn, and Jim Root. Slipknot is known for its distinctive visual presentation, aggressive musical style, and intense live performances.\n\nThe band’s debut demo album, "Mate. Feed. Kill. Repeat." (1996), received limited attention, but Slipknot gained widespread recognition following the release of its self-titled debut studio album, "Slipknot", in 1999. Its second studio album, "Iowa" (2001), further increased the band’s popularity. After a brief hiatus, Slipknot returned in 2004 with "Vol. 3: (The Subliminal Verses)". The band later released "All Hope Is Gone" in 2008, which debuted at number one on the US Billboard 200. Following another hiatus, Slipknot released ".5: The Gray Chapter" in 2014. Its sixth studio album, "We Are Not Your Kind", was released on August 9, 2019, followed by its seventh studio album, "The End, So Far", on September 30, 2022.\n\nSlipknot has also released two live albums, "9.0: Live" and "Day of the Gusano: Live in Mexico", a compilation album titled "Antennas to Hell", and several live DVDs. The band has sold approximately 30 million records worldwide, including more than 12 million in the United States.\n\nPaul Gray died on May 24, 2010, and was replaced between 2011 and 2014 by Donnie Steele. After Gray’s death, Crahan remained the only founding member in the active lineup. Joey Jordison was dismissed from the band in December 2013, and Steele left during the recording sessions for ".5: The Gray Chapter". Slipknot subsequently recruited Alessandro Venturella as bassist and Jay Weinberg as drummer. Chris Fehn was dismissed in March 2019 and was replaced by Michael Pfaff. The band later parted ways with Craig Jones and Jay Weinberg in 2023, with Weinberg being replaced by Eloy Casagrande the following year.\n\nStudio albums\nSlipknot (1999)\nIowa (2001)\nVol. 3: (The Subliminal Verses) (2004)\nAll Hope Is Gone (2008)\n.5: The Gray Chapter (2014)\nWe Are Not Your Kind (2019)\nThe End, So Far (2022)\n\n-----\n\nSlipknot was a thrashcore band from New Haven, Connecticut, active in the late 1980s. The band included Stiemy on bass and vocals, who had previously been the vocalist for Fatal Vision, a group featured on the compilation album "Connecticut Fun", released by INCAS in 1985. The compilation also included an early vinyl appearance by Youth of Today, prior to the band’s later association with the New York hardcore scene.\n\nAfter Slipknot disbanded, Stiemy left the music industry and later pursued work in visual art and culinary arts. The band’s drummer, Chang, also stopped performing music. The guitarist, known as F, later played drums in another New Haven hardcore band, Malachi Krunch. <a href="https://www.last.fm/music/Slipknot">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'

In [25]:
with open('files/artistrock.json', 'r', encoding='utf-8') as f:
    lista_artistas_rock = json.load(f)

In [26]:
lista_artistas_rock

['Unorthodocks',
 'Funk.Shu',
 'Taxi',
 'Anne-Marie',
 'KREAM',
 'Alex Goot',
 'Kurt Hugo Schneider',
 'Jada Facer',
 'Los 40',
 'Fleetwood Mac',
 'Queen',
 'Imagine Dragons',
 'Dani Fernández',
 'Twenty One Pilots',
 'Muse',
 'Bunbury',
 'Gorillaz',
 'Khruangbin',
 'Måneskin',
 'Mumford & Sons',
 'David Bowie',
 'Paul McCartney',
 'Eric Clapton',
 'The Rose',
 'Greta Van Fleet',
 'Panic! At The Disco',
 'Dirty Heads',
 'Eagles',
 'Falling In Reverse',
 'Young the Giant',
 'Inconscientes',
 'Fito Cabrales',
 'TK from Ling tosite sigure',
 'ishikinonaikranke',
 'I Am King',
 'ASIAN KUNG-FU GENERATION',
 'SID',
 'Gritando en Silencio',
 'Godsmack',
 'Glare',
 'Bad Wolves',
 'DIAMANTE',
 'Heroes Del Silencio',
 'DAY6',
 'Bragolin',
 'John Hiatt',
 'Bon Jovi',
 'XXXTENTACION',
 'Kanye West',
 'Travis Barker',
 'Three Days Grace',
 'Shinedown',
 'Bauhaus',
 'Suede',
 'Indio Solari',
 'Los Fundamentalistas del Aire Acondicionado',
 'Columbia Mills',
 'GAUPA',
 'Polyphia',
 'Hombres G',
 'Los Enanitos Verdes',
 'Caramelos De Cianuro',
 'Five Finger Death Punch',
 'Maribou State',
 'Young Gun Silver Fox',
 'Survive Said The Prophet',
 'Billy F Gibbons',
 'Molotov',
 'Chris Cornell',
 'Car Seat Headrest',
 'Hadadanza',
 'Saurom',
 'All Them Witches',
 'Ilegales',
 'Interpol',
 'El Último De La Fila',
 'Nerv',
 'Marilyn Manson',
 'Jimi Hendrix',
 'Elvis Presley',
 'TRAITRS',
 'I DONT KNOW HOW BUT THEY FOUND ME',
 'Escape the Fate',
 'The Neighbourhood',
 'The Voidz',
 'Mark Knopfler',
 'The Beatles',
 'Good Kid',
 'The Cure',
 "Guns N' Roses",
 'Disturbed',
 'Twin Tribes',
 'Babasonicos',
 'Ana Tijoux',
 'Mishka',
 'King Buffalo',
 'Malace Mizer',
 'MY FIRST STORY',
 'Des Rocs',
 'The Vaccines',
 'Ufuk Beydemir',
 'Dire Straits',
 'Yüzyüzeyken Konuşuruz',
 'Geowulf',
 'Mancha De Rolando',
 'THE ORAL CIGARETTES',
 'The Backseat Lovers',
 'SLAVES',
 'Albert Hammond Jr',
 'Razorlight',
 'Daron Malakian and Scars On Broadway',
 'Memphis May Fire',
 'Younger Hunger',
 'Fiona Boyes',
 'Bob Dylan',
 'The Lazys',
 'Mystery',
 "Aunt Cynthia's Cabin",
 'Franz Ferdinand',
 'Breaking Benjamin',
 'Jarabe De Palo',
 'Wallows',
 'Grupo Guinda',
 'Angel Guaraca',
 'Veronica Bolaños',
 'Graveyard',
 'The Goo Goo Dolls',
 'Barbi Recanati',
 'Thundermother',
 'Normandie',
 'The Blue Stones',
 'Tempesst',
 'The Desperados',
 'Lindsey Buckingham',
 'The Rare Occasions',
 'MAN WITH A MISSION',
 'Pond',
 'The Struts',
 'Lebanon Hanover',
 'Ciro y los Persas',
 'ROTTENGRAFFTY',
 'Bring Me The Horizon',
 'Sextile',
 'The Smashing Pumpkins',
 'La Trinca',
 'LEDGER',
 'KANA-BOON',
 'Self Deception',
 'Cuco',
 'Supertramp',
 'The Warning',
 'From Ashes to New',
 'The Marcus King Band',
 'Guitarricadelafuente',
 'IZAL',
 'Buhos',
 'ELYELLA',
 'La Pegatina',
 'Vanesa Martín',
 'Veintiuno',
 'Taburete',
 'Sidonie',
 'El Kanka',
 'Maki',
 'MGMT',
 'Melendi',
 'Arnau Griso',
 'Viva Suecia',
 'Carolina Durante',
 'Doctor Prats',
 'Kool & The Gang',
 'Bishop Briggs',
 'Everybody Loves an Outlaw',
 'Mr. Kilombo',
 'Els Catarres',
 'Boikot',
 'M-Clan',
 'grandson',
 'Ska-P',
 'Kodaline',
 'Marlon',
 'Txarango',
 'Joan Dausà',
 'Els Pets',
 'Baiuca',
 'Amaia Montero',
 'Nøgen',
 'El Canijo de Jerez',
 'Lauren Daigle',
 'Ghost',
 'Shinova',
 'Huecco',
 'Loquillo',
 'Air Supply',
 'Esne Beltza',
 'VK Blanka',
 'Lenny Kravitz',
 'Glenn Frey',
 'Manchester Orchestra',
 'Rawayana',
 'Bacilos',
 'KANKAKU PIERO',
 'Teejayx6',
 'Kasher Quon',
 'Famous',
 'Scarlett Miller',
 'Clairo',
 'Surf Curse',
 'Foster The People',
 'Celtas Cortos',
 'Fito y Fitipaldis',
 'Izal',
 'Sinsinati',
 'Álvaro De Luna',
 'Rulo y la contrabanda',
 'Bakar',
 'mgk',
 'YUNGBLUD',
 'The Rolling Stones',
 'Stick Figure',
 'Slightly Stoopid',
 'Djo',
 'Walls',
 'The Black Keys',
 'Mala Hierba',
 'Skillet',
 'I Prevail',
 'Vampire Weekend',
 'The Score',
 'Cam Cole',
 'Orchestral Manoeuvres In The Dark',
 'Celtian',
 'Antón Dávila',
 'TOOL',
 'Cage The Elephant',
 'Tame Impala',
 'Los Rodriguez',
 'Los De Marras',
 'coldrain',
 'Ryo',
 'Fitz and The Tantrums',
 'Liam Gallagher',
 'Serú Girán',
 'Sinkope',
 'Isma Romero',
 'Maná',
 'Sebastián Yatra',
 'Foreigner',
 'ONE OK ROCK',
 'STARSET',
 'Foals',
 "Somebody's Child",
 'Palace',
 'blackbear',
 'Keane',
 'Jadu Heart',
 'Lucas Colman',
 'Cruzando El Charco',
 'Volbeat',
 'Neil Fallon',
 'Howard Jones',
 'The Animals',
 'Allah-Las',
 'WildHeart',
 'Thorbjørn Risager & The Black Tornado',
 'The Black Tornado',
 'Rahzel',
 'Christone "Kingfish" Ingram',
 'Matt Maeson',
 'Boy Harsher',
 'carwash',
 'Beth Hart',
 'MISSIO',
 'Death Stranding: Timefall',
 'Los Zigarros',
 'Of Monsters and Men',
 'Dan Reynolds',
 'Once Monsters',
 'Gary Clark Jr.',
 'Five For Fighting',
 'Freddie Mercury',
 'Grimes',
 'Dani Filth',
 'The Raconteurs',
 'Vico y su Grupo Karicia',
 'Eyedress',
 'The Joker & The Thief',
 'Beck',
 'Local Natives',
 'Goth Babe',
 'Sean Koch',
 'X Ambassadors',
 'Kenny Wayne Shepherd',
 'Brantley Gilbert',
 'Brian May',
 'Alcest',
 'The National',
 'Mötley Crüe',
 'ZZ Top',
 'Stereophonics',
 'Delaney Jane',
 'XYLØ',
 'Declan McKenna',
 'MorMor',
 'beabadoobee',
 'The Haunt',
 'Chris Rea',
 'Reignwolf',
 'Papa Roach',
 'Rio',
 'The Cranberries',
 'Nick Waterhouse',
 'Sheryl Crow',
 'Chris Stapleton',
 'David Lebón',
 'Julieta Venegas',
 'Dayglow',
 'Set It Off',
 '仮病',
 'Calpurnia',
 'Kids That Fly',
 'Bad Touch',
 'Mollie Marriott',
 'Samantha Fish',
 'Tom Petty and the Heartbreakers',
 'American Authors',
 'She Past Away',
 'Snowy White',
 'The White Flames',
 'The Script',
 'No Te Va Gustar',
 'Draco Rosa',
 'Hamilton, Joe Frank & Reynolds',
 'Joe Frank & Reynolds',
 'Briston Maroney',
 'Airbourne',
 'Ray Pelka',
 'Benny Morrell',
 'Bryan Adams',
 'Better Oblivion Community Center',
 'Conor Oberst',
 'Phoebe Bridgers',
 'The Cold Stares',
 'Steve Lacy',
 'Ozzy Osbourne',
 'Low Hum',
 'Sublime With Rome',
 'DIIV',
 'Gary Holt',
 'Barns Courtney',
 'Lez Zeppelin',
 'The Night Flight Orchestra',
 'Zen',
 'Nevertel',
 'R.E.M.',
 'American Football',
 'Hayley Williams',
 'The Unlikely Candidates',
 'The Radio Dept.',
 'Animal Sun',
 'Grizfolk',
 'Royal Republic',
 'Vacations',
 'benches',
 'N.Flying',
 'Whirr',
 'Airbag',
 'Oques Grasses',
 'El Barrio',
 'Leiva',
 'Camela',
 'Ginebras',
 'Las Chuches',
 'Rammstein',
 'Ginestà',
 'Amaral',
 'Juanes',
 'ALIS',
 'Rotten XIII',
 'Procol Harum',
 'Los Punsetes',
 'Yeah Yeah Yeahs',
 'Sofia Ellar',
 'Despistaos',
 'David Bisbal',
 'Novedades Carminha',
 'Slipknot',
 'Hozier',
 'Azken Sustraiak',
 'The Lumineers',
 'Mrs. GREEN APPLE',
 'Tom Petty',
 'Mägo de Oz',
 'OneRepublic',
 'ChocQuibTown',
 'PUBLIC',
 'Robbie Williams',
 'Jesús Adrián Romero',
 'Andrew Bird',
 'Arrested Youth',
 'Wham!',
 'Earthadox',
 'Mat4yo',
 'Kevin Krust',
 'Cam Steady',
 'J-Xtreme',
 'shattered',
 'Waste',
 'lil eli young bapestah',
 'Fat Dolsk',
 'Freshy Kanal',
 'Verónica Romero',
 'Naim',
 'Invadable Harmony',
 'Paul Carrack',
 'Sean P. Rogan',
 'The Strokes',
 'Sidecars',
 'Adormidera',
 'Antílopez',
 'Ara Malikian',
 'Aurora Beltrán',
 'BAMBIKINA',
 'Derby Motoreta’s Burrito Kachimba',
 'El Drogas',
 'Kutxi Romero',
 'La Ira',
 'Will Paquin',
 'VOILÀ',
 'AC/DC',
 'Noan',
 'Halsey',
 'Chubby Checker',
 'Nova Twins',
 '24kGoldn',
 'All Time Low',
 'Cobardes',
 "Iñaki Antón 'Uoho'",
 'Travis Birds',
 'Nation of Language',
 'Theophilus London',
 'La Maravillosa Orquesta del Alcohol',
 'Pol 3.14',
 'Cepeda',
 'Enol',
 'Talking Heads',
 'Wanda Jackson',
 'Demi Lovato',
 'Álvaro Urquijo',
 'Los Secretos',
 'Dani Martín',
 'Yusuf / Cat Stevens',
 'Panchiko',
 'Palaye Royale',
 'Loathe',
 'Oliver Tree',
 'Playa Cuberris',
 'Pedro Fernández Razkin',
 'Pearl Jam',
 'Las Pastillas del Abuelo',
 'Bersuit Vergarabat',
 'Marcus King',
 'Funambulista',
 'Amenoskuarto',
 'AWOLNATION',
 'Bombay Bicycle Club',
 'Luis Alberto Spinetta',
 'TTRRUUCES',
 'Jaime Enrique Aymara',
 'Metallica',
 'San Francisco Symphony',
 'Eilen Jewell',
 'Jerry Lee Lewis',
 'Toño y su Grupo Centella',
 'Solence',
 'The Killers',
 'Hollow Ship',
 'Deftones',
 'Los Diablitos',
 'Hotel Ugly',
 'Awaken I Am',
 'Amy Lee',
 'Cory Marks',
 'Travis Tritt',
 'Ivan Moody',
 'Mick Mars',
 'Sun Room',
 'Bayronn Caicedo',
 'Avenged Sevenfold',
 'julie',
 'SiM',
 'Rain City Drive',
 'Peter Hook',
 'Georgia',
 'Betcha',
 'Mareux',
 "Autumn's Midnight",
 'Rata Blanca',
 'Other Lives',
 'Smash Into Pieces',
 'The 1975',
 'Foxy Shazam',
 'Conociendo Rusia',
 'Fito Paez',
 'Communicant',
 'Syndie Jo',
 'Temples',
 'Slomosa',
 'Vestron Vulture',
 'The Happy Fits',
 'Crash Adams',
 'Autumn Kings',
 'ISCREAM NEVER GROUND',
 'Christopher Cross',
 "J-ROCK'S",
 'もっさ',
 'Deep Purple',
 'The Rumpled',
 'The Rumjacks',
 'Beach Bunny',
 'Veni Vidi Vici',
 'Sam Tinnesz',
 'Poligamia',
 'flipturn',
 'Kyle Sparkman',
 'Tami Neilson',
 'Byron Solis',
 'George Barnett',
 'POORSTACY',
 'The Sweet Serenades',
 'Green Day',
 'Sir Chloe',
 'Black Stone Cherry',
 'Blind Channel',
 'Clutch',
 'Jonathan Bree',
 'Bad Nerves',
 'Linkin Park',
 'Los Internacionales Nenes de la Cumbia',
 'Arde Bogotá',
 'La Oreja de Van Gogh',
 'Maldita Nerea',
 'Vetusta Morla',
 'The Ronettes',
 'Eve',
 'Suu',
 'Bee Gees',
 'LiSA',
 'Paula Mattheus',
 'Cesk Freixas',
 'Valeria Castro',
 'El Mató a un Policía Motorizado',
 'RAT BOY',
 'ZOO',
 'Arco',
 'Pau Vallvé',
 'Miss Caffeina',
 'Pajaro Sunrise',
 'Anıl Emre Daldal',
 'Fondo Flamenco',
 'El Zar',
 'BLUE ENCOUNT',
 'Dynazty',
 'Brent Cobb',
 'Willie Nelson',
 'Glass Animals',
 'Bolo Zeus',
 'NerdOut',
 'J.Broady',
 'Gbaskill-D',
 'The Whistlers',
 'NAMOS',
 'Terry Borderline',
 "Sassy D'estany",
 'Safiya',
 'Booski3',
 'Masilo The Healer',
 'Da Souza',
 'Carlota Flâneur',
 'Jero Romero',
 'Marsella',
 'Gerard Aledo',
 "Lal'Ba",
 'Phoac',
 'Trapped Ants',
 'Malos Trapos',
 'Magalí Sare',
 'Pau Brugada',
 'John Doe The First',
 'Duncan Dhu',
 'Billy Chester',
 'Robert Hesser',
 'Robe',
 'Benito Kamelas',
 'Pole.',
 'C. Tangana',
 'Andrés Calamaro',
 'late night drive home',
 'The Offspring',
 'Xavi Castle',
 'Mikel Erentxun',
 'Santi Balmes',
 'Víctor Cabezuelo',
 'Los Fabulosos Cadillacs',
 'Billy Idol',
 'Joy',
 'Miley Cyrus',
 'WATT',
 'Elton John',
 'Yo-Yo Ma',
 'Robert Trujillo',
 'Chad Smith',
 'Chris Norman',
 'Suzi Quatro',
 'Poncho K',
 'Walls, Daniel Sabater',
 'Royal Blood',
 'Nessa Barrett',
 'jxdn',
 'Del Water Gap',
 'Kamikazes',
 'llvna',
 'Manolo Garcia',
 'Vicente Amigo',
 'Sublevados',
 'Caskets',
 'KALEO',
 'Milky Chance',
 'Fran Mariscal',
 'Ciudad Jara',
 'Hens',
 'Cableados',
 'Pardaos',
 'Descendientes',
 'Comida Para Pezes',
 'J Heras',
 'Dudi',
 'Manu Cort',
 'Saint Motel',
 'Alejandro Sanz',
 'BER',
 'ERRE',
 'EKKSTACY',
 'Gary Moore',
 'Lemmy',
 'Motörhead',
 'Estopa',
 'A Day To Remember',
 'Venturi',
 'Marmi',
 'Holding Absence',
 'Sôber',
 'Lynyrd Skynyrd',
 'Radiohead',
 'Biffy Clyro',
 'Iggy Pop',
 'Nirvana',
 'Argonaut & Wasp',
 'Pale Waves',
 'Limp Bizkit',
 'Still Corners',
 'Our Last Night',
 'Jeris Johnson',
 'Ida Maria',
 'Foo Fighters',
 'Saint Chaos',
 'Richard Ashcroft',
 'Tom Morello',
 'Wet Leg',
 'WILLOW',
 "Rag'n'Bone Man",
 'Jackie Venson',
 'Los Auténticos Decadentes',
 'Natalia Lafourcade',
 'Against The Current',
 'Kevin Walkman',
 'Chacalon Jr',
 'Sarmad',
 'Tufic',
 'Stellar',
 'Friday Pilots Club',
 'Bayron Caicedo',
 'Mati Sertic',
 'Citizen Soldier',
 'Neeus',
 'Gerardo Moran',
 'Wilderado',
 'Lovejoy',
 'Mon Laferte',
 'Keanu Bicol',
 'Inhaler',
 'Luke Hemmings',
 'Kings of Leon',
 'Maggie Lindemann',
 'Kellin Quinn',
 'Xdinary Heroes',
 'Girl and Girl',
 'John Mayer',
 'Weathers',
 'Memo Boy',
 'Grauzone',
 'Eldar Kedem',
 'iann dior',
 'Alessia Cara',
 'Evanescence',
 'Lonely God',
 'midwxst',
 'Warren Zeiders',
 'With Confidence',
 'Dead Sara',
 'Star Band de Luis Alfredo',
 'The Orion Experience',
 'ILLENIUM',
 'Sueco',
 'Trippie Redd',
 'Mammoth',
 'Milicia',
 'Widinson',
 'Lord Huron',
 'Mogwai',
 'Phoneboy',
 'Justin Magnaye',
 'Jocelyn & Chris Arndt',
 'Smith/Kotzen',
 'Adrian Smith',
 'Richie Kotzen',
 'Dropkick Murphys',
 'The Plot In You',
 'Airways',
 'MARLENA',
 'Miguel Campello',
 'Comandante Twin',
 'Sting',
 'Nunatak',
 'Phil Collins',
 'Mama Dousha',
 'The Tyets',
 'Scotty DK',
 'ajan',
 'Joost',
 'Celebration Guns',
 'La Decada Prodigiosa',
 'KISS',
 'Royel Otis',
 'Juancho Sidecars',
 'Funzo & Baby Loud',
 'ThxSoMch',
 'Paula Koops',
 'Marea',
 'Alex Wall',
 'Christian Nodal',
 'Motionless In White',
 'La La Love You',
 'Charlie USG',
 'Bad Omens',
 'D.Valentino',
 'Rakeem',
 'Leon Bridges',
 'Connor Kauffman',
 'JFM',
 'Grover Washington, Jr.',
 'Bill Withers',
 'Red Hot Chili Peppers',
 'The Surfaris',
 'Los Suaves',
 'Mick Gordon',
 'Arctic Monkeys',
 'Tam Tam Go!',
 'Mikel Izal',
 'Placebo',
 'Black Country, New Road',
 'mafalda cardenal',
 'Paul Alone',
 'Goodbye June',
 'alt-J',
 'quannnic',
 'Sigur Rós',
 'almost monday',
 'Nickelback',
 'Los Abuelos De La Nada',
 'Men I Trust',
 'The Smile',
 'Ed Sheeran',
 'Bob Moses',
 'Portugal. The Man',
 'Tomas Chris',
 'Band of Horses',
 'Maria De Los Angeles',
 'Mother Mother',
 'Mabell de la Rosa',
 'Scorpions',
 'Juanita Burbano',
 'Pixies',
 'Jack Johnson',
 'Piti Fernández',
 'Chri$tian Gate$',
 'Teddy Swims',
 'Judge & Jury',
 'Surf Hat',
 'Cal in Red',
 'PERSONA 749',
 'Generación 12',
 'Mick Jagger',
 'Black Pontiac',
 'H.E.A.T',
 'Azucena Aymara',
 'French Police',
 'Sunflower Bean',
 'glaive',
 'Michael Jackson',
 'State of Mine',
 'Arcade Fire',
 "Why Don't We",
 'Sundazer',
 'Madrugada',
 'The Kooks',
 'Jeff Beck',
 'Charlotte Sands',
 'Midrift',
 'GHOSTWOMAN',
 'Drugdealer',
 'Kakkmaddafakka',
 'Pepe Richard',
 'Rock Star',
 'The Orphan The Poet',
 'MYTCH',
 'Lø Spirit',
 'Orión',
 'Luisa Vox',
 'José Lucas',
 'Sexy Zebras',
 'Depeche Mode',
 'House Of Pain',
 'Elefantes',
 'Zea Mays',
 'Los Zopilotes Txirriaos',
 'Bomba Estéreo',
 'Second',
 'RADWIMPS',
 'Florence + The Machine',
 'We Came As Romans',
 'LOUTA',
 'Fontaines D.C.',
 'Level 42',
 'El Cuarteto De Nos']

In [27]:
pd.DataFrame(lista_artistas_rock)

                      0
0          Unorthodocks
1              Funk.Shu
2                  Taxi
3            Anne-Marie
4                 KREAM
..                  ...
840   We Came As Romans
841               LOUTA
842      Fontaines D.C.
843            Level 42
844  El Cuarteto De Nos

[845 rows x 1 columns]

hubo que agregar 3 cosas: 
headers = {'User-Agent': 'MiBootcampApp/1.0'} # <--- Esto es vital para evitar el 403

 print(f"❌ Error 403 en {artista}: Revisa tu API Key o el User-Agent.")
            break # Si es 403, mejor paramos para investigar
            
        # Un pequeño respiro para no saturar la API
        time.sleep(0.1)

In [ ]:
import requests
import time

# 1. Tu configuración (Revisa bien tu API Key)
api_key_last_fm = "dffc96fb5e37b49d6382379a54a66094"
headers = {'User-Agent': 'MiBootcampApp/1.0'} # <--- Esto es vital para evitar el 403
url = "http://ws.audioscrobbler.com/2.0/"

diccionario_rock = {"artista" : [], "audiencia" : [], "reproducciones" : [], "similares" : [], "biografia": []}

for artista in lista_artistas_rock:
    # 2. NO pongas los datos en la URL manualmente. 
    # Deja que 'requests' se encargue de limpiar los espacios y tildes.
    parametros = {
        "method": "artist.getinfo",
        "artist": artista,
        "api_key": api_key_last_fm,
        "format": "json"
    }

    try:
        # Pasamos los parámetros por separado
        response = requests.get(url, params=parametros, headers=headers)
        
        if response.status_code == 200:
            datos_api = response.json()
            
            if 'artist' in datos_api:
                info = datos_api['artist']
                
                diccionario_rock["artista"].append(info.get('name', artista))
                diccionario_rock["audiencia"].append(info['stats'].get('listeners', 0))
                diccionario_rock["reproducciones"].append(info['stats'].get('playcount', 0))
                
                # Extraemos similares (si existen)
                similares = [s['name'] for s in info.get('similar', {}).get('artist', [])]
                diccionario_rock["similares"].append(similares)
                
                # Biografía
                bio = info.get('bio', {}).get('content', 'Sin biografía')
                diccionario_rock["biografia"].append(bio)
                
                print(f"✅ {artista} recuperado correctamente.")
            else:
                print(f"⚠️ {artista} no existe en Last.fm.")
        
        elif response.status_code == 403:
            print(f"❌ Error 403 en {artista}: Revisa tu API Key o el User-Agent.")
            break # Si es 403, mejor paramos para investigar
            
        # Un pequeño respiro para no saturar la API
        time.sleep(0.1)

    except Exception as e:
        print(f"💥 Error inesperado con {artista}: {e}")

print("Proceso terminado.")

✅ Unorthodocks recuperado correctamente.
✅ Funk.Shu recuperado correctamente.
✅ Taxi recuperado correctamente.
Proceso terminado.

In [29]:
diccionario_rock

{'artista': ['Unorthodocks', 'funk.shu', 'Taxi'],
 'audiencia': ['535', '1155', '100928'],
 'reproducciones': ['2126', '3536', '980178'],
 'similares': [['Bane Capital',
   'Stack Skrilla',
   'SmooVth',
   'keevin',
   'Daniel Son'],
  ['One t.w.o.', 'Defla', 'pjzero', 'SHHP', 'mellowmnd'],
  ['Cargo', 'Voltaj', 'Bosquito', 'VAMA', 'Vita de Vie']],
 'biografia': ['',
  '',
  'There are several artists known as Taxi:\n\n1. Taxi (Gibraltar) Born from the ashes of Gibraltar based Melon Diesel,Taxi was born in 2004 formed by Dylan Ferro(Vocals),Dani Fa (Guitars) and Danny Bugeja (Guitars). Having sold more than a quarter of a million copies in their musical career, Taxi are currently promoting their new album "MIRANDO ATRAS",a collection of their greatest hits including 2 new songs and a cover version of Gun..s "Better Days" due 9th September. Their album "Aqui y Ahora"got a Latin Grammy nomination. See www.taxi.com.es\n\n2. Taxi (Portugal) a Rock band, influenced by Ska and New Wave. Formed in 1979, their first hit was "Chiclete" (1981), turning them into one of the most successful Portuguese rock bands in the first half of the eighties. They released 4 albums via PolyGram and made other contributions in the Portuguese music scene. They\'ve been mostly inactive since 1998, but meet up occasionally for the odd gig.\n\n3. TAXI (UK) Popular underground band - minimalist electro soul/house with vox. Originally signed to INFRACOM Records.  From Norwich, UK. Formed in 2001. Paul Cullen, SImon Lovejoy, Jo Laundy, Alexa Longman. Find their back catalogue and new material here: http://soundcloud.com/hairytunes\n\n4. Taxi (Romania) are a Pop-Rock band. Their sound is an eclectic mix of rock and contemporary pop, occasionally introducing other influences such as hot Nashville-style guitar licks.\n\nThe band was founded March 13, 1999 in Bucharest. Dan Teodorescu, songwriter, lead vocalist and the band\'s leader, first recruited Adrian Bortun, with whom he had previously played in Altceva ("Something Else"). Bortun recruited his former band mate Andrei Bărbulescu from Sarmalele Reci ("The Cold Sarmale"; sarmale are meat rolls with cabbage); Dan recruited Georgică Pătrănoiu with whom he had also played before. www.trupataxi.ro\n\n5. Taxi (Thailand)  Taxi is a group of rock artists from the GMM Grammy label who performed music from 2001 - 2006. The band consists of 4 members: Rahat Ratchakam (Kob) - vocalist. Lead and Guitar, Amornthep Kitilap (Pam) - Guitar, Arkom Nuchanil (Ek) - Bass Guitar and Jintakorn Suwanhong (Oh) - Drums. The band had had a total of 5 studio albums and 1 special album before they disbanded in 2006.\n\nTranslated from: แท็กซี่ เป็นกลุ่มศิลปินเพลงร็อกจากจีเอ็มเอ็ม แกรมมี่ มีผลงานเพลงในช่วงระหว่างปี พ.ศ. 2544 - 2549 โดยสมาชิกในวง 4 คนประกอบไปด้วย ระหัส ราชคำ (กบ) - ตำแหน่งร้องนำและกีตาร์ , อมรเทพ กิติลาภ (แป๋ม) - กีตาร์ , อาคม นุชนิล (เอก) - กีตาร์เบส และ จินตกร สุวรรณหงส์ (โอ๋) - กลอง มีผลงานสตูดิโออัลบั้มทั้งหมด 5 ชุด และมีอัลบั้มพิเศษ 1 ชุด ก่อนที่สมาชิกจะแยกวงกันไปในปี พ.ศ. 2549\n\n6. Taxi (Italy) ??\n\n7. Taxi (Switzerland) ???\n\n8. Taxi (Sweden) ????\n\n9. Taxi (Bulgaria) ?????\n\n10. Taxi (Australia) funk band, a Malvern based UK Rock\'n\'Roll band\n\n11. Taxi (Czech Republic) was a rock band, that existed in 1986-1991\n\n12. Taxi (Greece) was a greek rock band in 1980 and its members were: Nikos Karvelas (lyrics, music & keyboards), Giannis Saroglou (Lead vocals, bass & guitar), Nikos Politis (Guitar & harmonica) and Richard Whitman (Drums).\n\n13. Taxi (Brazil) was a funk/soul band, that existed in 1979-1980 formed by Max, Amaro e Camarão.\n\n14. Taxi [San Francisco, CA] is an SF emo band <a href="https://www.last.fm/music/Taxi">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.']}

In [30]:
pd.DataFrame(diccionario_rock)

,artista,audiencia,reproducciones,similares,biografia
0,Unorthodocks,535,2126,"[Bane Capital, Stack Skrilla, SmooVth, keevin,...",
1,funk.shu,1155,3536,"[One t.w.o., Defla, pjzero, SHHP, mellowmnd]",
2,Taxi,100928,980178,"[Cargo, Voltaj, Bosquito, VAMA, Vita de Vie]",There are several artists known as Taxi:\n\n1....

In [36]:
#guardamos el dataframe
df_rock_lastfm = pd.DataFrame(diccionario_rock)

In [37]:
df_rock_lastfm.to_json('files/datos_rock_apilastfm.json', orient='records', indent=4, force_ascii=False)

print("¡Archivo JSON guardado con éxito!")

¡Archivo JSON guardado con éxito!